import React,{createContext,useContext,useEffect,useState} from 'react';
import {Platform} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {Auth0Provider,useAuth0} from 'react-native-auth0';
import {request} from './api';
export interface User {id:string;name:string;role:string;language:'en'|'ta';consents:Record<string,boolean>}
interface Session {user:User|null;loading:boolean;demo:boolean;login:(handle?:string)=>Promise<void>;logout:()=>Promise<void>;api:<T>(path:string,body?:unknown,method?:string)=>Promise<T>;refresh:()=>Promise<void>}
const Context=createContext<Session|null>(null);
export const useSession=()=>{const s=useContext(Context);if(!s)throw new Error('Session provider missing');return s;};
const demo=process.env.EXPO_PUBLIC_APP_MODE==='demo';
const storage={get:()=>Platform.OS==='web'?Promise.resolve(sessionStorage.getItem('kamraw-demo')):SecureStore.getItemAsync('kamraw-demo'),set:(value:string)=>Platform.OS==='web'?Promise.resolve(sessionStorage.setItem('kamraw-demo',value)):SecureStore.setItemAsync('kamraw-demo',value),clear:()=>Platform.OS==='web'?Promise.resolve(sessionStorage.removeItem('kamraw-demo')):SecureStore.deleteItemAsync('kamraw-demo')};
function Demo({children}:{children:React.ReactNode}){const [handle,setHandle]=useState<string|null>(null),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{void storage.get().then(async h=>{if(h){const u=await request<User>('/me',`demo:${h}`);setHandle(h);setUser(u);}}).catch(()=>storage.clear()).finally(()=>setLoading(false));},[]);const api=<T,>(path:string,body?:unknown,method?:string)=>request<T>(path,handle?`demo:${handle}`:undefined,body,method);return <Context.Provider value={{user,loading,demo:true,api,login:async(h='customer')=>{const u=await request<User>('/me',`demo:${h}`);await storage.set(h);setHandle(h);setUser(u);},logout:async()=>{await storage.clear();setHandle(null);setUser(null);},refresh:async()=>setUser(await api<User>('/me'))}}>{children}</Context.Provider>;}
function Live({children}:{children:React.ReactNode}){const auth=useAuth0(),[user,setUser]=useState<User|null>(null);const api=async<T,>(path:string,body?:unknown,method?:string)=>{const c=await auth.getCredentials();return request<T>(path,c?.accessToken,body,method);};useEffect(()=>{if(auth.user)void api<User>('/me').then(setUser).catch(()=>setUser(null));else setUser(null);},[auth.user]);return <Context.Provider value={{user,loading:auth.isLoading,demo:false,api,login:async()=>{await auth.authorize({scope:'openid profile email offline_access',audience:process.env.EXPO_PUBLIC_AUTH0_AUDIENCE},{customScheme:'kamraw'});},logout:async()=>{await auth.clearSession({}, {customScheme:'kamraw'});setUser(null);},refresh:async()=>setUser(await api<User>('/me'))}}>{children}</Context.Provider>;}
export function SessionProvider({children}:{children:React.ReactNode}){if(demo)return <Demo>{children}</Demo>;const domain=process.env.EXPO_PUBLIC_AUTH0_DOMAIN,clientId=process.env.EXPO_PUBLIC_AUTH0_CLIENT_ID;if(!domain||!clientId)return <Context.Provider value={{user:null,loading:false,demo:false,login:async()=>{throw new Error('Sign-in is not configured yet. Please contact Kamraw.');},logout:async()=>{},api:async()=>{throw new Error('Sign-in required');},refresh:async()=>{}}}>{children}</Context.Provider>;return <Auth0Provider domain={domain} clientId={clientId}><Live>{children}</Live></Auth0Provider>;}
