import React,{useEffect,useState} from 'react';
import {Aperture,LayoutDashboard,CalendarDays,Users,Image,Wallet,LifeBuoy,Settings2,ShieldCheck,LogOut,UploadCloud,ChevronDown,ArrowRight,Menu} from 'lucide-react';
import {SessionProvider,useSession} from './auth';
import {Audit,Bookings,Configuration,Creators,Finance,Overview,Quality,Support,Safety} from './Operations';
import {Notice,useAction} from './ui';
import {Uploader} from './Uploader';
import {GuestGallery} from './GuestGallery';
function Login(){const {login,demo,error}=useSession(),a=useAction(),[handle,setHandle]=useState('ops');return <main className="login"><div className="login-art"><a className="brand" href="/">kamraw<span>.</span></a><p className="eyebrow">BEHIND EVERY GOOD MOMENT</p><h1>Good people.<br/>Beautiful work.<br/>Promises kept.</h1><div className="login-orbit"><Aperture size={100} strokeWidth={.75}/></div><p>The workspace that keeps Chennai’s moments in focus.</p></div><div className="login-form"><p className="eyebrow">COMMAND CENTRE</p><h2>A clear view.<br/>A calm start.</h2><p>Sign in to manage the people, shoots and memories behind Kamraw.</p><Notice error={a.error??error}/>{demo&&<label className="field"><span>Choose a demo workspace</span><select value={handle} onChange={e=>setHandle(e.target.value)}><option value="ops">Operations · Full demo access</option><option value="creator">Creator · Uploads</option><option value="finance">Finance · Payout maker</option><option value="approver">Finance · Approver</option></select></label>}<button className="button" disabled={a.busy} onClick={()=>void a.run(()=>login(demo?handle:undefined))}>{a.busy?'Opening workspace…':demo?'Enter demo workspace':'Sign in with SSO'}<ArrowRight size={18}/></button><a className="text-button" href="/app">Open customer & creator app <ArrowRight size={16}/></a><small>{demo?'A sandbox with sample accounts and simulated payments.':'Staff access requires multi-factor authentication.'}</small></div></main>;}
const items=[{label:'Overview',icon:LayoutDashboard,roles:['super_admin','city_ops','dispatcher']},{label:'Bookings',icon:CalendarDays,roles:['super_admin','city_ops','dispatcher']},{label:'Creators',icon:Users,roles:['super_admin','city_ops','verifier']},{label:'Media & QC',icon:Image,roles:['super_admin','qc']},{label:'Finance',icon:Wallet,roles:['super_admin','finance','finance_approver']},{label:'Safety',icon:ShieldCheck,roles:['super_admin','city_ops','dispatcher']},{label:'Support',icon:LifeBuoy,roles:['super_admin','city_ops','support']},{label:'Configuration',icon:Settings2,roles:['super_admin','city_ops','finance_approver']},{label:'Audit trail',icon:ShieldCheck,roles:['super_admin']},{label:'Web uploader',icon:UploadCloud,roles:['creator']}];
function Workspace(){const {user,demo,logout,loading}=useSession(),[active,setActive]=useState(''),[menu,setMenu]=useState(false);const allowed=items.filter(i=>i.roles.includes(user?.role??'')),current=active||allowed[0]?.label||'';useEffect(()=>{let timeout:ReturnType<typeof setTimeout>;const reset=()=>{clearTimeout(timeout);timeout=setTimeout(logout,30*60000);};window.addEventListener('pointerdown',reset);window.addEventListener('keydown',reset);reset();return ()=>{clearTimeout(timeout);window.removeEventListener('pointerdown',reset);window.removeEventListener('keydown',reset);};},[user?.id]);if(loading)return <div className="setup">Opening Kamraw…</div>;if(!user)return <Login/>;return <div className="shell"><aside className={menu?'sidebar open':'sidebar'}><a href="/" className="brand">kamraw<span>.</span></a><span className="workspace-label">COMMAND CENTRE</span><div className="city-switch"><div className="city-icon">C</div><div><strong>Chennai</strong><small>Pilot workspace</small></div><ChevronDown size={16}/></div><span className="nav-label">WORKSPACE</span><nav aria-label="Workspace navigation">{allowed.map(({label,icon:Icon})=><button aria-current={current===label?'page':undefined} className={current===label?'active':''} key={label} onClick={()=>{setActive(label);setMenu(false);}}><Icon size={18}/>{label}{label==='Overview'&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><p>Every moment matters.<br/><span>The work behind it does, too.</span></p><button onClick={logout}><LogOut size={17}/>Sign out</button></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu" aria-label="Open menu" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><span>Workspace</span><span>/</span><strong>{current}</strong></div><div className="topbar-right"><span className="mode-label"><i/>{demo?'Demo environment':'Live workspace'}</span><span className="divider"/><div className="user-avatar">{user.name[0]}</div><span className="user-name">{user.name.split(' · ')[0]}</span></div></header><main className="main">{current==='Overview'?<Overview onNavigate={setActive}/>:current==='Bookings'?<Bookings/>:current==='Creators'?<Creators/>:current==='Media & QC'?<Quality/>:current==='Finance'?<Finance/>:current==='Safety'?<Safety/>:current==='Support'?<Support/>:current==='Configuration'?<Configuration/>:current==='Audit trail'?<Audit/>:current==='Web uploader'?<Uploader/>:<div className="panel form-panel"><h1>Workspace access needed</h1><p>Your account is not assigned a staff or creator workspace.</p></div>}<footer className="workspace-footer"><span>Kamraw · Made for moments that matter.</span><span>Chennai · India Standard Time</span></footer></main></div></div>;}
export default function App(){const match=location.pathname.match(/^\/g\/([\w-]+)$/);if(match)return <GuestGallery token={match[1]!}/>;return <SessionProvider><Workspace/></SessionProvider>;}
