import React,{createContext,useContext,useEffect,useState} from 'react';
import {Auth0Provider,useAuth0} from '@auth0/auth0-react';
import {request,type User} from './api';
interface Auth {user:User|null;token:()=>Promise<string>;login:(handle?:string)=>Promise<void>;logout:()=>void;loading:boolean;demo:boolean;error:string|null}
const Ctx=createContext<Auth|null>(null);
export function useSession(){return useContext(Ctx)!;}
function Demo({children}:{children:React.ReactNode}){const [handle,setHandle]=useState(sessionStorage.getItem('kamraw-demo-web')),[user,setUser]=useState<User|null>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(!!handle);useEffect(()=>{if(handle)void request<User>('/me',`demo:${handle}`).then(setUser).catch(e=>{setError(e.message);setHandle(null);sessionStorage.removeItem('kamraw-demo-web');}).finally(()=>setLoading(false));},[handle]);const login=async(h='ops')=>{setError(null);const u=await request<User>('/me',`demo:${h}`);setUser(u);setHandle(h);sessionStorage.setItem('kamraw-demo-web',h);};return <Ctx.Provider value={{user,error,loading,demo:true,login,token:async()=>`demo:${handle}`,logout:()=>{sessionStorage.removeItem('kamraw-demo-web');setUser(null);setHandle(null);}}}>{children}</Ctx.Provider>;}
function Live({children}:{children:React.ReactNode}){const auth=useAuth0(),[user,setUser]=useState<User|null>(null),[error,setError]=useState<string|null>(null);useEffect(()=>{if(auth.isAuthenticated)void auth.getAccessTokenSilently().then(t=>request<User>('/me',t??null)).then(setUser).catch(e=>setError(e.message));},[auth.isAuthenticated]);return <Ctx.Provider value={{user,error,loading:auth.isLoading,demo:false,token:async()=>{const t=await auth.getAccessTokenSilently();if(!t)throw new Error('Sign-in token unavailable');return t;},login:async()=>auth.loginWithRedirect(),logout:()=>auth.logout({logoutParams:{returnTo:location.origin}})}}>{children}</Ctx.Provider>;}
export function SessionProvider({children}:{children:React.ReactNode}){if(import.meta.env.VITE_APP_MODE==='demo')return <Demo>{children}</Demo>;const domain=import.meta.env.VITE_AUTH0_DOMAIN,clientId=import.meta.env.VITE_AUTH0_CLIENT_ID;if(!domain||!clientId)return <div className="setup"><h1>Sign-in setup needed</h1><p>Configure the Kamraw Auth0 application before using the command centre.</p></div>;return <Auth0Provider domain={domain} clientId={clientId} authorizationParams={{redirect_uri:location.origin,audience:import.meta.env.VITE_AUTH0_AUDIENCE}} cacheLocation="memory"><Live>{children}</Live></Auth0Provider>;}
