import React,{useState} from 'react';
import {UploadCloud,CheckCircle2,FolderOpen} from 'lucide-react';
import {base} from './api';
import {useSession} from './auth';
import {Field,Notice,useAction,useApi,useLoad} from './ui';
import {Heading} from './Operations';
interface Upload {id:string;assets:{id:string;filename:string;bytes:string;received_bytes:string;status:string}[]}
export function Uploader(){const {token}=useSession(),api=useApi(),jobs=useLoad<{id:string;code:string;status:string}[]>('/creator/jobs'),a=useAction(),[session,setSession]=useState(''),[files,setFiles]=useState<File[]>([]),[kind,setKind]=useState('original'),[progress,setProgress]=useState<Record<string,number>>({}),[receipt,setReceipt]=useState<{message:string;files:number;bytes:number;demoVerified:boolean}|null>(null);const run=()=>a.run(async()=>{if(!session||!files.length)throw new Error('Choose a completed session and select your card files.');if(files.reduce((n,f)=>n+f.size,0)>50*1024**2)throw new Error('Demo uploads are limited to 50 MB per card.');setReceipt(null);const key=`kamraw-upload:${session}:${kind}`,signature=files.map(f=>`${f.name}:${f.size}:${f.lastModified}`).join('|');let upload:Upload;const saved=localStorage.getItem(key);if(saved&&JSON.parse(saved).signature===signature){upload=await api<Upload>(`/uploads/${JSON.parse(saved).id}`);}else{const manifest=await Promise.all(files.map(async f=>({filename:f.name,bytes:f.size,kind,checksum:Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await f.arrayBuffer()))).map(b=>b.toString(16).padStart(2,'0')).join('')})));upload=await api<Upload>('/uploads',{sessionId:session,files:manifest});localStorage.setItem(key,JSON.stringify({id:upload.id,signature}));}
const access=await token();for(const asset of upload.assets){const file=files.find(f=>f.name===asset.filename);if(!file)throw new Error(`Reselect the original file: ${asset.filename}`);let offset=Number(asset.received_bytes);if(asset.status==='verified'){setProgress(p=>({...p,[file.name]:100}));continue;}while(offset<file.size){const chunk=file.slice(offset,offset+2*1024**2);const res=await fetch(`${base}/api/assets/${asset.id}/chunks?offset=${offset}`,{method:'PUT',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/octet-stream'},body:chunk});const result=await res.json();if(!res.ok)throw new Error(result.error?.message??'Upload interrupted. Reselect the same files and resume.');if(result.data.status==='checksum_failed')throw new Error(`${file.name}: checksum mismatch. Retry this file.`);offset=result.data.receivedBytes;setProgress(p=>({...p,[file.name]:Math.round(offset/file.size*100)}));}}
setReceipt(await api(`/uploads/${upload.id}/receipt`,{}));});return <><Heading title="Every frame. Safely accounted for." eyebrow="CREATOR WEB UPLOADER" body="Select your full card, upload in resumable chunks, and verify every file before any receipt is issued."/><Notice error={a.error??jobs.error}/><section className="panel form-panel"><div className="two-fields"><Field label="Completed session"><select value={session} onChange={e=>{setSession(e.target.value);setProgress({});setReceipt(null);}}><option value="">Choose a session</option>{jobs.data?.map(j=><option value={j.id} key={j.id}>{j.code} · {j.status.replaceAll('_',' ')}</option>)}</select></Field><Field label="File set"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="original">Original captures</option><option value="edited">Edited deliverables for QC</option></select></Field></div><label className="dropzone"><UploadCloud size={40}/><strong>Every good memory starts with a full card.</strong><span>Choose files · RAW, JPEG, HEIF, MP4, MOV or WAV</span><input aria-label="Choose card files" type="file" multiple accept=".cr3,.nef,.arw,.raf,.dng,.jpg,.jpeg,.heif,.heic,.mp4,.mov,.wav" onChange={e=>{setFiles(Array.from(e.target.files??[]));setProgress({});}}/></label><p className="muted">Demo limit: 50 MB per card. After a network interruption, select the same files and choose Resume. Completed chunks are preserved.</p>{files.map(f=><div className="file-progress" key={f.name}><div className="row"><span><FolderOpen size={15}/> {f.name}</span><small>{progress[f.name]??0}%</small></div><progress max={100} value={progress[f.name]??0}/></div>)}<button className="button" disabled={a.busy||!files.length} onClick={()=>void run()}>{a.busy?'Uploading & verifying…':'Upload / resume card'}</button></section>{receipt&&<section className="receipt"><CheckCircle2 size={30}/><div><h2>{receipt.demoVerified?'Demo files verified':'Verification incomplete'}</h2><p>{receipt.files} files · {(receipt.bytes/1024**2).toFixed(2)} MB</p><strong>{receipt.message}</strong></div></section>}</>;}
