import type {MigrationInterface,QueryRunner} from 'typeorm';
export class Initial1790772000000 implements MigrationInterface {
  name='Initial1790772000000';
  async up(r:QueryRunner):Promise<void> {await r.query(`
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE SEQUENCE booking_number START 10001;
CREATE TABLE accounts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subject text UNIQUE NOT NULL,name text NOT NULL,language text NOT NULL DEFAULT 'en' CHECK(language IN ('en','ta')),role text NOT NULL DEFAULT 'customer',consents jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE configurations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL,version int NOT NULL,value jsonb NOT NULL,status text NOT NULL DEFAULT 'draft',created_by uuid NOT NULL REFERENCES accounts,approved_by uuid REFERENCES accounts,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(kind,version),CHECK(approved_by IS NULL OR approved_by<>created_by));
CREATE UNIQUE INDEX active_config ON configurations(kind) WHERE status='active';
CREATE TABLE quotes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),customer_id uuid NOT NULL REFERENCES accounts,input jsonb NOT NULL,price jsonb NOT NULL,expires_at timestamptz NOT NULL,order_id uuid,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text NOT NULL UNIQUE DEFAULT ('KMR-'||nextval('booking_number')),customer_id uuid NOT NULL REFERENCES accounts,quote_id uuid UNIQUE NOT NULL REFERENCES quotes,status text NOT NULL DEFAULT 'payment_pending',category text NOT NULL,total_paise int NOT NULL CHECK(total_paise>0),currency text NOT NULL DEFAULT 'INR' CHECK(currency='INR'),created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE quotes ADD CONSTRAINT quote_order_fk FOREIGN KEY(order_id) REFERENCES orders;
CREATE INDEX customer_orders ON orders(customer_id,created_at DESC);
CREATE TABLE sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid NOT NULL REFERENCES orders,input jsonb NOT NULL,status text NOT NULL DEFAULT 'confirmed',start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,zone_id text NOT NULL,total_paise int NOT NULL CHECK(total_paise>0),completion_code text NOT NULL,started_at timestamptz,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),CHECK(end_at>start_at));
CREATE INDEX session_queue ON sessions(status,start_at);
CREATE TABLE creators(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid UNIQUE NOT NULL REFERENCES accounts,name text NOT NULL,status text NOT NULL DEFAULT 'applied',online boolean NOT NULL DEFAULT false,disciplines jsonb NOT NULL DEFAULT '{}',zone_ids jsonb NOT NULL DEFAULT '[]',languages jsonb NOT NULL DEFAULT '["ta"]',profile jsonb NOT NULL DEFAULT '{}',checks jsonb NOT NULL DEFAULT '{}',metrics jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE availability(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),creator_id uuid NOT NULL REFERENCES creators,start_at timestamptz NOT NULL,end_at timestamptz NOT NULL,available boolean NOT NULL,CHECK(end_at>start_at));
CREATE INDEX availability_window ON availability(creator_id,start_at,end_at);
CREATE TABLE customer_blocks(customer_id uuid NOT NULL REFERENCES accounts,creator_id uuid NOT NULL REFERENCES creators,PRIMARY KEY(customer_id,creator_id));
CREATE TABLE roles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,discipline text NOT NULL CHECK(discipline IN ('photo','video')),tier text NOT NULL CHECK(tier IN ('T1','T2','T3')),creator_id uuid REFERENCES creators,status text NOT NULL DEFAULT 'confirmed',earning_paise int NOT NULL CHECK(earning_paise>=0),lead boolean NOT NULL DEFAULT false,reserved_start timestamptz NOT NULL,reserved_end timestamptz NOT NULL,CHECK((discipline='photo' AND tier IN ('T1','T2')) OR (discipline='video' AND tier IN ('T2','T3'))),CHECK(reserved_end>reserved_start),EXCLUDE USING gist(creator_id WITH =,tstzrange(reserved_start,reserved_end,'[)') WITH &&) WHERE(creator_id IS NOT NULL AND status NOT IN ('cancelled','refunded')));
CREATE INDEX role_session ON roles(session_id);
CREATE TABLE offers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),role_id uuid NOT NULL REFERENCES roles,creator_id uuid NOT NULL REFERENCES creators,status text NOT NULL DEFAULT 'pending',score double precision NOT NULL,earning_paise int NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(role_id,creator_id));
CREATE INDEX creator_offers ON offers(creator_id,status,expires_at);
CREATE TABLE payment_events(id text PRIMARY KEY,order_id uuid NOT NULL REFERENCES orders,provider text NOT NULL,amount_paise int NOT NULL,currency text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_transactions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE,order_id uuid REFERENCES orders,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ledger_entries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),transaction_id uuid NOT NULL REFERENCES ledger_transactions,account text NOT NULL,amount_paise int NOT NULL CHECK(amount_paise<>0));
CREATE FUNCTION enforce_balanced_ledger() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (SELECT COALESCE(sum(amount_paise),0) FROM ledger_entries WHERE transaction_id=NEW.transaction_id)<>0 THEN RAISE EXCEPTION 'Ledger transaction is not balanced'; END IF; RETURN NULL; END $$;
CREATE CONSTRAINT TRIGGER ledger_balanced AFTER INSERT OR UPDATE ON ledger_entries DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_balanced_ledger();
CREATE TABLE refunds(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid UNIQUE NOT NULL REFERENCES sessions,amount_paise int NOT NULL,fee_paise int NOT NULL,status text NOT NULL DEFAULT 'pending',method text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE session_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,actor_id uuid NOT NULL REFERENCES accounts,client_id uuid NOT NULL,kind text NOT NULL,payload jsonb NOT NULL,device_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(actor_id,client_id));
CREATE TABLE locations(id bigserial PRIMARY KEY,session_id uuid NOT NULL REFERENCES sessions,creator_id uuid NOT NULL REFERENCES creators,lat double precision NOT NULL CHECK(lat BETWEEN -90 AND 90),lng double precision NOT NULL CHECK(lng BETWEEN -180 AND 180),accuracy double precision NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX latest_location ON locations(session_id,created_at DESC);
CREATE TABLE galleries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),order_id uuid UNIQUE NOT NULL REFERENCES orders,status text NOT NULL DEFAULT 'uploading',expires_at timestamptz,portfolio_consent boolean NOT NULL DEFAULT false,minors_present boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE uploads(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,creator_id uuid NOT NULL REFERENCES creators,expected_count int NOT NULL CHECK(expected_count>0),expected_bytes bigint NOT NULL CHECK(expected_bytes>0),status text NOT NULL DEFAULT 'uploading',receipt jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE media_assets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),upload_id uuid NOT NULL REFERENCES uploads,gallery_id uuid NOT NULL REFERENCES galleries,filename text NOT NULL,bytes bigint NOT NULL CHECK(bytes>0),checksum text NOT NULL,verified_checksum text,status text NOT NULL DEFAULT 'pending',copies int NOT NULL DEFAULT 0,storage_key text NOT NULL,received_bytes bigint NOT NULL DEFAULT 0,kind text NOT NULL DEFAULT 'original',qc_status text NOT NULL DEFAULT 'pending',width int,height int,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(upload_id,filename));
CREATE TABLE shares(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),gallery_id uuid NOT NULL REFERENCES galleries,token_hash text UNIQUE NOT NULL,kind text NOT NULL CHECK(kind IN ('public','pin','invite')),pin_hash text,invites jsonb NOT NULL DEFAULT '[]',expires_at timestamptz NOT NULL,allow_download boolean NOT NULL DEFAULT false,revoked_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE favourites(customer_id uuid NOT NULL REFERENCES accounts,asset_id uuid NOT NULL REFERENCES media_assets,PRIMARY KEY(customer_id,asset_id));
CREATE TABLE tickets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES accounts,order_id uuid REFERENCES orders,category text NOT NULL,subject text NOT NULL,body text NOT NULL,priority text NOT NULL DEFAULT 'normal',status text NOT NULL DEFAULT 'open',assignee_id uuid REFERENCES accounts,due_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ticket_messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),ticket_id uuid NOT NULL REFERENCES tickets,actor_id uuid NOT NULL REFERENCES accounts,body text NOT NULL,internal boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE incidents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES accounts,session_id uuid NOT NULL REFERENCES sessions,kind text NOT NULL,location jsonb,notes text NOT NULL,status text NOT NULL DEFAULT 'open',acknowledged_by uuid REFERENCES accounts,acknowledged_at timestamptz,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ratings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,rater_id uuid NOT NULL REFERENCES accounts,kind text NOT NULL,stars int NOT NULL CHECK(stars BETWEEN 1 AND 5),comment text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(session_id,rater_id,kind));
CREATE TABLE messages(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),session_id uuid NOT NULL REFERENCES sessions,actor_id uuid NOT NULL REFERENCES accounts,body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE payout_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_by uuid NOT NULL REFERENCES accounts,approved_by uuid REFERENCES accounts,status text NOT NULL DEFAULT 'draft',total_paise int NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),CHECK(approved_by IS NULL OR approved_by<>created_by));
CREATE TABLE payout_items(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),run_id uuid NOT NULL REFERENCES payout_runs,role_id uuid NOT NULL REFERENCES roles,creator_id uuid NOT NULL REFERENCES creators,portion text NOT NULL,amount_paise int NOT NULL,status text NOT NULL DEFAULT 'pending',UNIQUE(role_id,portion));
CREATE TABLE print_orders(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),customer_id uuid NOT NULL REFERENCES accounts,gallery_id uuid NOT NULL REFERENCES galleries,configuration jsonb NOT NULL,address jsonb NOT NULL,status text NOT NULL DEFAULT 'draft',total_paise int,partner_reference text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE privacy_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),account_id uuid NOT NULL REFERENCES accounts,kind text NOT NULL,status text NOT NULL DEFAULT 'pending',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit(id bigserial PRIMARY KEY,actor_id uuid REFERENCES accounts,action text NOT NULL,entity_id text NOT NULL,details jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE FUNCTION immutable_record() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Append-only record'; END $$;
CREATE TRIGGER audit_immutable BEFORE UPDATE OR DELETE ON audit FOR EACH ROW EXECUTE FUNCTION immutable_record();
CREATE TRIGGER ledger_immutable BEFORE UPDATE OR DELETE ON ledger_entries FOR EACH ROW EXECUTE FUNCTION immutable_record();
CREATE TABLE outbox(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),kind text NOT NULL,entity_id text NOT NULL,payload jsonb NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending',attempts int NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX outbox_pending ON outbox(status,next_attempt_at);
`);}
  async down():Promise<void> {throw new Error('Initial migration is irreversible: restore a verified backup to protect financial and audit records');}
}
