import {PhoneSignIn} from '../components/phone-sign-in';
import React,{useState} from 'react';
import {ActivityIndicator,Switch,Text,View} from 'react-native';
import Feather from '@expo/vector-icons/Feather';
import {useNavigation,type NavigationProp,type StaticScreenProps} from '@react-navigation/native';
import {Button,Card,Chips,ErrorNotice,Field,Page,color,styles} from '../components/ui';
import {useSession} from '../services/session';
import {CreatorMatchingProfile} from '../components/preferences';
import {CreatorPerformance} from '../components/creator-profile';
import {HelpCentre} from '../components/help-centre';
import {PaymentRecords} from '../components/payment-records';
import {PrivacyRequests} from '../components/privacy';
import {PrintOrders} from '../components/print-orders';
import {Credits} from '../components/recovery';
import {Notifications,TicketConversation} from '../components/communication';
import {useAction,useLoad} from '../services/use-load';
import type {Gallery,Routes,Order} from '../services/types';
import {translate} from '../services/strings';
export function Welcome(){const {login,demo,loading}=useSession(),a=useAction(),[phoneSignIn,setPhoneSignIn]=useState(!demo);return <Page><View style={{paddingTop:36,gap:20}}><View style={styles.row}><Text style={[styles.title,{fontSize:30,letterSpacing:-1.5}]}>kamraw<Text style={{color:color.red}}>.</Text></Text><Feather name="aperture" size={28} color={color.red}/></View><View style={{height:220,backgroundColor:'#E6E1D4',borderRadius:120,justifyContent:'center',alignItems:'center',marginVertical:20}}><View style={{width:140,height:140,borderRadius:70,borderWidth:1,borderColor:'#BDB49E',alignItems:'center',justifyContent:'center'}}><Feather name="camera" size={60} color={color.ink}/></View></View><Text style={styles.eyebrow}>CHENNAI’S MOMENTS, WELL CAPTURED</Text><Text style={[styles.title,{fontSize:44,lineHeight:48}]}>A good moment starts here.</Text><Text style={styles.subtitle}>From a first birthday to a once-in-a-lifetime yes. Find a verified creator. Be there for your moment.</Text>{demo&&<Text style={styles.label}>DEMO · Sample accounts, illustrative prices, no real payments.</Text>}<ErrorNotice message={a.error}/>{loading?<ActivityIndicator/>:<>{phoneSignIn?<PhoneSignIn/>:<Button title="Continue with your phone" onPress={()=>setPhoneSignIn(true)}/>}{demo&&<><Button title="Explore as a customer" secondary busy={a.busy} onPress={()=>void a.run(()=>login('customer'))}/><Button title="Open creator workspace" secondary busy={a.busy} onPress={()=>void a.run(()=>login('creator'))}/></>}</>}</View></Page>;}
export function ProfileScreen(){const {user,api,refresh,logout}=useSession(),a=useAction(),nav=useNavigation<NavigationProp<Routes>>(),[name,setName]=useState(user?.name??''),[language,setLanguage]=useState(user?.language??'en'),[consents,setConsents]=useState({marketing:user?.consents.marketing??false,portfolio:user?.consents.portfolio??false,guardian:user?.consents.guardian??false});const t=(key:Parameters<typeof translate>[1])=>translate(language,key);return <Page><Text style={styles.eyebrow}>{user?.role}</Text><Text style={styles.title}>{t('profile')}</Text><Field label="Name / பெயர்" value={name} onChangeText={setName}/><Text style={styles.section}>{t('language')}</Text><Chips values={['en','ta'] as const} value={language} onChange={setLanguage}/><Text style={styles.section}>{t('privacy')}</Text>{(['marketing','portfolio','guardian'] as const).map(key=><View style={styles.row} key={key}><Text style={[styles.body,{flex:1}]}>{key==='guardian'?'Guardian consent for media showing minors':t(key)}</Text><Switch accessibilityLabel={key} value={consents[key]} onValueChange={v=>setConsents({...consents,[key]:v})}/></View>)}<ErrorNotice message={a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}<Button title={t('save')} busy={a.busy} onPress={()=>void a.run(async()=>{await api('/me',{name,language,consents},'PUT');await refresh();a.setSuccess('Your preferences have been saved.');})}/>{user?.role==='customer'&&<><Credits/><PaymentRecords/><PrintOrders/></>}{user?.role==='creator'&&<><CreatorPerformance/><CreatorMatchingProfile/></>}<Notifications/><Button title={t('help')} secondary onPress={()=>nav.navigate('Support')}/><Button title="Become a Kamraw creator" secondary onPress={()=>nav.navigate('Onboarding')}/>{(['export','delete'] as const).map(kind=><Button key={kind} title={t(kind)} secondary onPress={()=>void a.run(async()=>{await api('/me/privacy',{kind});a.setSuccess(`Your ${kind==='export'?'data export':'account deletion'} request has been received.`);})}/>)}<PrivacyRequests/><Button title={t('signout')} secondary onPress={()=>void a.run(logout)}/></Page>;}
export function SupportScreen(){const {api,user}=useSession(),tickets=useLoad<{id:string;subject:string;body:string;status:string}[]>('/tickets'),a=useAction(),orders=useLoad<Order[]>('/orders'),[bookingCode,setBookingCode]=useState('No booking'),[category,setCategory]=useState<'booking'|'payment'|'quality'|'print'|'account'|'other'>('other'),[subject,setSubject]=useState(''),[body,setBody]=useState('');const t=(key:Parameters<typeof translate>[1])=>translate(user?.language??'en',key);return <Page><Text style={styles.title}>{t('supportTitle')}</Text><HelpCentre/><Text style={styles.subtitle}>For an immediate safety emergency, call 112. For booking, delivery or payment help, send us a ticket.</Text><Text style={styles.section}>{user?.language==='ta'?'கோரிக்கை வகை':'Request category'}</Text><Chips values={['booking','payment','quality','print','account','other'] as const} value={category} onChange={setCategory}/><Text style={styles.section}>{user?.language==='ta'?'தொடர்புடைய முன்பதிவு':'Related booking'}</Text><Chips values={['No booking',...(orders.data?.map(o=>o.code)??[])]} value={bookingCode} onChange={setBookingCode}/><Field label={t('subject')} value={subject} onChangeText={setSubject}/><Field label={t('details')} value={body} onChangeText={setBody} multiline/><ErrorNotice message={a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}<Button title={t('send')} busy={a.busy} onPress={()=>void a.run(async()=>{const ticket=await api<{id:string}>('/tickets',{category,subject,body,orderId:orders.data?.find(o=>o.code===bookingCode)?.id});a.setSuccess(`Ticket ${ticket.id.slice(0,8)} created. We’ll respond here.`);setSubject('');setBody('');await tickets.refresh();})}/><Text style={styles.section}>Your support requests</Text><ErrorNotice message={tickets.error}/>{tickets.data?.map(ticket=><Card key={ticket.id}><Text style={styles.label}>{ticket.status}</Text><Text style={styles.section}>{ticket.subject}</Text><Text style={styles.body}>{ticket.body}</Text><TicketConversation ticketId={ticket.id}/></Card>)}</Page>;}
export function OnboardingScreen(){const {api,user}=useSession(),a=useAction(),[name,setName]=useState(user?.name??''),[bio,setBio]=useState(''),[experience,setExperience]=useState('0'),[gear,setGear]=useState(''),[serial,setSerial]=useState(''),[emergency,setEmergency]=useState('+91'),[consent,setConsent]=useState(false);return <Page><Text style={styles.eyebrow}>CREATE WITH KAMRAW</Text><Text style={styles.title}>Good work.\nMore often.</Text><Text style={styles.subtitle}>Apply, verify your gear and identity, share your portfolio, then join a paid trial. Every discipline is reviewed separately.</Text><Field label="Your display name" value={name} onChangeText={setName}/><Field label="Tell us about your work" value={bio} onChangeText={setBio} multiline/><Field label="Years of experience" value={experience} onChangeText={setExperience} keyboardType="number-pad"/><Field label="Primary camera model" value={gear} onChangeText={setGear}/><Field label="Camera serial number" value={serial} onChangeText={setSerial}/><Field label="Emergency contact (+91)" value={emergency} onChangeText={setEmergency} keyboardType="phone-pad"/><View style={styles.row}><Text style={[styles.body,{flex:1}]}>I consent to background verification.</Text><Switch value={consent} onValueChange={setConsent} accessibilityLabel="Background verification consent"/></View><ErrorNotice message={a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}<Button title="Submit application" busy={a.busy} disabled={!consent} onPress={()=>void a.run(async()=>{await api('/creator/apply',{name,languages:['ta','en'],disciplines:{photo:'T1'},profile:{bio,experience:Number(experience),gear:[{type:'camera',model:gear,serial,ownership:'owned'}],portfolioUrls:[],emergencyContact:emergency,agreementAccepted:false,backgroundConsent:consent}});a.setSuccess('Application received. Identity verification, portfolio review, trial and training are next.');})}/></Page>;}
export function AlbumScreen({route}:StaticScreenProps<{gallery:Gallery}>){const {api}=useSession(),a=useAction(),[size,setSize]=useState<'8x8'|'10x10'|'12x12'>('8x8'),[paper,setPaper]=useState<'matte'|'gloss'>('matte'),[cover,setCover]=useState<'linen'|'hard'>('linen'),[copies,setCopies]=useState('1'),[selected,setSelected]=useState<string[]>([]),[name,setName]=useState(''),[address,setAddress]=useState(''),[phone,setPhone]=useState('+91'),[postcode,setPostcode]=useState('');const assets=route.params.gallery.assets??[];return <Page><Text style={styles.title}>Made to hold.</Text><Text style={styles.subtitle}>Choose at least 10 photos. We check 300 DPI resolution before preparing your album order.</Text><Chips values={['8x8','10x10','12x12'] as const} value={size} onChange={setSize}/><Chips values={['matte','gloss'] as const} value={paper} onChange={setPaper}/><Chips values={['linen','hard'] as const} value={cover} onChange={setCover}/><Field label="Copies (1–10)" value={copies} onChangeText={setCopies} keyboardType="number-pad"/>{assets.map(x=><Card key={x.id}><View style={styles.row}><Text style={[styles.body,{flex:1}]}>{x.filename}</Text><Switch accessibilityLabel={`Select ${x.filename}`} value={selected.includes(x.id)} onValueChange={v=>setSelected(v?[...selected,x.id]:selected.filter(s=>s!==x.id))}/></View></Card>)}<Text style={styles.section}>Your page order</Text>{selected.map((id,i)=><Card key={id}><Text style={styles.body}>Page {i+1} · {assets.find(x=>x.id===id)?.filename}</Text><Button title="Move one page earlier" secondary disabled={i===0} onPress={()=>{const next=[...selected];[next[i-1],next[i]]=[next[i]!,next[i-1]!];setSelected(next);}}/></Card>)}<Field label="Recipient name" value={name} onChangeText={setName}/><Field label="Delivery address" value={address} onChangeText={setAddress} multiline/><Field label="PIN code" value={postcode} onChangeText={setPostcode} keyboardType="number-pad"/><Field label="Phone (+91)" value={phone} onChangeText={setPhone}/><ErrorNotice message={a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}<Button title="Save album order" disabled={selected.length<10} busy={a.busy} onPress={()=>void a.run(async()=>{await api('/prints',{galleryId:route.params.gallery.id,configuration:{size,paper,cover,copies:Number(copies),pages:selected.map(assetId=>({assetId}))},address:{name,line:address,city:'Chennai',postcode,phone}});a.setSuccess('Album draft saved for proof preparation. Review your album orders in your profile.');})}/></Page>;}
