import React,{useEffect,useState} from 'react';
import {Linking,Switch,Text,View} from 'react-native';
import {useNavigation,type NavigationProp,type StaticScreenProps} from '@react-navigation/native';
import * as Location from 'expo-location';
import * as Crypto from 'expo-crypto';
import {formatMoney} from '@kamraw/domain';
import {Button,Card,Empty,ErrorNotice,Field,Page,styles} from '../components/ui';
import {useSession} from '../services/session';
import {useAction,useLoad} from '../services/use-load';
import {enqueue,flushQueue} from '../services/offline';
import {CreatorCancellation,CancellationHistory} from '../components/recovery';
import {SessionChat,Availability} from '../components/communication';
import {SessionChanges} from '../components/session-tools';
import {ApiError} from '../services/api';
import type {Offer,Job,Routes} from '../services/types';
export function OffersScreen(){const {api}=useSession(),offers=useLoad<Offer[]>('/creator/offers'),profile=useLoad<{online:boolean;status:string;name:string}>('/creator'),a=useAction();useEffect(()=>{const timer=setInterval(()=>void offers.refresh(),15000);return ()=>clearInterval(timer);},[]);return <Page><Text style={styles.eyebrow}>CREATOR WORKSPACE</Text><Text style={styles.title}>A good day\nfor good work.</Text><Card><View style={styles.row}><View style={{flex:1}}><Text style={styles.section}>{profile.data?.online?'You’re online':'Take your time'}</Text><Text style={styles.subtitle}>Available for on-demand shoots</Text></View><Switch accessibilityLabel="Available for on-demand shoots" value={profile.data?.online??false} onValueChange={online=>void a.run(async()=>{await api('/creator/online',{online},'PUT');await profile.refresh();})}/></View></Card><ErrorNotice message={offers.error??profile.error??a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}{offers.data?.map(o=><Card key={o.id}><Text style={styles.eyebrow}>{o.tier} · {o.discipline}</Text><Text style={[styles.section,{textTransform:'capitalize'}]}>{o.category}</Text><Text style={styles.subtitle}>{new Date(o.start_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · {o.zone_id}</Text><Text style={styles.title}>{formatMoney(o.earning_paise)}</Text><Text style={styles.label}>Your fixed earnings · expires {new Date(o.expires_at).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'})}</Text><Button title="Accept this shoot" busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/creator/offers/${o.id}/accept`,{});await offers.refresh();a.setSuccess('Shoot accepted. Find the full brief in My shoots.');})}/><Button title="Decline offer" secondary busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/creator/offers/${o.id}/decline`,{});await offers.refresh();})}/></Card>)}{!offers.data?.length&&<Empty title="Ready for your next good shoot." body="Matching offers will appear here. Keep your availability up to date."/>}<Availability/><Button title="Refresh offers" secondary onPress={()=>void offers.refresh()}/></Page>;}
export function JobsScreen(){const load=useLoad<Job[]>('/creator/jobs'),nav=useNavigation<NavigationProp<Routes>>();return <Page><Text style={styles.title}>My shoots</Text><ErrorNotice message={load.error}/>{load.data?.map(j=><Card key={j.role_id}><Text style={styles.eyebrow}>{j.code} · {j.status.replaceAll('_',' ')}</Text><Text style={styles.section}>{new Date(j.start_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</Text><Text style={styles.subtitle}>{j.input.venue.address}</Text><Button title="Open shoot brief" secondary onPress={()=>nav.navigate('Job',{job:j})}/></Card>)}{!load.data?.length&&<Empty title="Your next chapter is on its way." body="Accepted shoots, briefs and session tools appear here."/>}<Button title="Refresh shoots" secondary onPress={()=>void load.refresh()}/></Page>;}
export function JobScreen({route}:StaticScreenProps<{job:Job}>){const nav=useNavigation<NavigationProp<Routes>>(),job=route.params.job,{api,user,demo}=useSession(),a=useAction(),[code,setCode]=useState(''),[status,setStatus]=useState(job.status);const actions:Record<string,[string,string]>={assigned:['trip','Start trip'],reconfirmed:['trip','Start trip'],en_route:['check_in','Verify arrival'],arrived:['start','Start session'],in_session:['complete','Complete session']};const next=actions[status];async function location(){if(demo)return {...job.input.venue,accuracy:5};const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted')throw new Error('Location access is needed to verify arrival.');const p=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});return {lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy??100};}
 useEffect(()=>{if(status!=='en_route')return;const timer=setInterval(()=>{void location().then(p=>api(`/sessions/${job.id}/location`,p)).catch(()=>{});},10000);return ()=>clearInterval(timer);},[status]);
 const send=()=>a.run(async()=>{if(!next)return;const clientId=Crypto.randomUUID(),body={clientId,action:next[0],deviceAt:new Date().toISOString(),location:await location(),completionCode:next[0]==='complete'?code:undefined,identityProof:demo&&next[0]==='check_in'?'demo-selfie':undefined};try{const r=await api<{status:string}>(`/creator/roles/${job.role_id}/events`,body);setStatus(r.status);a.setSuccess('Session updated.');}catch(e){if(e instanceof ApiError&&e.status===0){await enqueue({id:clientId,path:`/creator/roles/${job.role_id}/events`,body,accountId:user!.id});a.setSuccess('Saved on this device. Sync when you reconnect.');}else throw e;}});
 return <Page><Text style={styles.eyebrow}>{job.code} · {job.tier}</Text><Text style={styles.title}>{status.replaceAll('_',' ')}</Text><Card><Text style={styles.section}>{job.input.venue.address}</Text><Text style={styles.subtitle}>{job.input.venue.notes||'No extra venue notes'}</Text><Text style={styles.body}>{job.input.hours} hours · {job.discipline} · {job.input.style}</Text><Text style={styles.subtitle}>{job.input.notes||'Follow the standard event shot list.'}</Text></Card><Button title="Open navigation" secondary onPress={()=>void Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${job.input.venue.lat},${job.input.venue.lng}`)}/>{demo&&<Text style={styles.label}>Demo arrival uses the sample venue and a simulated identity check.</Text>}{status==='in_session'&&<Field label="Customer completion code" value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6}/>}<ErrorNotice message={a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}{next&&<Button title={next[1]} busy={a.busy} onPress={()=>void send()}/>}{!['cancelled','refunded'].includes(status)&&<SessionChat sessionId={job.id}/>} {status==='in_session'&&<SessionChanges sessionId={job.id} status={status} creator/>}{['session_completed','media_verified','editing','preview_delivered'].includes(status)&&<Button title="Upload original captures or edits" onPress={()=>nav.navigate('Upload',{sessionId:job.id})}/>}{['assigned','reconfirmed','en_route'].includes(status)&&<CreatorCancellation roleId={job.role_id} onCancelled={()=>{setStatus('cancelled');a.setSuccess('Cancellation recorded. Replacement matching has started.');}}/>}<Button title="Sync saved events" secondary onPress={()=>void a.run(async()=>{const pending=await flushQueue(user!.id,(p,b)=>api(p,b));a.setSuccess(pending.length?`${pending.length} event(s) still need attention.`:'All saved events synced.');})}/><Button title="SOS · Alert operations" secondary onPress={()=>void a.run(async()=>{await api(`/sessions/${job.id}/incidents`,{kind:'sos',location:await location(),notes:'Creator needs help'});a.setSuccess('SOS sent. Call 112 for an immediate emergency.');})}/><Button title="Call 112" secondary onPress={()=>void Linking.openURL('tel:112')}/></Page>;}
export function EarningsScreen(){const load=useLoad<{jobs:{id:string;code:string;earning_paise:number;status:string}[];payouts:{id:string;amount_paise:number;status:string}[]}>('/creator/earnings');return <Page><Text style={styles.eyebrow}>YOUR WORK, VALUED</Text><Text style={styles.title}>Earnings</Text><Card><Text style={styles.label}>Booked earnings</Text><Text style={styles.title}>{formatMoney(load.data?.jobs.reduce((t,j)=>t+j.earning_paise,0)??0)}</Text><Text style={styles.subtitle}>Weekly payouts follow session completion and verified uploads. Video retains 20% until final QC.</Text></Card><ErrorNotice message={load.error}/>{load.data?.jobs.map(j=><Card key={j.id}><View style={styles.row}><Text style={styles.body}>{j.code}</Text><Text style={styles.section}>{formatMoney(j.earning_paise)}</Text></View><Text style={styles.subtitle}>{j.status.replaceAll('_',' ')}</Text></Card>)}<CancellationHistory/><Button title="Refresh earnings" secondary onPress={()=>void load.refresh()}/></Page>;}
