import {EntitySchema} from 'typeorm';
import type {BookingInput, Price, RateCard, SessionInput, Status, Tier, Discipline, Zone} from '@kamraw/domain';
export interface Account {id:string;subject:string;name:string;language:string;role:string;consents:Record<string,boolean>;createdAt:Date}
export interface Configuration {id:string;kind:string;version:number;value:RateCard|Zone[]|Record<string,unknown>;status:string;createdBy:string;approvedBy:string|null;createdAt:Date}
export interface Quote {id:string;customerId:string;input:BookingInput;price:Price;expiresAt:Date;orderId:string|null;createdAt:Date}
export interface Order {id:string;code:string;customerId:string;quoteId:string;status:string;category:string;totalPaise:number;creditPaise:number;currency:string;createdAt:Date}
export interface Session {id:string;orderId:string;input:SessionInput;status:Status;startAt:Date;endAt:Date;zoneId:string;totalPaise:number;creditPaise:number;completionCode:string;startedAt:Date|null;completedAt:Date|null;createdAt:Date}
export interface Role {id:string;sessionId:string;discipline:Discipline;tier:Tier;creatorId:string|null;status:Status;earningPaise:number;lead:boolean;reservedStart:Date;reservedEnd:Date}
export interface Creator {id:string;accountId:string;name:string;status:string;online:boolean;disciplines:Partial<Record<Discipline,Tier>>;zoneIds:string[];languages:string[];profile:Record<string,unknown>;checks:Record<string,boolean>;metrics:Record<string,number>;createdAt:Date}
export interface Offer {id:string;roleId:string;creatorId:string;status:string;score:number;earningPaise:number;expiresAt:Date;createdAt:Date}
const uuid={type:'uuid' as const,primary:true,generated:'uuid' as const};
const created={type:'timestamptz' as const,createDate:true,name:'created_at'};
export const AccountEntity=new EntitySchema<Account>({name:'Account',tableName:'accounts',columns:{id:uuid,subject:{type:String,unique:true},name:{type:String},language:{type:String},role:{type:String},consents:{type:'jsonb'},createdAt:created}});
export const ConfigEntity=new EntitySchema<Configuration>({name:'Configuration',tableName:'configurations',columns:{id:uuid,kind:{type:String},version:{type:Number},value:{type:'jsonb'},status:{type:String},createdBy:{type:'uuid',name:'created_by'},approvedBy:{type:'uuid',name:'approved_by',nullable:true},createdAt:created}});
export const QuoteEntity=new EntitySchema<Quote>({name:'Quote',tableName:'quotes',columns:{id:uuid,customerId:{type:'uuid',name:'customer_id'},input:{type:'jsonb'},price:{type:'jsonb'},expiresAt:{type:'timestamptz',name:'expires_at'},orderId:{type:'uuid',name:'order_id',nullable:true},createdAt:created}});
export const OrderEntity=new EntitySchema<Order>({name:'Order',tableName:'orders',columns:{id:uuid,code:{type:String,unique:true},customerId:{type:'uuid',name:'customer_id'},quoteId:{type:'uuid',name:'quote_id',unique:true},status:{type:String},category:{type:String},totalPaise:{type:Number,name:'total_paise'},creditPaise:{type:Number,name:'credit_paise',default:0},currency:{type:String},createdAt:created}});
export const SessionEntity=new EntitySchema<Session>({name:'Session',tableName:'sessions',columns:{id:uuid,orderId:{type:'uuid',name:'order_id'},input:{type:'jsonb'},status:{type:String},startAt:{type:'timestamptz',name:'start_at'},endAt:{type:'timestamptz',name:'end_at'},zoneId:{type:String,name:'zone_id'},totalPaise:{type:Number,name:'total_paise'},creditPaise:{type:Number,name:'credit_paise',default:0},completionCode:{type:String,name:'completion_code',select:false},startedAt:{type:'timestamptz',name:'started_at',nullable:true},completedAt:{type:'timestamptz',name:'completed_at',nullable:true},createdAt:created}});
export const RoleEntity=new EntitySchema<Role>({name:'Role',tableName:'roles',columns:{id:uuid,sessionId:{type:'uuid',name:'session_id'},discipline:{type:String},tier:{type:String},creatorId:{type:'uuid',name:'creator_id',nullable:true},status:{type:String},earningPaise:{type:Number,name:'earning_paise'},lead:{type:Boolean},reservedStart:{type:'timestamptz',name:'reserved_start'},reservedEnd:{type:'timestamptz',name:'reserved_end'}}});
export const CreatorEntity=new EntitySchema<Creator>({name:'Creator',tableName:'creators',columns:{id:uuid,accountId:{type:'uuid',unique:true,name:'account_id'},name:{type:String},status:{type:String},online:{type:Boolean},disciplines:{type:'jsonb'},zoneIds:{type:'jsonb',name:'zone_ids'},languages:{type:'jsonb'},profile:{type:'jsonb'},checks:{type:'jsonb'},metrics:{type:'jsonb'},createdAt:created}});
export const OfferEntity=new EntitySchema<Offer>({name:'Offer',tableName:'offers',columns:{id:uuid,roleId:{type:'uuid',name:'role_id'},creatorId:{type:'uuid',name:'creator_id'},status:{type:String},score:{type:'double precision'},earningPaise:{type:Number,name:'earning_paise'},expiresAt:{type:'timestamptz',name:'expires_at'},createdAt:created}});
export const entities=[AccountEntity,ConfigEntity,QuoteEntity,OrderEntity,SessionEntity,RoleEntity,CreatorEntity,OfferEntity];
