import {z} from 'zod';
import {PlatformRepository} from '../repositories/platform';
import {AppError} from '../middleware/errors';
import {AccountEntity,CreatorEntity} from '../entities';
export class AccountService {
  constructor(private repo:PlatformRepository){}
  async profile(id:string,body:unknown){const x=z.object({name:z.string().trim().min(2).max(80),language:z.enum(['en','ta']),consents:z.object({marketing:z.boolean(),portfolio:z.boolean(),guardian:z.boolean()})}).parse(body);await this.repo.db.transaction(async m=>{await m.getRepository(AccountEntity).update(id,x);await this.repo.audit(m,id,'profile_consent_updated',id,{consents:x.consents});});return this.repo.account(id);}
  async privacy(id:string,body:unknown){const x=z.object({kind:z.enum(['export','delete'])}).parse(body);const [row]=await this.repo.db.query('INSERT INTO privacy_requests(account_id,kind) VALUES($1,$2) RETURNING *',[id,x.kind]);return row;}
  async onboard(id:string,body:unknown){const x=z.object({name:z.string().min(2).max(100),languages:z.array(z.enum(['ta','en','hi'])).min(1),disciplines:z.object({photo:z.enum(['T1','T2']).optional(),video:z.enum(['T2','T3']).optional()}),profile:z.object({bio:z.string().max(2000),experience:z.number().int().min(0).max(70),gear:z.array(z.object({type:z.string().max(50),model:z.string().max(100),serial:z.string().max(100),ownership:z.enum(['owned','rented'])})).max(30),portfolioUrls:z.array(z.string().url()).max(100),emergencyContact:z.string().regex(/^\+91[6-9]\d{9}$/),agreementAccepted:z.boolean(),backgroundConsent:z.boolean()})}).parse(body);const existing=await this.repo.db.getRepository(CreatorEntity).findOneBy({accountId:id});if(existing&&existing.status==='active')throw new AppError(409,'ALREADY_ACTIVE','Contact operations to change verified credentials');return this.repo.db.getRepository(CreatorEntity).save({...existing,...x,profile:{...x.profile,...(existing?.profile.photoDataUrl?{photoDataUrl:existing.profile.photoDataUrl}:{})},accountId:id,status:'applied',zoneIds:existing?.zoneIds??[],checks:existing?.checks??{},metrics:existing?.metrics??{},online:false});}
  async online(id:string,online:boolean){const c=await this.repo.creator(id);if(c.status!=='active')throw new AppError(403,'NOT_ACTIVE','Finish verification before going online');await this.repo.db.getRepository(CreatorEntity).update(c.id,{online});return {online};}
  async availability(id:string,body:unknown){const c=await this.repo.creator(id);const x=z.object({start:z.iso.datetime({offset:true}),end:z.iso.datetime({offset:true}),available:z.boolean()}).refine(x=>new Date(x.end)>new Date(x.start)&&new Date(x.end).getTime()<Date.now()+180*86400000).parse(body);const [a]=await this.repo.db.query('INSERT INTO availability(creator_id,start_at,end_at,available) VALUES($1,$2,$3,$4) RETURNING *',[c.id,x.start,x.end,x.available]);return a;}
  async ticket(id:string,body:unknown){const x=z.object({orderId:z.uuid().optional(),category:z.enum(['booking','payment','quality','print','account','other']),subject:z.string().trim().min(5).max(150),body:z.string().trim().min(10).max(5000)}).parse(body);if(x.orderId)await this.repo.ownedOrder(x.orderId,id);const [t]=await this.repo.db.query('INSERT INTO tickets(account_id,order_id,category,subject,body,due_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[id,x.orderId??null,x.category,x.subject,x.body,new Date(Date.now()+2*3600000)]);return t;}
  async message(id:string,sessionId:string,body:unknown){const {session}=await this.repo.authorizedSession(sessionId,id);if(['confirmed','cancelled','refunded'].includes(session.status)||session.completedAt&&Date.now()-session.completedAt.getTime()>86400000)throw new AppError(409,'CHAT_CLOSED','Chat is available from assignment until 24 hours after the session');const x=z.object({body:z.string().trim().min(1).max(2000)}).parse(body);if(/(?:\+?91[ -]?)?[6-9](?:[ -]?\d){9}|[\w.+-]+@[\w.-]+\.[a-z]{2,}/i.test(x.body))throw new AppError(422,'CONTACT_DETAILS','Keep contact details private. Use Kamraw chat and masked calls.');const [r]=await this.repo.db.query('INSERT INTO messages(session_id,actor_id,body) VALUES($1,$2,$3) RETURNING *',[sessionId,id,x.body]);return r;}
  async prints(id:string,body:unknown){const x=z.object({galleryId:z.uuid(),configuration:z.object({size:z.enum(['8x8','10x10','12x12']),paper:z.enum(['matte','gloss']),cover:z.enum(['linen','hard']),pages:z.array(z.object({assetId:z.uuid(),crop:z.object({x:z.number().min(0).max(1),y:z.number().min(0).max(1)}).optional()})).min(10).max(80),copies:z.number().int().min(1).max(10)}),address:z.object({name:z.string().min(2),line:z.string().min(10),city:z.string().min(2),postcode:z.string().regex(/^\d{6}$/),phone:z.string().regex(/^\+91[6-9]\d{9}$/)})}).parse(body);const [g]=await this.repo.db.query('SELECT g.id FROM galleries g JOIN orders o ON o.id=g.order_id WHERE g.id=$1 AND o.customer_id=$2',[x.galleryId,id]);if(!g)throw new AppError(404,'NOT_FOUND','Gallery not found');for(const p of x.configuration.pages){const [a]=await this.repo.db.query("SELECT width,height FROM media_assets WHERE id=$1 AND gallery_id=$2 AND kind='edited' AND qc_status='approved'",[p.assetId,x.galleryId]);const inches=Number(x.configuration.size.split('x')[0]);if(!a||a.width<inches*300||a.height<inches*300)throw new AppError(422,'PRINT_RESOLUTION','An image is below 300 DPI for the selected page size');}const [row]=await this.repo.db.query('INSERT INTO print_orders(customer_id,gallery_id,configuration,address) VALUES($1,$2,$3,$4) RETURNING *',[id,x.galleryId,JSON.stringify(x.configuration),JSON.stringify(x.address)]);return row;}
}
