import {createHash,createHmac,randomBytes,scryptSync,timingSafeEqual} from 'node:crypto';
import {mkdir,open,copyFile,readFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {z} from 'zod';
import {safeToFormat} from '@kamraw/domain';
import {PlatformRepository} from '../repositories/platform';
import {AppError,requireValue} from '../middleware/errors';
import {previewPhoto,isPhoto} from './image-processing';
import {permissions} from '../middleware/auth';
import {RoleEntity,SessionEntity} from '../entities';
interface Asset {id:string;upload_id:string;filename:string;bytes:string;checksum:string;verified_checksum:string|null;copies:number;status:string;storage_key:string;received_bytes:string;gallery_id:string;kind:string;qc_status:string}
const digest=(v:string|Buffer)=>createHash('sha256').update(v).digest('hex');
const ticketKey=randomBytes(32);
type MediaTicket={asset:string;gallery:string;share?:string;owner?:string;download:boolean;staff?:string;exp:number};
function issueTicket(data:Omit<MediaTicket,'exp'>){const body=Buffer.from(JSON.stringify({...data,exp:Date.now()+300000})).toString('base64url');return `${body}.${createHmac('sha256',ticketKey).update(body).digest('base64url')}`;}
const manifestSchema=z.object({sessionId:z.uuid(),files:z.array(z.object({filename:z.string().min(1).max(200).regex(/^[^/\\]+\.(?:cr3|nef|arw|raf|dng|png|webp|jpe?g|heif|heic|mp4|mov|wav)$/i),bytes:z.number().int().positive().max(150*1024**3),checksum:z.string().regex(/^[a-f0-9]{64}$/),kind:z.enum(['original','edited']).default('original')})).min(1).max(10000)});
export class MediaService {
  constructor(private repo:PlatformRepository,private root:string,private demo:boolean){}
  async manifest(accountId:string,body:unknown){const input=manifestSchema.parse(body),c=await this.repo.creator(accountId);const role=await this.repo.db.getRepository(RoleEntity).createQueryBuilder('r').where('r.sessionId=:sessionId AND r.creatorId=:creatorId',{sessionId:input.sessionId,creatorId:c.id}).andWhere("r.status NOT IN ('cancelled','refunded')").getOne();if(!role)throw new AppError(404,'NOT_FOUND','Session not found');
    if(!['session_completed','media_verified','editing','preview_delivered'].includes(role.status))throw new AppError(409,'SESSION_INCOMPLETE','Complete the session before uploading');
    if(!this.demo)throw new AppError(503,'STORAGE_REQUIRED','Production object storage is not configured');
    const bytes=input.files.reduce((s,f)=>s+f.bytes,0);if(bytes>50*1024**2)throw new AppError(422,'DEMO_LIMIT','Demo uploads are limited to 50 MB per card');
    if(new Set(input.files.map(f=>f.filename)).size!==input.files.length)throw new AppError(422,'DUPLICATE_FILE','Each filename must be unique within a card');
    return this.repo.db.transaction(async m=>{const session=await this.repo.session(input.sessionId,m);const [gallery]=await m.query('SELECT id FROM galleries WHERE order_id=$1',[session.orderId]) as {id:string}[];const [upload]=await m.query('INSERT INTO uploads(session_id,creator_id,expected_count,expected_bytes) VALUES($1,$2,$3,$4) RETURNING *',[session.id,c.id,input.files.length,bytes]);const assets=[];
      for(const f of input.files){const key=randomBytes(20).toString('hex');const [asset]=await m.query('INSERT INTO media_assets(upload_id,gallery_id,filename,bytes,checksum,storage_key,kind) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,filename,bytes,received_bytes,status',[upload.id,gallery!.id,f.filename,f.bytes,f.checksum,key,f.kind]);assets.push(asset);}return {...upload,assets};});
  }
  async ownedAsset(accountId:string,assetId:string){const c=await this.repo.creator(accountId);const [asset]=await this.repo.db.query('SELECT a.* FROM media_assets a JOIN uploads u ON u.id=a.upload_id WHERE a.id=$1 AND u.creator_id=$2',[assetId,c.id]) as Asset[];return requireValue(asset);}
  async chunk(accountId:string,assetId:string,offset:number,bytes:Buffer){await this.ownedAsset(accountId,assetId);if(!Buffer.isBuffer(bytes)||!bytes.length||bytes.length>8*1024**2)throw new AppError(422,'INVALID_CHUNK','Choose a chunk between 1 byte and 8 MB');
    return this.repo.db.transaction(async m=>{const [asset]=await m.query('SELECT * FROM media_assets WHERE id=$1 FOR UPDATE',[assetId]) as Asset[];const a=requireValue(asset);if(a.status==='discarded')throw new AppError(409,'DISCARDED','This upload was discarded');if(offset!==Number(a.received_bytes))throw new AppError(409,'OFFSET_MISMATCH',`Resume at byte ${a.received_bytes}`);if(offset+bytes.length>Number(a.bytes)||a.status==='verified')throw new AppError(422,'INVALID_SIZE','Chunk exceeds the declared file size');
      await mkdir(path.join(this.root,'primary'),{recursive:true});const filename=path.join(this.root,'primary',a.storage_key);const file=await open(filename,offset===0?'w':'r+');try{await file.write(bytes,0,bytes.length,offset);await file.sync();}finally{await file.close();}const received=offset+bytes.length;
      let verified=false;let dimensions:{width:number;height:number}|undefined;if(received===Number(a.bytes)){const content=await readFile(filename);if(digest(content)!==a.checksum){await m.query("UPDATE media_assets SET received_bytes=0,status='checksum_failed' WHERE id=$1",[assetId]);return {receivedBytes:0,status:'checksum_failed'};}await mkdir(path.join(this.root,'backup'),{recursive:true});const backup=path.join(this.root,'backup',a.storage_key);await copyFile(filename,backup);if(digest(await readFile(backup))!==a.checksum)throw new AppError(500,'BACKUP_FAILED','Backup verification failed');if(a.kind==='edited'&&isPhoto(a.filename))dimensions=await previewPhoto(this.root,a.storage_key);verified=true;}
      if(dimensions)await m.query('UPDATE media_assets SET width=$2,height=$3 WHERE id=$1',[assetId,dimensions.width,dimensions.height]);await m.query('UPDATE media_assets SET received_bytes=$2,status=$3,verified_checksum=$4,copies=$5 WHERE id=$1',[assetId,received,verified?'verified':'uploading',verified?a.checksum:null,verified?2:0]);return {receivedBytes:received,status:verified?'verified':'uploading'};});
  }
  async receipt(accountId:string,uploadId:string){const c=await this.repo.creator(accountId);return this.repo.db.transaction(async m=>{const [upload]=await m.query('SELECT * FROM uploads WHERE id=$1 AND creator_id=$2 FOR UPDATE',[uploadId,c.id]);if(!upload)throw new AppError(404,'NOT_FOUND','Upload not found');if(upload.status==='verified'&&upload.receipt)return upload.receipt;if(upload.status==='cancelled')throw new AppError(409,'DISCARDED','This upload was discarded');const assets=await m.query('SELECT * FROM media_assets WHERE upload_id=$1',[uploadId]) as Asset[];const safe=safeToFormat(assets.map(a=>({bytes:Number(a.bytes),checksum:a.checksum,verifiedChecksum:a.verified_checksum,copies:a.copies,status:a.status})),upload.expected_count,Number(upload.expected_bytes));
      const receipt={safeToFormat:safe&&!this.demo,demoVerified:safe&&this.demo,files:assets.length,bytes:Number(upload.expected_bytes),verifiedAt:safe?new Date().toISOString():null,message:this.demo?'Demo verification uses two copies on one machine. Keep your original card.':safe?'All originals verified in redundant storage.':'Keep your original card until every file is verified.'};
      if(safe){await m.query("UPDATE uploads SET status='verified',receipt=$2 WHERE id=$1",[uploadId,JSON.stringify(receipt)]);await m.query("UPDATE roles SET status='media_verified' WHERE session_id=$1 AND creator_id=$2 AND status IN ('session_completed','media_verified','editing','preview_delivered')",[upload.session_id,c.id]);const remaining=await m.query("SELECT 1 FROM roles WHERE session_id=$1 AND status NOT IN ('media_verified','editing','preview_delivered','final_delivered','cancelled','refunded')",[upload.session_id]);if(!remaining.length)await m.getRepository(SessionEntity).update(upload.session_id,{status:'media_verified'});await this.repo.event(m,'upload_verified',uploadId);}return receipt;});}
  async abandon(accountId:string,uploadId:string){const creator=await this.repo.creator(accountId);return this.repo.db.transaction(async m=>{const [u]=await m.query('SELECT id,status FROM uploads WHERE id=$1 AND creator_id=$2 FOR UPDATE',[uploadId,creator.id]);if(!u)throw new AppError(404,'NOT_FOUND','Upload not found');if(u.status==='verified')throw new AppError(409,'ALREADY_VERIFIED','Contact operations to change a verified card');await m.query("UPDATE uploads SET status='cancelled' WHERE id=$1",[uploadId]);await m.query("UPDATE media_assets SET status='discarded' WHERE upload_id=$1",[uploadId]);await this.repo.audit(m,accountId,'upload_discarded',uploadId);return {discarded:true};});}
  async gallery(accountId:string,galleryId:string){const [gallery]=await this.repo.db.query('SELECT g.* FROM galleries g JOIN orders o ON o.id=g.order_id WHERE g.id=$1 AND o.customer_id=$2',[galleryId,accountId]);if(!gallery)throw new AppError(404,'NOT_FOUND','Gallery not found');const assets=await this.repo.db.query("SELECT id,filename,bytes,kind,width,height FROM media_assets WHERE gallery_id=$1 AND qc_status='approved' AND kind='edited' AND status='verified'",[galleryId]);return {...gallery,assets};}
  async share(accountId:string,galleryId:string,body:unknown){await this.gallery(accountId,galleryId);const x=z.object({kind:z.enum(['public','pin','invite']),pin:z.string().regex(/^\d{6}$/).optional(),expiresAt:z.iso.datetime({offset:true}),allowDownload:z.boolean(),invites:z.array(z.string().min(5).max(200)).max(100).default([])}).parse(body);if(new Date(x.expiresAt)<=new Date()||new Date(x.expiresAt).getTime()>Date.now()+365*86400000)throw new AppError(422,'EXPIRY','Choose an expiry within one year');if(x.kind==='pin'&&!x.pin)throw new AppError(422,'PIN_REQUIRED','Choose a six-digit PIN');if(x.kind==='invite'&&!x.invites.length)throw new AppError(422,'INVITES_REQUIRED','Add at least one verified account ID');const token=randomBytes(32).toString('base64url'),salt=randomBytes(16).toString('hex');const pinHash=x.pin?`${salt}:${scryptSync(x.pin,salt,32).toString('hex')}`:null;const [share]=await this.repo.db.query('INSERT INTO shares(gallery_id,token_hash,kind,pin_hash,invites,expires_at,allow_download) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,kind,expires_at,allow_download',[galleryId,digest(token),x.kind,pinHash,JSON.stringify(x.invites),x.expiresAt,x.allowDownload]);return {...share,token};}
  async shared(token:string,pin?:string,accountId?:string){const [s]=await this.repo.db.query('SELECT s.*,g.status AS gallery_status,g.expires_at AS gallery_expiry FROM shares s JOIN galleries g ON g.id=s.gallery_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now()',[digest(token)]);if(!s||!['preview_ready','final_ready'].includes(s.gallery_status)||s.gallery_expiry&&new Date(s.gallery_expiry)<=new Date())throw new AppError(404,'NOT_FOUND','This gallery link is unavailable or has expired');if(s.kind==='pin'){const [salt,hash]=s.pin_hash.split(':');if(!pin||!/^\d{6}$/.test(pin)||!timingSafeEqual(scryptSync(pin,salt,32),Buffer.from(hash,'hex')))throw new AppError(401,'PIN_REQUIRED','Enter the six-digit gallery PIN');}if(s.kind==='invite'&&(!accountId||!s.invites.includes(accountId)))throw new AppError(401,'INVITE_REQUIRED','Sign in with an invited account');const assets=await this.repo.db.query("SELECT id,filename,bytes,width,height FROM media_assets WHERE gallery_id=$1 AND status='verified' AND qc_status='approved' AND kind='edited'",[s.gallery_id]);return {id:s.gallery_id,status:s.gallery_status,allowDownload:s.allow_download,assets};}
  async reviewTicket(staff:string,assetId:string){const {asset}=await this.file(assetId,true);return {ticket:issueTicket({asset:assetId,gallery:asset.gallery_id,staff,download:true})};}
  async ownerTicket(accountId:string,assetId:string){const {asset}=await this.file(assetId);await this.gallery(accountId,asset.gallery_id);return {ticket:issueTicket({asset:assetId,gallery:asset.gallery_id,owner:accountId,download:true})};}
  async sharedTickets(token:string,pin?:string,accountId?:string){const shared=await this.shared(token,pin,accountId);const [share]=await this.repo.db.query('SELECT id FROM shares WHERE token_hash=$1',[digest(token)]);return {...shared,assets:shared.assets.map((asset:{id:string})=>({...asset,ticket:issueTicket({asset:asset.id,gallery:shared.id,share:share.id,download:shared.allowDownload})}))};}
  async authorizedFile(assetId:string,ticket:string,download:boolean){const [body,signature]=ticket.split('.');if(!body||!signature)throw new AppError(401,'INVALID_TICKET','Refresh the gallery to view this file');const expected=createHmac('sha256',ticketKey).update(body).digest();const actual=Buffer.from(signature,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))throw new AppError(401,'INVALID_TICKET','Refresh the gallery to view this file');let data:MediaTicket;try{data=JSON.parse(Buffer.from(body,'base64url').toString());}catch{throw new AppError(401,'INVALID_TICKET','Invalid file ticket');}if(data.asset!==assetId||data.exp<Date.now()||download&&!data.download)throw new AppError(403,'EXPIRED_TICKET','Refresh the gallery or ask the owner for download permission');if(data.staff){const staff=await this.repo.account(data.staff);if(!permissions[staff.role]?.includes('qc'))throw new AppError(403,'FORBIDDEN','QC access no longer available');return this.file(assetId,true);}if(data.share){const [share]=await this.repo.db.query('SELECT id FROM shares WHERE id=$1 AND gallery_id=$2 AND revoked_at IS NULL AND expires_at>now()',[data.share,data.gallery]);if(!share)throw new AppError(404,'NOT_FOUND','This gallery link is no longer available');}else if(data.owner)await this.gallery(data.owner,data.gallery);else throw new AppError(401,'INVALID_TICKET','Invalid file ticket');return this.file(assetId);}
  async file(assetId:string,review=false){const [a]=await this.repo.db.query("SELECT a.*,g.status AS gallery_status FROM media_assets a JOIN galleries g ON g.id=a.gallery_id WHERE a.id=$1 AND a.status='verified' AND ($2 OR (a.qc_status='approved' AND a.kind='edited' AND g.status IN ('preview_ready','final_ready'))) AND (g.expires_at IS NULL OR g.expires_at>now())",[assetId,review]) as (Asset&{gallery_status:string})[];const asset=requireValue(a);const preview=!review&&asset.gallery_status==='preview_ready'&&isPhoto(asset.filename);const filename=path.resolve(this.root,preview?'preview':'primary',asset.storage_key+(preview?'.jpg':''));await stat(filename);return {asset:{...asset,filename:preview?asset.filename.replace(/\.[^.]+$/,'.jpg'):asset.filename},filename};}
}
