import type {EntityManager} from 'typeorm';
const titles:Record<string,string>={creator_cancelled:'We are finding a replacement creator',creator_suspension_review:'Creator reliability needs review',booking_confirmed:'Your shoot is booked',offer_sent:'A new shoot is waiting',creator_assigned:'Your creator is confirmed',session_trip:'Your creator is on the way',session_check_in:'Your creator has arrived',session_start:'Your shoot has started',session_complete:'Your shoot is complete',upload_verified:'Your upload has been verified',gallery_published:'Your gallery is ready',refund_requested:'Your refund is being processed',payout_requested:'Your payout was approved',extension_requested:'Extra time requested',extension_applied:'Your shoot has been extended',reschedule_applied:'Your shoot has been rescheduled',manual_dispatch_required:'A shoot needs matching help',sos:'An urgent safety alert needs attention'};
export async function notifyEvent(m:EntityManager,event:{id:string;kind:string;entity_id:string}){
 const title=titles[event.kind];if(!title)return;
 const sessions=await m.query(`SELECT DISTINCT s.id,s.order_id FROM sessions s WHERE s.id::text=$1 OR s.order_id::text=$1 OR s.id IN(SELECT session_id FROM roles WHERE id::text=$1 UNION SELECT r.session_id FROM offers o JOIN roles r ON r.id=o.role_id WHERE o.id::text=$1 UNION SELECT session_id FROM uploads WHERE id::text=$1 UNION SELECT session_id FROM incidents WHERE id::text=$1 UNION SELECT session_id FROM refunds WHERE id::text=$1) OR s.order_id IN(SELECT order_id FROM galleries WHERE id::text=$1)`,[event.entity_id]) as {id:string;order_id:string}[];
 const recipients=new Set<string>();
 if(event.kind==='offer_sent'){const rows=await m.query('SELECT c.account_id FROM offers o JOIN creators c ON c.id=o.creator_id WHERE o.id::text=$1',[event.entity_id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 else for(const session of sessions){const rows=await m.query("SELECT customer_id AS account_id FROM orders WHERE id=$1 UNION SELECT c.account_id FROM roles r JOIN creators c ON c.id=r.creator_id WHERE r.session_id=$2 AND r.status NOT IN ('cancelled','refunded')",[session.order_id,session.id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 if(event.kind==='payout_requested'){const rows=await m.query('SELECT DISTINCT c.account_id FROM payout_items p JOIN creators c ON c.id=p.creator_id WHERE p.run_id::text=$1',[event.entity_id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 if(['sos','manual_dispatch_required','creator_suspension_review'].includes(event.kind)){const rows=await m.query("SELECT id FROM accounts WHERE role IN ('super_admin','city_ops','dispatcher')");rows.forEach((r:{id:string})=>recipients.add(r.id));}
 for(const account of recipients)await m.query('INSERT INTO notifications(account_id,event_id,title,body,entity_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(account_id,event_id) DO NOTHING',[account,event.id,title,'Open the related shoot or gallery for details. Demo notifications stay inside Kamraw.',event.entity_id]);
}
