import type {EntityManager} from 'typeorm';
const titles:Record<string,string>={creator_quality_review:'Creator feedback needs review',assignment_overdue:'A booking is still waiting for assignment',assignment_choice:'Choose how to continue your unassigned booking',reconfirmation_due:'Please reconfirm your scheduled shoot',reconfirmation_overdue:'A creator has not reconfirmed',departure_due:'Departure needs attention',late_risk:'A creator has not checked in on time',session_ending:'Your shoot has 15 minutes left',upload_overdue:'Photo upload is overdue',gallery_expiry_30:'Your gallery expires within 30 days',gallery_expiry_7:'Your gallery expires within 7 days',gallery_expiry_1:'Your gallery expires within 24 hours',gallery_expired:'Your gallery retention period has ended',print_updated:'Your album order has an update',creator_cancelled:'We are finding a replacement creator',creator_suspension_review:'Creator reliability needs review',booking_confirmed:'Your shoot is booked',offer_sent:'A new shoot is waiting',creator_assigned:'Your creator is confirmed',session_trip:'Your creator is on the way',session_check_in:'Your creator has arrived',session_start:'Your shoot has started',session_complete:'Your shoot is complete',upload_verified:'Your upload has been verified',gallery_published:'Your gallery is ready',refund_requested:'Your refund is being processed',payout_requested:'Your payout was approved',extension_requested:'Extra time requested',extension_applied:'Your shoot has been extended',reschedule_applied:'Your shoot has been rescheduled',manual_dispatch_required:'A shoot needs matching help',sos:'An urgent safety alert needs attention'};
const tamil:Record<string,string>={creator_quality_review:'படைப்பாளர் பற்றிய கருத்துகளைப் பரிசீலிக்க வேண்டும்',assignment_overdue:'முன்பதிவிற்குப் படைப்பாளர் இன்னும் ஒதுக்கப்படவில்லை',assignment_choice:'படைப்பாளர் ஒதுக்கப்படாத முன்பதிவைத் தொடரும் முறையைத் தேர்ந்தெடுக்கவும்',reconfirmation_due:'திட்டமிட்ட படப்பிடிப்பை மீண்டும் உறுதிசெய்யவும்',reconfirmation_overdue:'படைப்பாளர் மீண்டும் உறுதிசெய்யவில்லை',departure_due:'புறப்படும் நேரத்திற்கு கவனம் தேவை',late_risk:'படைப்பாளரின் வருகை சரியான நேரத்தில் பதிவாகவில்லை',session_ending:'படப்பிடிப்பு முடிய இன்னும் 15 நிமிடங்கள்',upload_overdue:'புகைப்படப் பதிவேற்றம் தாமதமாகியுள்ளது',gallery_expiry_30:'உங்கள் படத்தொகுப்பு 30 நாட்களுக்குள் காலாவதியாகும்',gallery_expiry_7:'உங்கள் படத்தொகுப்பு 7 நாட்களுக்குள் காலாவதியாகும்',gallery_expiry_1:'உங்கள் படத்தொகுப்பு 24 மணிநேரத்திற்குள் காலாவதியாகும்',gallery_expired:'உங்கள் படத்தொகுப்பின் சேமிப்புக் காலம் முடிந்தது',print_updated:'உங்கள் ஆல்ப ஆர்டரில் புதிய தகவல் உள்ளது',creator_cancelled:'மாற்றுப் படைப்பாளரைத் தேடுகிறோம்',creator_suspension_review:'படைப்பாளரின் நம்பகத்தன்மையைப் பரிசீலிக்க வேண்டும்',booking_confirmed:'உங்கள் படப்பிடிப்பு முன்பதிவு செய்யப்பட்டது',offer_sent:'புதிய படப்பிடிப்பு வாய்ப்பு காத்திருக்கிறது',creator_assigned:'உங்கள் படைப்பாளர் உறுதிசெய்யப்பட்டார்',session_trip:'உங்கள் படைப்பாளர் வந்துகொண்டிருக்கிறார்',session_check_in:'உங்கள் படைப்பாளர் வந்துவிட்டார்',session_start:'உங்கள் படப்பிடிப்பு தொடங்கியது',session_complete:'உங்கள் படப்பிடிப்பு முடிந்தது',upload_verified:'உங்கள் பதிவேற்றம் சரிபார்க்கப்பட்டது',gallery_published:'உங்கள் படத்தொகுப்பு தயாராக உள்ளது',refund_requested:'பணம் திரும்ப வழங்கும் பணி நடைபெறுகிறது',payout_requested:'உங்கள் பணப்பட்டுவாடா ஒப்புதல் பெற்றது',extension_requested:'கூடுதல் நேரம் கோரப்பட்டுள்ளது',extension_applied:'உங்கள் படப்பிடிப்பு நேரம் நீட்டிக்கப்பட்டது',reschedule_applied:'உங்கள் படப்பிடிப்பின் தேதி மாற்றப்பட்டது',manual_dispatch_required:'படப்பிடிப்பிற்குப் படைப்பாளரை ஒதுக்க உதவி தேவை',sos:'அவசரப் பாதுகாப்பு எச்சரிக்கைக்கு கவனம் தேவை'};
Object.assign(titles,{late_arrival:'Your late-arrival credit and shooting time are ready',overrun_conflict:'A delayed shoot conflicts with another commitment',completion_requested:'Please confirm your shoot is complete',completion_disputed:'Session completion needs review',completion_reopened:'Your session completion request was reopened'});
Object.assign(tamil,{late_arrival:'தாமதமான வருகைக்கான கிரெடிட்டும் படப்பிடிப்பு நேரமும் புதுப்பிக்கப்பட்டன',overrun_conflict:'தாமதமான படப்பிடிப்பு மற்றொரு பணியுடன் மோதுகிறது',completion_requested:'உங்கள் படப்பிடிப்பு முடிந்ததை உறுதிசெய்யவும்',completion_disputed:'படப்பிடிப்பு நிறைவைப் பரிசீலிக்க வேண்டும்',completion_reopened:'படப்பிடிப்பு நிறைவுக் கோரிக்கை மீண்டும் திறக்கப்பட்டது'});
export async function notifyEvent(m:EntityManager,event:{id:string;kind:string;entity_id:string}){
 const title=titles[event.kind];if(!title)return;
 const sessions=await m.query(`SELECT DISTINCT s.id,s.order_id FROM sessions s WHERE s.id::text=$1 OR s.order_id::text=$1 OR s.id IN(SELECT session_id FROM roles WHERE id::text=$1 UNION SELECT r.session_id FROM offers o JOIN roles r ON r.id=o.role_id WHERE o.id::text=$1 UNION SELECT session_id FROM uploads WHERE id::text=$1 UNION SELECT session_id FROM incidents WHERE id::text=$1 UNION SELECT session_id FROM refunds WHERE id::text=$1) OR s.order_id IN(SELECT order_id FROM galleries WHERE id::text=$1)`,[event.entity_id]) as {id:string;order_id:string}[];
 const recipients=new Set<string>();
 if(event.kind==='offer_sent'){const rows=await m.query('SELECT c.account_id FROM offers o JOIN creators c ON c.id=o.creator_id WHERE o.id::text=$1',[event.entity_id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 else if(['reconfirmation_due','upload_overdue'].includes(event.kind)){const rows=await m.query('SELECT c.account_id FROM roles r JOIN creators c ON c.id=r.creator_id WHERE r.id::text=$1',[event.entity_id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 else if(!['assignment_overdue','reconfirmation_overdue','departure_due','manual_dispatch_required','creator_suspension_review','creator_quality_review','overrun_conflict','completion_disputed'].includes(event.kind))for(const session of sessions){const rows=await m.query("SELECT customer_id AS account_id FROM orders WHERE id=$1 UNION SELECT c.account_id FROM roles r JOIN creators c ON c.id=r.creator_id WHERE r.session_id=$2 AND r.status NOT IN ('cancelled','refunded')",[session.order_id,session.id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 if(event.kind==='print_updated'){const rows=await m.query('SELECT customer_id FROM print_orders WHERE id::text=$1',[event.entity_id]);rows.forEach((r:{customer_id:string})=>recipients.add(r.customer_id));}
 if(event.kind==='payout_requested'){const rows=await m.query('SELECT DISTINCT c.account_id FROM payout_items p JOIN creators c ON c.id=p.creator_id WHERE p.run_id::text=$1',[event.entity_id]);rows.forEach((r:{account_id:string})=>recipients.add(r.account_id));}
 if(['sos','manual_dispatch_required','creator_suspension_review','creator_quality_review','overrun_conflict','completion_disputed','assignment_overdue','reconfirmation_overdue','departure_due','late_risk','upload_overdue'].includes(event.kind)){const rows=await m.query("SELECT id FROM accounts WHERE role IN ('super_admin','city_ops','dispatcher')");rows.forEach((r:{id:string})=>recipients.add(r.id));}
 const accounts=recipients.size?await m.query('SELECT id,language FROM accounts WHERE id=ANY($1::uuid[]) AND disabled_at IS NULL',[[...recipients]]):[];
 for(const account of accounts){const ta=account.language==='ta';const body=event.kind==='assignment_choice'?(ta?'முன்பதிவைத் திறந்து காத்திருக்கவோ கட்டணமின்றி ரத்து செய்யவோ தேர்ந்தெடுக்கவும். தரம் அல்லது தேதியை மாற்ற ஆதரவுக் குழுவை அணுகவும்.':'Open your booking to keep waiting or cancel without a fee. Contact support to switch tier or date.'):ta?'விவரங்களுக்கு தொடர்புடைய படப்பிடிப்பு அல்லது படத்தொகுப்பைத் திறக்கவும். சோதனை அறிவிப்புகள் Kamraw செயலியில் மட்டுமே இருக்கும்.':'Open the related shoot or gallery for details. Demo notifications stay inside Kamraw.';await m.query('INSERT INTO notifications(account_id,event_id,title,body,entity_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(account_id,event_id) DO NOTHING',[account.id,event.id,ta?(tamil[event.kind]??title):title,body,event.entity_id]);}

}
