import {z} from 'zod';
import {PlatformRepository} from '../repositories/platform';
import {AppError,requireValue} from '../middleware/errors';
import {ConfigEntity,CreatorEntity,SessionEntity} from '../entities';
import type {RateCard,Zone} from '@kamraw/domain';
const reason=z.string().trim().min(5).max(1000);
export class OperationsService {
  constructor(private repo:PlatformRepository,private demo:boolean){}
  async dashboard(){const [stats]=await this.repo.db.query(`SELECT (SELECT count(*)::int FROM sessions WHERE status NOT IN ('closed','cancelled','refunded')) AS active_sessions,(SELECT count(*)::int FROM creators WHERE online AND status='active') AS online_creators,(SELECT count(*)::int FROM roles WHERE status='confirmed') AS open_roles,(SELECT count(*)::int FROM incidents WHERE status='open') AS incidents,(SELECT COALESCE(sum(amount_paise),0)::bigint::text FROM payment_events) AS collections_paise`);const bookings=await this.repo.db.query(`SELECT s.id,o.code,o.category,s.start_at,s.status,s.zone_id,(SELECT count(*)::int FROM roles r WHERE r.session_id=s.id AND r.creator_id IS NULL) AS open_roles FROM sessions s JOIN orders o ON o.id=s.order_id ORDER BY s.start_at DESC LIMIT 100`);const alerts=await this.repo.db.query(`SELECT id,kind,entity_id,created_at FROM outbox WHERE kind IN ('manual_dispatch_required','late_risk','upload_overdue','sos') ORDER BY created_at DESC LIMIT 50`);return {stats,bookings,alerts};}
  async creators(){return this.repo.db.getRepository(CreatorEntity).find({order:{createdAt:'DESC'},take:100});}
  async reviewCreator(actor:string,id:string,body:unknown){const x=z.object({status:z.enum(['applied','review','active','paused','suspended','rejected']),checks:z.record(z.string(),z.boolean()),disciplines:z.object({photo:z.enum(['T1','T2']).optional(),video:z.enum(['T2','T3']).optional()}),reason}).parse(body);if(x.status==='active'&&['kyc','bank','background','gear','portfolio','trial','training','agreement'].some(k=>!x.checks[k]))throw new AppError(422,'CHECKS_INCOMPLETE','Complete all verification, trial, training and agreement checks first');if(!this.demo&&x.status==='active')throw new AppError(503,'PROVIDER_REQUIRED','Verified KYC and agreement provider records are required for activation');return this.repo.db.transaction(async m=>{const creator=requireValue(await m.getRepository(CreatorEntity).findOneBy({id}));await m.getRepository(CreatorEntity).update(id,{status:x.status,checks:x.checks,disciplines:x.disciplines,online:x.status==='active'&&creator.online});await this.repo.audit(m,actor,'creator_reviewed',id,{status:x.status,reason:x.reason});await this.repo.event(m,'creator_status_changed',id);return {updated:true};});}
  async configurations(){return this.repo.db.getRepository(ConfigEntity).find({order:{createdAt:'DESC'},take:100});}
  async propose(actor:string,body:unknown){const base=z.object({kind:z.enum(['rates','zones']),value:z.unknown()}).parse(body);if(base.kind==='rates')validateRates(base.value);else validateZones(base.value);return this.repo.db.transaction(async m=>{await m.query("SELECT pg_advisory_xact_lock(hashtext('config:'||$1))",[base.kind]);const [v]=await m.query('SELECT COALESCE(max(version),0)+1 AS next FROM configurations WHERE kind=$1',[base.kind]);const value=base.kind==='rates'?{...base.value as RateCard,version:v.next}:base.value;const config=await m.getRepository(ConfigEntity).save({kind:base.kind,version:v.next,value:value as RateCard|Zone[],status:'draft',createdBy:actor});await this.repo.audit(m,actor,'configuration_proposed',config.id);return config;});}
  async approveConfig(actor:string,id:string){return this.repo.db.transaction(async m=>{const cfg=requireValue(await m.getRepository(ConfigEntity).findOne({where:{id},lock:{mode:'pessimistic_write'}}));if(cfg.createdBy===actor)throw new AppError(403,'MAKER_CHECKER','A different finance approver must approve this change');if(cfg.status!=='draft')throw new AppError(409,'ALREADY_REVIEWED','Configuration is not a draft');await m.query("SELECT pg_advisory_xact_lock(hashtext('config:'||$1))",[cfg.kind]);await m.getRepository(ConfigEntity).update({kind:cfg.kind,status:'active'},{status:'archived'});await m.getRepository(ConfigEntity).update(id,{status:'active',approvedBy:actor});await this.repo.audit(m,actor,'configuration_approved',id);return {approved:true};});}
  async qcQueue(){return this.repo.db.query(`SELECT g.*,o.code,(SELECT count(*)::int FROM media_assets a WHERE a.gallery_id=g.id) AS file_count FROM galleries g JOIN orders o ON o.id=g.order_id ORDER BY g.created_at DESC LIMIT 100`);}
  async qcAssets(galleryId:string){return this.repo.db.query('SELECT id,filename,bytes,kind,status,qc_status,width,height FROM media_assets WHERE gallery_id=$1 ORDER BY created_at',[galleryId]);}
  async reviewAsset(actor:string,id:string,body:unknown){const x=z.object({status:z.enum(['approved','rejected']),reason,width:z.number().int().positive().optional(),height:z.number().int().positive().optional()}).parse(body);return this.repo.db.transaction(async m=>{const [asset]=await m.query('SELECT * FROM media_assets WHERE id=$1 FOR UPDATE',[id]);if(!asset||asset.status!=='verified')throw new AppError(422,'UNVERIFIED','Only verified files can pass QC');if(asset.kind!=='edited')throw new AppError(422,'ORIGINAL','Publish an edited deliverable, not the original capture');if(x.status==='approved'&&asset.width&&asset.height&&(x.width!==asset.width||x.height!==asset.height))throw new AppError(422,'DIMENSIONS_MISMATCH','Use the dimensions measured from the uploaded image');if(x.status==='approved'&&(!x.width||!x.height))throw new AppError(422,'DIMENSIONS_REQUIRED','Record the verified output dimensions');await m.query('UPDATE media_assets SET qc_status=$2,width=$3,height=$4 WHERE id=$1',[id,x.status,x.width??null,x.height??null]);await this.repo.audit(m,actor,'asset_reviewed',id,{status:x.status,reason:x.reason});return {updated:true};});}
  async publish(actor:string,id:string,body:unknown){const x=z.object({stage:z.enum(['preview_ready','final_ready']),reason}).parse(body);return this.repo.db.transaction(async m=>{const [g]=await m.query('SELECT * FROM galleries WHERE id=$1 FOR UPDATE',[id]);if(!g)throw new AppError(404,'NOT_FOUND','Gallery not found');if(x.stage==='final_ready'&&g.status!=='preview_ready')throw new AppError(409,'PREVIEW_REQUIRED','Publish the preview before final delivery');const [counts]=await m.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE status='verified' AND qc_status='approved')::int AS ready FROM media_assets WHERE gallery_id=$1 AND kind='edited' AND status<>'discarded'",[id]);if(counts.total===0||counts.total!==counts.ready)throw new AppError(422,'QC_INCOMPLETE','Every edited deliverable must pass verification and QC');const sessions=await m.getRepository(SessionEntity).findBy({orderId:g.order_id});if(sessions.some(s=>!['media_verified','editing','preview_delivered'].includes(s.status)))throw new AppError(409,'MEDIA_INCOMPLETE','Verify media from every session before publishing');const {rates}=await this.repo.config(m);await m.query('UPDATE galleries SET status=$2,expires_at=$3 WHERE id=$1',[id,x.stage,new Date(Date.now()+rates.retentionDays*86400000)]);const status=x.stage==='final_ready'?'final_delivered':'preview_delivered';await m.getRepository(SessionEntity).update({orderId:g.order_id},{status});await m.query('UPDATE roles SET status=$2 WHERE session_id IN(SELECT id FROM sessions WHERE order_id=$1)',[g.order_id,status]);await this.repo.audit(m,actor,'gallery_published',id,x);await this.repo.event(m,'gallery_published',id,{stage:x.stage});return {published:true};});}
  async finance(){return {payments:await this.repo.db.query('SELECT * FROM payment_events ORDER BY created_at DESC LIMIT 100'),refunds:await this.repo.db.query('SELECT * FROM refunds ORDER BY created_at DESC LIMIT 100'),runs:await this.repo.db.query('SELECT * FROM payout_runs ORDER BY created_at DESC LIMIT 50'),balances:await this.repo.db.query('SELECT account,sum(amount_paise)::bigint::text AS balance_paise FROM ledger_entries GROUP BY account')};}
  async generatePayout(actor:string){return this.repo.db.transaction(async m=>{await m.query("SELECT pg_advisory_xact_lock(hashtext('payout'))");const rows=await m.query(`SELECT r.*,CASE WHEN r.discipline='video' AND r.status<>'final_delivered' THEN round(r.earning_paise*.8)::int ELSE r.earning_paise END AS payable FROM roles r WHERE r.creator_id IS NOT NULL AND r.status IN ('media_verified','editing','preview_delivered','final_delivered','closed') ORDER BY r.id`);const [run]=await m.query('INSERT INTO payout_runs(created_by) VALUES($1) RETURNING *',[actor]);let total=0;for(const r of rows){const [paid]=await m.query('SELECT COALESCE(sum(amount_paise),0)::int AS amount FROM payout_items WHERE role_id=$1',[r.id]);const amount=r.payable-paid.amount;if(amount<=0)continue;const portion=paid.amount?'delivery':'session';await m.query('INSERT INTO payout_items(run_id,role_id,creator_id,portion,amount_paise) VALUES($1,$2,$3,$4,$5)',[run.id,r.id,r.creator_id,portion,amount]);total+=amount;}if(!total)throw new AppError(422,'NO_EARNINGS','No verified, unpaid earnings are ready for payout');await m.query('UPDATE payout_runs SET total_paise=$2 WHERE id=$1',[run.id,total]);await this.repo.audit(m,actor,'payout_generated',run.id,{totalPaise:total});return {...run,total_paise:total};});}
  async approvePayout(actor:string,id:string){return this.repo.db.transaction(async m=>{const [run]=await m.query('SELECT * FROM payout_runs WHERE id=$1 FOR UPDATE',[id]);if(!run)throw new AppError(404,'NOT_FOUND','Payout run not found');if(run.created_by===actor)throw new AppError(403,'MAKER_CHECKER','You cannot approve a payout you created');if(run.status!=='draft')throw new AppError(409,'ALREADY_REVIEWED','Payout is not a draft');await m.query("UPDATE payout_runs SET status='approved',approved_by=$2 WHERE id=$1",[id,actor]);await this.repo.audit(m,actor,'payout_approved',id);await this.repo.event(m,'payout_requested',id);return {approved:true};});}
  async incident(actor:string,sessionId:string,body:unknown){await this.repo.authorizedSession(sessionId,actor);const x=z.object({kind:z.enum(['sos','delay','equipment','conduct','venue']),notes:z.string().max(2000).default(''),location:z.object({lat:z.number(),lng:z.number()}).optional()}).parse(body);return this.repo.db.transaction(async m=>{const [incident]=await m.query('INSERT INTO incidents(account_id,session_id,kind,location,notes) VALUES($1,$2,$3,$4,$5) RETURNING *',[actor,sessionId,x.kind,JSON.stringify(x.location??null),x.notes]);await this.repo.event(m,x.kind==='sos'?'sos':'incident',incident.id);return incident;});}
  async acknowledge(actor:string,id:string){return this.repo.db.transaction(async m=>{const rows=await m.query("UPDATE incidents SET status='acknowledged',acknowledged_by=$2,acknowledged_at=now() WHERE id=$1 AND status='open' RETURNING *",[id,actor]);if(!rows.length)throw new AppError(409,'ALREADY_ACKNOWLEDGED','Incident already acknowledged');await this.repo.audit(m,actor,'incident_acknowledged',id);return rows[0];});}
  async audit(){return this.repo.db.query('SELECT * FROM audit ORDER BY id DESC LIMIT 200');}
}
function validateRates(value:unknown){const amount=z.number().int().min(0).max(100000000);z.object({version:z.number().int(),rates:z.record(z.string().regex(/^(photo:T[12]|video:T[23])$/),z.object({hourPaise:amount,earningHourPaise:amount})),addons:z.record(z.string(),amount),taxBps:z.number().int().min(0).max(10000),urgencyBps:z.number().int().min(0).max(10000),peakBps:z.number().int().min(0).max(10000),peakCapPaise:amount,earlyBps:z.number().int().min(0).max(10000),peakDates:z.array(z.iso.date()),cancellationBps:z.tuple([z.number(),z.number(),z.number(),z.number(),z.number()]).refine(a=>a.every((n,i)=>Number.isInteger(n)&&n>=0&&n<=10000&&(i===0||n>=a[i-1]!))),retentionDays:z.number().int().min(1).max(3650)}).parse(value);}
function validateZones(value:unknown){z.array(z.object({id:z.string().min(1),name:z.string().min(1),polygon:z.array(z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)})).min(3),active:z.boolean(),onDemand:z.boolean(),leadMinutes:z.number().int().min(120).max(1440),feePaise:z.number().int().min(0),openHour:z.number().min(0).max(24),closeHour:z.number().min(0).max(24)}).refine(x=>x.closeHour>x.openHour)).min(1).parse(value);}
