import {z} from 'zod';
import {PlatformRepository} from '../repositories/platform';
import {AppError,requireValue} from '../middleware/errors';
import type {EntityManager} from 'typeorm';
interface PrintOrder {id:string;customer_id:string;gallery_id:string;configuration:{size:'8x8'|'10x10'|'12x12';paper:string;cover:string;copies:number;pages:{assetId:string;crop?:{x:number;y:number}}[]};status:string;total_paise:number;proof_version:number;tracking:Record<string,string>}
export class PrintService {
 constructor(private repo:PlatformRepository,private demo:boolean){}
 private async printable(m:EntityManager,order:PrintOrder){const [gallery]=await m.query("SELECT id FROM galleries WHERE id=$1 AND status='final_ready' AND (expires_at IS NULL OR expires_at>now())",[order.gallery_id]);if(!gallery)throw new AppError(409,'FINAL_REQUIRED','The final gallery must be available before printing');const inches=Number(order.configuration.size.split('x')[0]);for(const page of order.configuration.pages){const [asset]=await m.query("SELECT width,height FROM media_assets WHERE id=$1 AND gallery_id=$2 AND status='verified' AND kind='edited' AND qc_status='approved'",[page.assetId,order.gallery_id]);if(!asset||asset.width<inches*300||asset.height<inches*300)throw new AppError(422,'PRINT_RESOLUTION','Every page needs an approved image at 300 DPI');}}
 async queue(){return this.repo.db.query('SELECT p.*,a.name AS customer_name FROM print_orders p JOIN accounts a ON a.id=p.customer_id ORDER BY p.created_at DESC LIMIT 100');}
 async detail(customerId:string,id:string){const [row]=await this.repo.db.query('SELECT * FROM print_orders WHERE id=$1 AND customer_id=$2',[id,customerId]);return requireValue(row);}
 async prepare(actor:string,id:string,body:unknown){const b=z.object({reason:z.string().trim().min(5).max(1000)}).parse(body);if(!this.demo)throw new AppError(503,'PRINT_PROVIDER_REQUIRED','A print provider must quote the order');return this.repo.db.transaction(async m=>{const [row]=await m.query('SELECT * FROM print_orders WHERE id=$1 FOR UPDATE',[id]) as PrintOrder[],p=requireValue(row);if(!['draft','proof_ready'].includes(p.status))throw new AppError(409,'PROOF_LOCKED','The proof cannot change after customer approval');await this.printable(m,p);const base=({ '8x8':149900,'10x10':199900,'12x12':249900 }[p.configuration.size]+Math.max(0,p.configuration.pages.length-10)*7500+(p.configuration.cover==='hard'?30000:0))*p.configuration.copies+15000;const total=base+Math.round(base*.18);const [rows]=await m.query("UPDATE print_orders SET total_paise=$2,status='proof_ready',proof_version=proof_version+1,updated_at=now() WHERE id=$1 RETURNING *",[id,total]);await this.repo.audit(m,actor,'print_proof_prepared',id,{reason:b.reason,totalPaise:total,illustrative:true});await this.repo.event(m,'print_updated',id);return rows[0];});}
 async approveDemo(customerId:string,id:string,body:unknown){const b=z.object({expectedTotalPaise:z.number().int().positive(),proofVersion:z.number().int().positive()}).parse(body);if(!this.demo)throw new AppError(503,'PRINT_PROVIDER_REQUIRED','Print payment provider is not configured');return this.repo.db.transaction(async m=>{const [row]=await m.query('SELECT * FROM print_orders WHERE id=$1 AND customer_id=$2 FOR UPDATE',[id,customerId]) as PrintOrder[],p=requireValue(row);if(['in_production','shipped','delivered'].includes(p.status))return {...p,simulated:true};if(p.status!=='proof_ready')throw new AppError(409,'PROOF_REQUIRED','Review the prepared proof before payment');if(p.total_paise!==b.expectedTotalPaise||p.proof_version!==b.proofVersion)throw new AppError(409,'PROOF_CHANGED','The proof or price changed. Review it again before approving.');await this.printable(m,p);await this.repo.ledger(m,`demo-print:${p.id}`,null,[{account:'demo_print_clearing',amountPaise:p.total_paise},{account:'print_order_deposits',amountPaise:-p.total_paise}]);await m.query("UPDATE print_orders SET status='in_production',proof_approved_at=now(),partner_reference=$2,updated_at=now() WHERE id=$1",[id,`DEMO-${id.slice(0,8)}`]);await this.repo.audit(m,customerId,'print_proof_approved',id,{proofVersion:p.proof_version,totalPaise:p.total_paise,simulated:true});await this.repo.event(m,'print_updated',id);return {...p,status:'in_production',simulated:true};});}
 async advance(actor:string,id:string,body:unknown){const b=z.object({stage:z.enum(['shipped','delivered','reprint','refunded']),reason:z.string().trim().min(5).max(1000),trackingCode:z.string().max(100).optional()}).parse(body);if(!this.demo)throw new AppError(503,'PRINT_PROVIDER_REQUIRED','Fulfilment requires verified provider events');return this.repo.db.transaction(async m=>{const [row]=await m.query('SELECT * FROM print_orders WHERE id=$1 FOR UPDATE',[id]) as PrintOrder[],p=requireValue(row);if(p.status===b.stage)return p;const valid=b.stage==='shipped'?p.status==='in_production':b.stage==='delivered'?p.status==='shipped':b.stage==='reprint'?p.status==='delivered':['in_production','shipped','delivered'].includes(p.status);if(!valid)throw new AppError(409,'PRINT_STATE','This update is not allowed in the current print stage');if(b.stage==='shipped'&&!b.trackingCode)throw new AppError(422,'TRACKING_REQUIRED','Enter a clearly labelled demo tracking reference');if(b.stage==='refunded')await this.repo.ledger(m,`demo-print-refund:${id}`,null,[{account:'print_order_deposits',amountPaise:p.total_paise},{account:'demo_print_clearing',amountPaise:-p.total_paise}]);const status=b.stage==='reprint'?'in_production':b.stage;await m.query('UPDATE print_orders SET status=$2,tracking=$3,updated_at=now() WHERE id=$1',[id,status,JSON.stringify({...p.tracking,...(b.trackingCode?{reference:b.trackingCode}:{})})]);await this.repo.audit(m,actor,`print_${b.stage}`,id,{reason:b.reason,simulated:true});await this.repo.event(m,'print_updated',id);return {status,simulated:true};});}
}
