import {z} from 'zod';
import {PlatformRepository} from '../repositories/platform';
import {AppError,requireValue} from '../middleware/errors';
export class PrivacyService {
 constructor(private repo:PlatformRepository,private demo:boolean){}
 async requests(accountId:string){return this.repo.db.query('SELECT id,kind,status,review_note,created_at,completed_at FROM privacy_requests WHERE account_id=$1 ORDER BY created_at DESC LIMIT 100',[accountId]);}
 async queue(){return this.repo.db.query('SELECT p.*,a.name FROM privacy_requests p JOIN accounts a ON a.id=p.account_id ORDER BY p.created_at DESC LIMIT 100');}
 async export(accountId:string,id:string){return this.repo.db.transaction(async m=>{const [r]=await m.query("SELECT id FROM privacy_requests WHERE id=$1 AND account_id=$2 AND kind='export' FOR UPDATE",[id,accountId]);if(!r)throw new AppError(404,'NOT_FOUND','Export request not found');const account=await this.repo.account(accountId,m);const orders=await m.query('SELECT id,code,category,status,total_paise,currency,created_at FROM orders WHERE customer_id=$1',[accountId]);const sessions=await m.query('SELECT s.id,s.input,s.status,s.start_at,s.end_at FROM sessions s JOIN orders o ON o.id=s.order_id WHERE o.customer_id=$1',[accountId]);const creator=await m.query('SELECT name,status,disciplines,languages,profile,checks,metrics FROM creators WHERE account_id=$1',[accountId]);const tickets=await m.query('SELECT subject,body,category,status,created_at FROM tickets WHERE account_id=$1',[accountId]);const messages=await m.query('SELECT session_id,body,created_at FROM messages WHERE actor_id=$1',[accountId]);const ratings=await m.query('SELECT session_id,kind,stars,comment,created_at FROM ratings WHERE rater_id=$1',[accountId]);await m.query("UPDATE privacy_requests SET status='completed',completed_at=now() WHERE id=$1",[id]);await this.repo.audit(m,accountId,'privacy_export_downloaded',id);return {generatedAt:new Date().toISOString(),account:{id:account.id,name:account.name,language:account.language,role:account.role,consents:account.consents},orders,sessions,creator,tickets,messages,ratings};});}
 async review(actor:string,id:string,body:unknown){const b=z.object({action:z.enum(['request_information','complete_demo_deletion']),reason:z.string().trim().min(10).max(2000)}).parse(body);return this.repo.db.transaction(async m=>{const [r]=await m.query('SELECT * FROM privacy_requests WHERE id=$1 FOR UPDATE',[id]);requireValue(r);if(r.status==='completed')return {completed:true};if(b.action==='request_information'){await m.query("UPDATE privacy_requests SET status='needs_information',reviewed_by=$2,review_note=$3 WHERE id=$1",[id,actor,b.reason]);return {updated:true};}if(!this.demo)throw new AppError(503,'PRIVACY_PROVIDER_REQUIRED','Live deletion requires verified provider cleanup and an approved record-retention policy');await m.query('SELECT id FROM accounts WHERE id=$1 FOR UPDATE',[r.account_id]);if(r.kind!=='delete')throw new AppError(409,'WRONG_REQUEST','This request is not for deletion');const active=await m.query("SELECT 1 FROM sessions s JOIN orders o ON o.id=s.order_id WHERE o.customer_id=$1 AND s.status NOT IN ('cancelled','refunded','final_delivered','closed') UNION SELECT 1 FROM roles r JOIN creators c ON c.id=r.creator_id WHERE c.account_id=$1 AND r.status NOT IN ('cancelled','refunded','final_delivered','closed') UNION SELECT 1 FROM print_orders WHERE customer_id=$1 AND status IN ('in_production','shipped')",[r.account_id]);if(active.length)throw new AppError(409,'ACTIVE_BOOKINGS','Resolve active bookings before completing deletion');
 await m.query("UPDATE accounts SET name='Deleted demo account',consents='{}',disabled_at=now() WHERE id=$1",[r.account_id]);await m.query("UPDATE creators SET name='Deleted demo creator',profile='{}',status='suspended',online=false WHERE account_id=$1",[r.account_id]);await m.query("UPDATE shares SET revoked_at=now() WHERE gallery_id IN(SELECT g.id FROM galleries g JOIN orders o ON o.id=g.order_id WHERE o.customer_id=$1)",[r.account_id]);await m.query("UPDATE galleries SET status='expired',expires_at=now() WHERE order_id IN(SELECT id FROM orders WHERE customer_id=$1)",[r.account_id]);await m.query("UPDATE messages SET body='[Removed at account request]' WHERE actor_id=$1",[r.account_id]);await m.query("UPDATE ratings SET comment='' WHERE rater_id=$1",[r.account_id]);await m.query("UPDATE tickets SET subject='[Removed at account request]',body='[Removed at account request]' WHERE account_id=$1",[r.account_id]);await m.query("UPDATE ticket_messages SET body='[Removed at account request]' WHERE actor_id=$1",[r.account_id]);await m.query("UPDATE print_orders SET address='{}' WHERE customer_id=$1",[r.account_id]);
 await m.query("UPDATE session_changes SET data=data-'input' WHERE customer_id=$1",[r.account_id]);await m.query("UPDATE incidents SET notes='[Removed at account request]',location=NULL WHERE account_id=$1",[r.account_id]);await m.query('DELETE FROM locations WHERE creator_id IN(SELECT id FROM creators WHERE account_id=$1) OR session_id IN(SELECT s.id FROM sessions s JOIN orders o ON o.id=s.order_id WHERE o.customer_id=$1)',[r.account_id]);await m.query("UPDATE session_events SET payload=payload-'location' WHERE actor_id=$1",[r.account_id]);
 const sessions=await m.query('SELECT s.id,s.input FROM sessions s JOIN orders o ON o.id=s.order_id WHERE o.customer_id=$1',[r.account_id]);for(const s of sessions){const input={...s.input,notes:'',venue:{type:s.input.venue.type,lat:0,lng:0,address:'Removed',contactName:'Removed',contactPhone:'Removed',notes:''}};await m.query('UPDATE sessions SET input=$2 WHERE id=$1',[s.id,JSON.stringify(input)]);}await m.query("UPDATE quotes SET input=jsonb_build_object('category',input->>'category','sessions','[]'::jsonb,'termsVersion',input->>'termsVersion') WHERE customer_id=$1",[r.account_id]);await m.query("UPDATE privacy_requests SET status='completed',reviewed_by=$2,review_note=$3,completed_at=now() WHERE id=$1",[id,actor,b.reason]);await this.repo.audit(m,actor,'demo_privacy_deletion',id,{accountId:r.account_id,retained:'financial and immutable audit records; blocked identity reference'});return {completed:true,retained:'Financial and audit records and the blocked identity reference remain. Live provider deletion is not simulated.'};});}
}
