import {availableCredits} from './credits';
import {PlatformRepository} from '../repositories/platform';
import {OrderEntity,CreatorEntity} from '../entities';
import {AppError} from '../middleware/errors';
export class QueryService {
  constructor(private repo:PlatformRepository){}
  async bookings(id:string,page:number){return this.repo.db.getRepository(OrderEntity).find({where:{customerId:id},order:{createdAt:'DESC'},skip:(page-1)*25,take:25});}
  async galleries(id:string){return this.repo.db.query('SELECT g.*,o.code,o.category FROM galleries g JOIN orders o ON o.id=g.order_id WHERE o.customer_id=$1 ORDER BY g.created_at DESC LIMIT 100',[id]);}
  async creator(id:string){return this.repo.db.getRepository(CreatorEntity).findOneBy({accountId:id});}
  async tracking(id:string,sessionId:string){await this.repo.authorizedSession(sessionId,id);return {locations:await this.repo.db.query('SELECT DISTINCT ON(creator_id) creator_id,lat,lng,accuracy,created_at FROM locations WHERE session_id=$1 ORDER BY creator_id,created_at DESC',[sessionId]),etaAvailable:false};}
  async messages(id:string,sessionId:string){await this.repo.authorizedSession(sessionId,id);return this.repo.db.query('SELECT id,actor_id,body,created_at FROM messages WHERE session_id=$1 ORDER BY created_at DESC LIMIT 100',[sessionId]);}
  async credits(id:string){return availableCredits(this.repo.db.manager,id);}
  async notifications(id:string){return this.repo.db.query('SELECT id,title,body,entity_id,read_at,created_at FROM notifications WHERE account_id=$1 ORDER BY created_at DESC LIMIT 100',[id]);}
  async readNotification(id:string,notificationId:string){const [rows]=await this.repo.db.query('UPDATE notifications SET read_at=coalesce(read_at,now()) WHERE id=$1 AND account_id=$2 RETURNING id',[notificationId,id]);if(!rows.length)throw new AppError(404,'NOT_FOUND','Notification not found');return {read:true};}
  async availability(id:string){const c=await this.repo.creator(id);return this.repo.db.query('SELECT id,start_at,end_at,available FROM availability WHERE creator_id=$1 AND end_at>now() ORDER BY start_at LIMIT 100',[c.id]);}
  async removeAvailability(id:string,blockId:string){const c=await this.repo.creator(id);const [rows]=await this.repo.db.query('DELETE FROM availability WHERE id=$1 AND creator_id=$2 RETURNING id',[blockId,c.id]);if(!rows.length)throw new AppError(404,'NOT_FOUND','Availability block not found');return {removed:true};}
  async ticketMessages(id:string,ticketId:string,staff=false){const [ticket]=await this.repo.db.query('SELECT account_id FROM tickets WHERE id=$1',[ticketId]);if(!ticket||!staff&&ticket.account_id!==id)throw new AppError(404,'NOT_FOUND','Ticket not found');return this.repo.db.query('SELECT id,body,created_at,actor_id FROM ticket_messages WHERE ticket_id=$1 AND NOT internal ORDER BY created_at LIMIT 100',[ticketId]);}
  async tickets(id:string,staff=false){return this.repo.db.query(`SELECT id,category,subject,body,priority,status,due_at,created_at FROM tickets ${staff?'':'WHERE account_id=$1'} ORDER BY created_at DESC LIMIT 100`,staff?[]:[id]);}
  async ticketReply(id:string,ticketId:string,body:string,staff=false){const [ticket]=await this.repo.db.query('SELECT account_id FROM tickets WHERE id=$1',[ticketId]);if(!ticket||!staff&&ticket.account_id!==id)throw new AppError(404,'NOT_FOUND','Ticket not found');const [reply]=await this.repo.db.query('INSERT INTO ticket_messages(ticket_id,actor_id,body) VALUES($1,$2,$3) RETURNING *',[ticketId,id,body]);return reply;}
  async earnings(id:string){const c=await this.repo.creator(id);return {jobs:await this.repo.db.query('SELECT r.id,r.earning_paise,r.status,s.start_at,o.code FROM roles r JOIN sessions s ON s.id=r.session_id JOIN orders o ON o.id=s.order_id WHERE r.creator_id=$1 ORDER BY s.start_at DESC LIMIT 100',[c.id]),payouts:await this.repo.db.query('SELECT * FROM payout_items WHERE creator_id=$1 ORDER BY id DESC LIMIT 100',[c.id])};}
  async payments(id:string){return this.repo.db.query('SELECT p.*,o.code FROM payment_events p JOIN orders o ON o.id=p.order_id WHERE o.customer_id=$1 ORDER BY p.created_at DESC LIMIT 100',[id]);}
  async printOrders(id:string){return this.repo.db.query('SELECT * FROM print_orders WHERE customer_id=$1 ORDER BY created_at DESC LIMIT 100',[id]);}
  async favourite(id:string,assetId:string,selected:boolean){const [a]=await this.repo.db.query('SELECT a.id FROM media_assets a JOIN galleries g ON g.id=a.gallery_id JOIN orders o ON o.id=g.order_id WHERE a.id=$1 AND o.customer_id=$2',[assetId,id]);if(!a)throw new AppError(404,'NOT_FOUND','Photo not found');if(selected)await this.repo.db.query('INSERT INTO favourites(customer_id,asset_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,assetId]);else await this.repo.db.query('DELETE FROM favourites WHERE customer_id=$1 AND asset_id=$2',[id,assetId]);return {selected};}
  async revoke(id:string,shareId:string){const [rows]=await this.repo.db.query('UPDATE shares SET revoked_at=now() WHERE id=$1 AND gallery_id IN(SELECT g.id FROM galleries g JOIN orders o ON o.id=g.order_id WHERE o.customer_id=$2) RETURNING id',[shareId,id]);if(!rows.length)throw new AppError(404,'NOT_FOUND','Share not found');return {revoked:true};}
  async upload(id:string,uploadId:string){const c=await this.repo.creator(id);const [u]=await this.repo.db.query('SELECT * FROM uploads WHERE id=$1 AND creator_id=$2',[uploadId,c.id]);if(!u)throw new AppError(404,'NOT_FOUND','Upload not found');return {...u,assets:await this.repo.db.query('SELECT id,filename,bytes,received_bytes,status FROM media_assets WHERE upload_id=$1',[uploadId])};}
  async shares(id:string,galleryId:string){const [g]=await this.repo.db.query('SELECT g.id FROM galleries g JOIN orders o ON o.id=g.order_id WHERE g.id=$1 AND o.customer_id=$2',[galleryId,id]);if(!g)throw new AppError(404,'NOT_FOUND','Gallery not found');return this.repo.db.query('SELECT id,kind,expires_at,allow_download,revoked_at FROM shares WHERE gallery_id=$1',[galleryId]);}
}
