import {rateLimit} from 'express-rate-limit';
import {AuthenticationService} from '../services/authentication';
import {pipeline} from 'node:stream/promises';
import {CreatorProfileService} from '../services/creator-profile';
import {SessionTimingService} from '../services/session-timing';
import {RatingService} from '../services/ratings';
import {PaymentRecordsService} from '../services/payment-records';
import {Router,raw} from 'express';
import {z} from 'zod';
import {createHmac,timingSafeEqual} from 'node:crypto';
import {PlatformRepository} from '../repositories/platform';
import {BookingService} from '../services/bookings';
import {DispatchService} from '../services/dispatch';
import {PrivacyService} from '../services/privacy';
import {PrintService} from '../services/prints';
import {RecoveryService} from '../services/recovery';
import {SessionChangeService} from '../services/session-changes';
import {SessionService} from '../services/sessions';
import {MediaService} from '../services/media';
import {OperationsService} from '../services/operations';
import {AccountService} from '../services/accounts';
import {QueryService} from '../services/queries';
import {authentication,permit,principal} from '../middleware/auth';
import {AppError} from '../middleware/errors';
import {id,page,respond} from '../controllers/platform';
import type {Env} from '../config/env';
import {categories,earliestServiceStart} from '@kamraw/domain';
export function routes(repo:PlatformRepository,env:Env){
  const records=new PaymentRecordsService(repo,env.APP_MODE==='demo'),profiles=new CreatorProfileService(repo,env.APP_MODE==='demo'),ratings=new RatingService(repo),timing=new SessionTimingService(repo);
  const router=Router(),booking=new BookingService(repo),changes=new SessionChangeService(repo),recovery=new RecoveryService(repo),prints=new PrintService(repo,env.APP_MODE==='demo'),privacy=new PrivacyService(repo,env.APP_MODE==='demo'),dispatch=new DispatchService(repo),session=new SessionService(repo,env.APP_MODE==='demo'),media=new MediaService(repo,env.MEDIA_ROOT,env.APP_MODE==='demo'),ops=new OperationsService(repo,env.APP_MODE==='demo'),account=new AccountService(repo),query=new QueryService(repo);
  const auth=new AuthenticationService(repo,env.APP_MODE==='demo');
  router.use('/auth',rateLimit({windowMs:15*60000,limit:100,standardHeaders:'draft-8',legacyHeaders:false}),(_req,res,next)=>{res.setHeader('Cache-Control','no-store');next();});
  router.post('/auth/demo',respond(req=>auth.demoLogin(req.body)));
  router.post('/auth/phone/start',respond(req=>auth.requestCode(req.body)));
  router.post('/auth/phone/verify',respond(req=>auth.verifyCode(req.body)));
  router.post('/auth/logout',respond(req=>auth.logout(req.headers.authorization?.replace(/^Bearer /,''))));
  router.get('/catalog',respond(async()=>{const config=await repo.config(),now=new Date(),available=config.zones.filter(z=>z.active&&z.onDemand).map(z=>earliestServiceStart(now,z.leadMinutes,z.openHour,z.closeHour));return {...config,categories,serverTime:now.toISOString(),earliestStart:available.length?new Date(Math.min(...available.map(d=>d.getTime()))).toISOString():null,mode:env.APP_MODE};}));
  router.get('/demo/accounts',respond(async()=>{if(env.APP_MODE!=='demo')throw new AppError(404,'NOT_FOUND','Not found');return repo.db.query("SELECT name,role,replace(subject,'demo:','') AS handle FROM accounts WHERE subject LIKE 'demo:%' ORDER BY role,name");}));
  router.post('/shared/:token',respond(req=>media.sharedTickets(z.string().min(40).max(100).parse(req.params.token),z.object({pin:z.string().optional()}).parse(req.body).pin)));
  router.get('/media/:id',async(req,res)=>{const download=req.query.download==='1';const {asset,filename}=await media.authorizedFile(id(req),z.string().max(2000).parse(req.query.ticket),download);res.setHeader('Cache-Control','private, no-store');res.setHeader('Referrer-Policy','no-referrer');if(download)res.download(filename,asset.filename);else res.type(asset.filename).sendFile(filename);});
  router.get('/gallery-download/:id',async(req,res)=>{const stream=await media.archive(id(req),z.string().max(2000).parse(req.query.ticket));res.setHeader('Cache-Control','private, no-store');res.setHeader('Referrer-Policy','no-referrer');res.type('application/zip').attachment(`kamraw-${id(req)}.zip`);await pipeline(stream,res);});
  // Streaming chunks require raw parsing before the JSON parser in app.ts.
  router.use(authentication(env,repo));
  const uid=(req:Parameters<typeof principal>[0])=>principal(req).account.id;
  router.get('/me',respond(async req=>principal(req).account));router.put('/me',respond(req=>account.profile(uid(req),req.body)));router.post('/me/privacy',respond(req=>account.privacy(uid(req),req.body),201));
  router.get('/me/privacy/:id/data',respond(req=>privacy.export(uid(req),id(req))));
  router.get('/me/privacy',respond(req=>privacy.requests(uid(req))));router.get('/me/exports/:id',async(req,res)=>{const data=await privacy.export(uid(req),id(req));res.setHeader('Cache-Control','no-store');res.attachment('kamraw-personal-data.json').json(data);});router.get('/ops/privacy',permit('privacy'),respond(()=>privacy.queue()));router.post('/ops/privacy/:id/review',permit('privacy'),respond(req=>privacy.review(uid(req),id(req),req.body)));
  router.post('/quotes',respond(req=>booking.quote(uid(req),req.body),201));router.post('/checkout',respond(req=>{const b=z.object({quoteId:z.uuid(),useCredits:z.boolean().default(false),expectedCreditPaise:z.number().int().nonnegative().optional()}).parse(req.body);return booking.checkout(uid(req),b.quoteId,new Date(),b.useCredits,b.expectedCreditPaise);},201));
  router.post('/orders/:id/demo-pay',respond(async req=>{if(env.APP_MODE!=='demo')throw new AppError(404,'NOT_FOUND','Not found');const result=await booking.demoPay(uid(req),id(req));const roles=await repo.db.query('SELECT r.id FROM roles r JOIN sessions s ON s.id=r.session_id WHERE s.order_id=$1',[id(req)]) as {id:string}[];for(const r of roles)await dispatch.dispatch(r.id);return result;}));
  router.get('/orders',respond(req=>query.bookings(uid(req),page(req))));router.get('/orders/:id',respond(req=>repo.orderDetail(id(req),uid(req))));
  router.get('/sessions/:id/recovery',respond(req=>recovery.failures(uid(req),id(req))));router.post('/sessions/:id/replacement',respond(req=>recovery.chooseReplacement(uid(req),id(req))));
  router.get('/creator/cancellations',respond(req=>recovery.creatorHistory(uid(req))));router.get('/creator/roles/:id/cancellation',respond(req=>recovery.preview(uid(req),id(req))));router.post('/creator/roles/:id/cancel',respond(req=>recovery.cancel(uid(req),id(req),req.body)));
  router.get('/sessions/:id/changes',respond(req=>changes.list(uid(req),id(req))));
  router.post('/sessions/:id/changes',respond(req=>changes.request(uid(req),id(req),req.body),201));
  router.post('/changes/:id/dismiss',respond(req=>changes.dismiss(uid(req),id(req))));
  router.post('/changes/:id/respond',respond(req=>changes.respond(uid(req),id(req),z.object({accepted:z.boolean()}).parse(req.body).accepted)));
  router.post('/changes/:id/demo-apply',respond(req=>{if(env.APP_MODE!=='demo')throw new AppError(503,'PROVIDER_REQUIRED','Payment integration is not configured');return changes.applyDemo(uid(req),id(req),z.object({expectedDeltaPaise:z.number().int()}).parse(req.body).expectedDeltaPaise);}));
  router.get('/sessions/:id/cancellation',respond(req=>booking.cancelPreview(uid(req),id(req))));router.post('/sessions/:id/cancel',respond(req=>{const b=z.object({expectedFeePaise:z.number().int().nonnegative(),refundMethod:z.enum(['source','credit']).default('source')}).parse(req.body);return booking.cancel(uid(req),id(req),b.expectedFeePaise,new Date(),b.refundMethod);}));
  router.get('/sessions/:id/tracking',respond(req=>query.tracking(uid(req),id(req))));router.post('/sessions/:id/location',respond(req=>session.location(uid(req),id(req),req.body)));router.get('/sessions/:id/messages',respond(req=>query.messages(uid(req),id(req))));router.post('/sessions/:id/messages',respond(req=>account.message(uid(req),id(req),req.body),201));
  router.post('/sessions/:id/incidents',respond(req=>ops.incident(uid(req),id(req),req.body),201));router.post('/sessions/:id/ratings',respond(req=>ratings.rate(uid(req),id(req),req.body),201));
  router.get('/sessions/:id/timing',respond(req=>timing.detail(uid(req),id(req))));
  router.put('/sessions/:id/venue-timing',respond(req=>timing.venue(uid(req),id(req),req.body)));
  router.post('/creator/roles/:id/completion-request',respond(req=>timing.request(uid(req),id(req),req.body),201));
  router.post('/completion-requests/:id/decision',respond(req=>timing.decide(uid(req),id(req),req.body)));
  router.get('/ops/timing-conflicts',permit('operations'),respond(()=>timing.conflicts()));
  router.post('/ops/timing-conflicts/:id/resolve',permit('operations'),respond(req=>timing.resolveConflict(uid(req),id(req),req.body)));
  router.get('/ops/completion-requests',permit('operations'),respond(()=>timing.queue()));
  router.post('/ops/completion-requests/:id/decision',permit('operations'),respond(req=>timing.decide(uid(req),id(req),req.body,new Date(),true)));
  router.get('/sessions/:id/ratings',respond(req=>ratings.list(uid(req),id(req))));
  router.get('/sessions/:id/creators',respond(req=>profiles.assigned(uid(req),id(req))));
  router.get('/creator/performance',respond(req=>profiles.self(uid(req))));
  router.put('/creator/photo',raw({type:'application/octet-stream',limit:'4mb'}),respond(req=>profiles.photo(uid(req),req.body)));
  router.get('/credits',respond(req=>query.credits(uid(req))));
  router.get('/notifications',respond(req=>query.notifications(uid(req))));router.post('/notifications/:id/read',respond(req=>query.readNotification(uid(req),id(req))));
  router.get('/creator/availability',respond(req=>query.availability(uid(req))));router.delete('/creator/availability/:id',respond(req=>query.removeAvailability(uid(req),id(req))));
  router.get('/creator',respond(req=>query.creator(uid(req))));router.post('/creator/apply',respond(req=>account.onboard(uid(req),req.body),201));router.put('/creator/online',respond(req=>account.online(uid(req),z.object({online:z.boolean()}).parse(req.body).online)));router.post('/creator/availability',respond(req=>account.availability(uid(req),req.body),201));
  router.get('/creator/offers',respond(req=>dispatch.offers(uid(req))));router.post('/creator/offers/:id/decline',respond(req=>dispatch.decline(uid(req),id(req))));router.post('/creator/offers/:id/accept',respond(req=>dispatch.accept(uid(req),id(req))));router.get('/creator/jobs',respond(req=>dispatch.jobs(uid(req))));router.get('/creator/earnings',respond(req=>query.earnings(uid(req))));router.post('/creator/roles/:id/events',respond(req=>session.transition(uid(req),id(req),req.body)));
  router.post('/uploads',respond(req=>media.manifest(uid(req),req.body),201));router.post('/uploads/:id/abandon',respond(req=>media.abandon(uid(req),id(req))));router.get('/uploads/:id',respond(req=>query.upload(uid(req),id(req))));router.put('/assets/:id/chunks',raw({type:'application/octet-stream',limit:'8mb'}),respond(req=>media.chunk(uid(req),id(req),z.coerce.number().int().nonnegative().parse(req.query.offset),req.body)));router.post('/uploads/:id/receipt',respond(req=>media.receipt(uid(req),id(req))));
  router.post('/galleries/:id/download-ticket',respond(req=>media.archiveTicket(uid(req),id(req))));
  router.get('/galleries',respond(req=>query.galleries(uid(req))));router.get('/galleries/:id',respond(req=>media.gallery(uid(req),id(req))));router.post('/galleries/:id/shares',respond(req=>media.share(uid(req),id(req),req.body),201));router.get('/galleries/:id/shares',respond(req=>query.shares(uid(req),id(req))));router.delete('/shares/:id',respond(req=>query.revoke(uid(req),id(req))));
  router.post('/shared-invite/:token',respond(req=>media.sharedTickets(z.string().min(40).parse(req.params.token),undefined,uid(req))));
  router.post('/assets/:id/ticket',respond(req=>media.ownerTicket(uid(req),id(req))));
  router.get('/assets/:id/file',async(req,res)=>{const {asset,filename}=await media.file(id(req));await media.gallery(uid(req),asset.gallery_id);res.setHeader('Cache-Control','private, no-store');res.download(filename,asset.filename);});
  router.put('/assets/:id/favourite',respond(req=>query.favourite(uid(req),id(req),z.object({selected:z.boolean()}).parse(req.body).selected)));
  router.get('/tickets/:id/messages',respond(req=>query.ticketMessages(uid(req),id(req))));router.get('/ops/tickets/:id/messages',permit('support'),respond(req=>query.ticketMessages(uid(req),id(req),true)));
  router.get('/tickets',respond(req=>query.tickets(uid(req))));router.post('/tickets',respond(req=>account.ticket(uid(req),req.body),201));router.post('/tickets/:id/messages',respond(req=>query.ticketReply(uid(req),id(req),z.object({body:z.string().min(1).max(4000)}).parse(req.body).body)));
  router.get('/prints/:id',respond(req=>prints.detail(uid(req),id(req))));router.post('/prints/:id/demo-approve',respond(req=>prints.approveDemo(uid(req),id(req),req.body)));router.get('/ops/prints',permit('operations'),respond(()=>prints.queue()));router.post('/ops/prints/:id/proof',permit('operations'),respond(req=>prints.prepare(uid(req),id(req),req.body)));router.post('/ops/prints/:id/advance',permit('operations'),respond(req=>prints.advance(uid(req),id(req),req.body)));
  router.get('/payment-records',respond(req=>records.history(uid(req),page(req))));router.get('/orders/:id/payment-record',respond(req=>records.detail(uid(req),id(req))));router.get('/orders/:id/statement',respond(req=>records.statement(uid(req),id(req))));
  router.get('/payments',respond(req=>query.payments(uid(req))));router.post('/prints',respond(req=>account.prints(uid(req),req.body),201));router.get('/prints',respond(req=>query.printOrders(uid(req))));
  router.get('/ops/incidents',permit('operations'),respond(()=>repo.db.query('SELECT i.*,o.code FROM incidents i JOIN sessions s ON s.id=i.session_id JOIN orders o ON o.id=s.order_id ORDER BY i.created_at DESC LIMIT 100')));router.get('/ops/dashboard',permit('operations'),respond(()=>ops.dashboard()));router.get('/ops/creators',permit('onboarding'),respond(()=>ops.creators()));router.put('/ops/creators/:id',permit('onboarding'),respond(req=>ops.reviewCreator(uid(req),id(req),req.body)));
  router.get('/ops/dispatch',permit('dispatch'),respond(()=>dispatch.board()));router.get('/ops/roles/:id/candidates',permit('dispatch'),respond(req=>dispatch.manualCandidates(id(req))));router.post('/ops/roles/:id/offer',permit('dispatch'),respond(req=>dispatch.manualOffer(uid(req),id(req),req.body)));
  router.post('/ops/roles/:id/dispatch',permit('dispatch'),respond(req=>dispatch.dispatch(id(req))));router.post('/ops/incidents/:id/acknowledge',permit('operations'),respond(req=>ops.acknowledge(uid(req),id(req))));
  router.get('/ops/configurations',permit('config:read'),respond(()=>ops.configurations()));router.post('/ops/configurations',permit('config:write'),respond(req=>ops.propose(uid(req),req.body),201));router.post('/ops/configurations/:id/approve',permit('config:approve'),respond(req=>ops.approveConfig(uid(req),id(req))));
  router.post('/ops/assets/:id/ticket',permit('qc'),respond(req=>media.reviewTicket(uid(req),id(req))));router.get('/ops/qc',permit('qc'),respond(()=>ops.qcQueue()));router.get('/ops/qc/:id/assets',permit('qc'),respond(req=>ops.qcAssets(id(req))));router.put('/ops/assets/:id/review',permit('qc'),respond(req=>ops.reviewAsset(uid(req),id(req),req.body)));router.post('/ops/galleries/:id/publish',permit('qc'),respond(req=>ops.publish(uid(req),id(req),req.body)));
  router.get('/ops/tickets',permit('support'),respond(req=>query.tickets(uid(req),true)));router.post('/ops/tickets/:id/messages',permit('support'),respond(req=>query.ticketReply(uid(req),id(req),z.object({body:z.string().min(1).max(4000)}).parse(req.body).body,true)));
  router.get('/ops/finance',permit('finance'),respond(()=>ops.finance()));router.post('/ops/payouts',permit('payout:create'),respond(req=>ops.generatePayout(uid(req)),201));router.post('/ops/payouts/:id/approve',permit('payout:approve'),respond(req=>ops.approvePayout(uid(req),id(req))));router.get('/ops/audit',permit('audit'),respond(()=>ops.audit()));
  return router;
}
export function webhook(repo:PlatformRepository,env:Env){return respond(async req=>{if(!env.PAYMENT_WEBHOOK_SECRET)throw new AppError(503,'PROVIDER_REQUIRED','Payment webhooks are not configured');const received=req.headers['x-kamraw-signature'];if(typeof received!=='string'||!/^[a-f0-9]{64}$/.test(received)||!Buffer.isBuffer(req.body))throw new AppError(401,'BAD_SIGNATURE','Invalid webhook signature');const expected=createHmac('sha256',env.PAYMENT_WEBHOOK_SECRET).update(req.body).digest();if(!timingSafeEqual(expected,Buffer.from(received,'hex')))throw new AppError(401,'BAD_SIGNATURE','Invalid webhook signature');const event=z.object({id:z.string().min(1).max(100),orderId:z.uuid(),amountPaise:z.number().int().positive(),currency:z.literal('INR'),provider:z.string().min(1)}).parse(JSON.parse(req.body.toString()));return new BookingService(repo).confirmPayment(event);});}
