import React,{useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {Card,Field,Chips,styles} from './ui';
import {useSession} from '../services/session';

const articles=[
  {id:'booking',en:['How do I book a shoot?','Choose your event, photo or video coverage, tier, crew size, venue and date. Starts must be within the service zone’s opening hours. Allow at least the lead time shown in the app; scheduled bookings can be up to 180 days ahead. Review the itemized quote before confirming.'],ta:['படப்பிடிப்பை முன்பதிவு செய்வது எப்படி?','நிகழ்ச்சி, புகைப்படம் அல்லது காணொளி சேவை, தரம், குழுவின் எண்ணிக்கை, இடம் மற்றும் தேதியைத் தேர்ந்தெடுக்கவும். சேவைப் பகுதியின் செயல்பாட்டு நேரத்திற்குள் தொடங்க வேண்டும். செயலியில் காட்டப்படும் முன்னேற்பாட்டு நேரத்தை அனுமதிக்கவும். 180 நாட்கள் முன்புவரை முன்பதிவு செய்யலாம். உறுதிசெய்யும் முன் கட்டண விவரங்களைச் சரிபார்க்கவும்.']},
  {id:'change',en:['Can I change or cancel a booking?','Open your booking to review a reschedule, extension or cancellation. One reschedule is available more than 72 hours before the shoot. Extra time needs every creator’s approval. Any price difference or cancellation fee is shown before you confirm. Demo policies and prices are illustrative.'],ta:['முன்பதிவை மாற்றவோ ரத்து செய்யவோ முடியுமா?','உங்கள் முன்பதிவைத் திறந்து தேதி மாற்றம், நேர நீட்டிப்பு அல்லது ரத்துசெய்தலைப் பரிசீலிக்கவும். படப்பிடிப்பிற்கு 72 மணிநேரத்திற்கும் அதிகமாக இருக்கும்போது ஒருமுறை தேதி மாற்றலாம். நேர நீட்டிப்பிற்கு அனைத்துப் படைப்பாளர்களின் ஒப்புதலும் தேவை. உறுதிசெய்வதற்கு முன் கட்டண வேறுபாடும் ரத்துக் கட்டணமும் காட்டப்படும். சோதனைப் பதிப்பின் விதிகளும் விலைகளும் எடுத்துக்காட்டுகள் மட்டுமே.']},
  {id:'creator',en:['Where is my creator?','Open the tracking section of your booking to see the last location shared during an active trip. Demo tracking does not calculate a live traffic arrival estimate. Use in-app chat for venue details. If your creator cannot attend, the booking shows replacement and refund choices.'],ta:['எனது படைப்பாளர் எங்கே இருக்கிறார்?','உங்கள் முன்பதிவில் பயணக் கண்காணிப்பைத் திறந்து கடைசியாகப் பகிரப்பட்ட இருப்பிடத்தைக் காணவும். சோதனைப் பதிப்பு போக்குவரத்து அடிப்படையிலான வருகை நேரத்தைக் கணிக்காது. இடம் பற்றிய விவரங்களுக்கு செயலியிலுள்ள அரட்டையைப் பயன்படுத்தவும். படைப்பாளர் வர முடியாவிட்டால் மாற்றுப் படைப்பாளர் மற்றும் பணத்தைத் திரும்பப் பெறுவதற்கான தேர்வுகள் காட்டப்படும்.']},
  {id:'gallery',en:['How do I download and share my photos?','Edited files appear after quality review. Preview images are watermarked. Final galleries allow individual files and a Download all ZIP. Create a six-digit PIN link and manage its expiry or revoke it at any time. Save your files before the gallery expiry date; reminders appear 30, 7 and 1 day before expiry.'],ta:['புகைப்படங்களைப் பதிவிறக்கி பகிர்வது எப்படி?','தரச் சரிபார்ப்பிற்குப் பிறகு திருத்தப்பட்ட கோப்புகள் கிடைக்கும். முன்னோட்டப் படங்களில் நீர்க்குறி இருக்கும். இறுதித் தொகுப்பைத் தனித்தனியாகவோ ZIP கோப்பாகவோ பதிவிறக்கலாம். ஆறு இலக்க PIN இணைப்பை உருவாக்கி அதன் காலாவதியை நிர்வகிக்கலாம் அல்லது ரத்து செய்யலாம். தொகுப்பு காலாவதியாகும் முன் கோப்புகளைச் சேமிக்கவும். 30, 7 மற்றும் 1 நாள் முன் நினைவூட்டல்கள் காட்டப்படும்.']},
  {id:'album',en:['How does album approval work?','Choose photos, size, paper, cover and copies, then put the pages in order. Low-resolution photos cannot be printed. Review each proof page and the price before approving. Follow production, shipping and delivery in your profile. For a damaged print, send support your album reference and a description so the team can review a reprint or refund.'],ta:['ஆல்பத்திற்கு ஒப்புதல் அளிப்பது எப்படி?','புகைப்படங்கள், அளவு, தாள், அட்டை மற்றும் பிரதிகளின் எண்ணிக்கையைத் தேர்ந்தெடுத்து பக்கங்களை வரிசைப்படுத்தவும். குறைந்த தெளிவுள்ள படங்களை அச்சிட முடியாது. ஒப்புதல் அளிக்கும் முன் ஒவ்வொரு மாதிரிப் பக்கத்தையும் விலையையும் சரிபார்க்கவும். தயாரிப்பு, அனுப்புதல் மற்றும் விநியோக நிலைகளை உங்கள் சுயவிவரத்தில் காணலாம். அச்சில் குறை இருந்தால் ஆல்பக் குறிப்பு எண்ணையும் விவரத்தையும் ஆதரவுக் குழுவிற்கு அனுப்பவும்.']},
  {id:'payment',en:['Are payments and refunds real in this demo?','No real money moves in demo mode. Payment history shows simulated payments, booking changes and refund status. Download a sample PDF statement from Payments & refunds in your profile. It is not a GST tax invoice. Real payment methods and refund timelines will depend on the connected payment provider at launch.'],ta:['சோதனைப் பதிப்பில் உண்மையான பணப் பரிவர்த்தனை நடக்குமா?','சோதனைப் பதிப்பில் உண்மையான பணம் பரிமாறப்படாது. கட்டண வரலாற்றில் மாதிரிக் கட்டணங்கள், முன்பதிவு மாற்றங்கள் மற்றும் பணத்தைத் திரும்பப் பெறும் நிலை காட்டப்படும். சுயவிவரத்தின் கட்டணப் பகுதியில் மாதிரி PDF அறிக்கையைப் பதிவிறக்கலாம். இது GST வரி விலைப்பட்டியல் அல்ல. உண்மையான கட்டண முறைகளும் பணத்தைத் திருப்பும் காலமும் வெளியீட்டின்போது இணைக்கப்படும் சேவை வழங்குநரைப் பொறுத்தது.']},
  {id:'privacy',en:['How do I manage my privacy?','Choose English or Tamil and update marketing, portfolio and guardian consent in your profile. Request a private export of your account data or account deletion. The team reviews deletion after active bookings are resolved. Financial and audit records follow retention requirements.'],ta:['எனது தனியுரிமையை நிர்வகிப்பது எப்படி?','சுயவிவரத்தில் தமிழ் அல்லது ஆங்கிலத்தைத் தேர்ந்தெடுத்து சந்தைப்படுத்தல், படைப்புத் தொகுப்பு மற்றும் பாதுகாவலர் ஒப்புதல்களை மாற்றலாம். உங்கள் கணக்குத் தரவுகளின் நகலைக் கோரவோ கணக்கை நீக்கக் கோரவோ முடியும். செயலில் உள்ள முன்பதிவுகள் முடிந்த பிறகு நீக்கக் கோரிக்கை பரிசீலிக்கப்படும். நிதி மற்றும் தணிக்கைப் பதிவுகள் பாதுகாப்பு விதிகளின்படி தக்கவைக்கப்படும்.']},
  {id:'upload',en:['When can I format my memory card?','Upload every file and check the verification receipt. In this demo the two stored copies are on the same machine, so the receipt always says to keep your original card. A demo verification is not permission to erase originals. Resume interrupted uploads from the upload screen.'],ta:['எனது மெமரி கார்டை எப்போது அழிக்கலாம்?','ஒவ்வொரு கோப்பையும் பதிவேற்றி சரிபார்ப்பு ரசீதைப் பார்க்கவும். இந்தச் சோதனைப் பதிப்பில் இரண்டு நகல்களும் ஒரே கணினியில் உள்ளதால் அசல் கார்டை வைத்திருக்குமாறு ரசீது தெரிவிக்கும். சோதனைச் சரிபார்ப்பு அசல் கோப்புகளை அழிப்பதற்கான அனுமதி அல்ல. தடைப்பட்ட பதிவேற்றங்களைப் பதிவேற்றத் திரையிலிருந்து தொடரலாம்.']}
] as const;

export function HelpCentre(){
  const {user}=useSession(),[language,setLanguage]=useState<'en'|'ta'>(user?.language==='ta'?'ta':'en'),[search,setSearch]=useState(''),[open,setOpen]=useState<string|null>(null);
  const tamil=language==='ta',matches=articles.filter(a=>[...a.en,...a.ta].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
  return <View style={{gap:16}}><Text style={styles.section}>{tamil?'உதவி மையம்':'Help centre'}</Text><Chips values={['en','ta'] as const} value={language} onChange={setLanguage}/><Field label={tamil?'உதவிக் கட்டுரைகளைத் தேடுங்கள்':'Search help articles'} value={search} onChangeText={setSearch}/>{matches.map(a=><Card key={a.id}><Pressable accessibilityRole="button" aria-expanded={open===a.id} onPress={()=>setOpen(open===a.id?null:a.id)}><Text style={styles.section}>{a[language][0]}</Text></Pressable>{open===a.id&&<Text style={styles.body}>{a[language][1]}</Text>}</Card>)}{!matches.length&&<Text style={styles.subtitle}>{tamil?'கட்டுரை கிடைக்கவில்லை. கீழே ஆதரவுக் கோரிக்கையை அனுப்பவும்.':'No articles found. Send a support request below.'}</Text>}</View>;
}
