import React,{useEffect,useState} from 'react';
import {Text,View} from 'react-native';
import {Button,Card,ErrorNotice,Field,styles} from './ui';
import {useSession,type PhoneChallenge} from '../services/session';
import {useAction} from '../services/use-load';
export function PhoneSignIn(){
 const {requestCode,verifyCode,demo}=useSession(),a=useAction(),[phone,setPhone]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState<PhoneChallenge|null>(null),[retryAt,setRetryAt]=useState(0),[now,setNow]=useState(Date.now());
 useEffect(()=>{if(!challenge)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[challenge]);
 const send=async()=>{const next=await requestCode(challenge?.phone??phone);setChallenge(next);setCode('');const now=Date.now();setNow(now);setRetryAt(now+next.retryAfterSeconds*1000);};
 const seconds=Math.max(0,Math.ceil((retryAt-now)/1000)),expired=challenge?Date.parse(challenge.expiresAt)<=now:false;
 return <Card><Text style={styles.section}>{challenge?'Enter your verification code':'Sign in with your phone'}</Text><ErrorNotice message={a.error}/>{!challenge?<><Field label="Mobile number" value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="+91 90000 00001"/><Field label="Your name (for a new account)" value={name} onChangeText={setName} autoCapitalize="words"/><Text style={styles.subtitle}>{demo?'Demo verification shows a test code here. No SMS is sent and phone ownership is not verified.':'We’ll send a six-digit verification code. Your number stays private.'}</Text><Button title={demo?'Get demo verification code':'Send verification code'} busy={a.busy} disabled={!/^(\+91)?[6-9]\d{9}$/.test(phone.replace(/[\s()-]/g,''))||(!!name&&name.trim().length<2)} onPress={()=>void a.run(send)}/></>:<><Text style={styles.subtitle}>For {challenge.phone}</Text>{challenge.demo&&challenge.demoCode&&<Text selectable style={styles.section}>Demo code · {challenge.demoCode}</Text>}<Field label="Six-digit verification code" value={code} onChangeText={value=>setCode(value.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6} autoComplete="one-time-code"/><Text style={styles.subtitle}>{expired?'This code has expired. Request a new one.':'The code expires in five minutes and can be used once.'}</Text><Button title="Verify and continue" busy={a.busy} disabled={code.length!==6||expired} onPress={()=>void a.run(()=>verifyCode(challenge.challengeId,code,name.trim()||undefined))}/><View style={{gap:8}}><Button title={seconds?`Resend code in ${seconds}s`:'Resend code'} secondary busy={a.busy} disabled={seconds>0} onPress={()=>void a.run(send)}/><Button title="Use a different number" secondary disabled={a.busy} onPress={()=>{setChallenge(null);setCode('');}}/></View></>}</Card>;
}
