import React,{useState} from 'react';
import {Switch,Text,View} from 'react-native';
import {formatMoney} from '@kamraw/domain';
import {Button,Card,ErrorNotice,styles} from './ui';
import {useSession} from '../services/session';
import {useAction,useLoad} from '../services/use-load';
import type {Gallery} from '../services/types';
import {GalleryAsset} from '../screens/customer';
interface PrintOrder {id:string;status:string;total_paise:number|null;proof_version:number;configuration:{size:string;paper:string;cover:string;copies:number;pages:{assetId:string}[]};gallery_id:string;tracking:{reference?:string};partner_reference:string|null}
export function PrintOrders(){const {api,demo}=useSession(),load=useLoad<PrintOrder[]>('/prints'),a=useAction(),[selected,setSelected]=useState<PrintOrder|null>(null),[gallery,setGallery]=useState<Gallery|null>(null),[approved,setApproved]=useState(false);return <Card><Text style={styles.section}>Albums made to hold</Text><ErrorNotice message={load.error??a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}{load.data?.map(p=><View key={p.id} style={{gap:10,paddingVertical:10}}><Text style={styles.body}>{p.configuration.size} · {p.configuration.pages.length} pages · {p.configuration.copies} copy/copies</Text><Text style={styles.subtitle}>{p.status.replaceAll('_',' ')}{p.total_paise?` · ${formatMoney(p.total_paise)}`:''}</Text>{p.tracking.reference&&<Text style={styles.label}>Demo tracking: {p.tracking.reference}</Text>}<Button title="View page-by-page proof" secondary busy={a.busy} onPress={()=>void a.run(async()=>{const fresh=await api<PrintOrder>(`/prints/${p.id}`);setGallery(await api(`/galleries/${p.gallery_id}`));setSelected(fresh);setApproved(false);})}/></View>)}{!load.data?.length&&<Text style={styles.subtitle}>Choose photos in a final gallery to start your first album.</Text>}{selected&&<Card><Text style={styles.section}>Your album proof</Text><Text style={styles.subtitle}>{selected.configuration.size} · {selected.configuration.paper} · {selected.configuration.cover} · version {selected.proof_version}</Text>{selected.configuration.pages.map((p,i)=>{const asset=gallery?.assets?.find(x=>x.id===p.assetId);return <View key={`${p.assetId}-${i}`} style={{gap:8}}><Text style={styles.label}>Page {i+1}</Text>{asset?<GalleryAsset asset={asset} square/>:<Text style={styles.error}>This page is no longer available.</Text>}</View>;})}{selected.status==='proof_ready'&&<><Text style={styles.body}>Total {formatMoney(selected.total_paise??0)} · illustrative price including tax and shipping</Text><View style={styles.row}><Switch accessibilityLabel="I reviewed every album page" value={approved} onValueChange={setApproved}/><Text style={[styles.body,{flex:1}]}>I reviewed every album page and approve this proof.</Text></View><Button title="Approve proof & pay in demo" disabled={!approved||!demo} busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/prints/${selected.id}/demo-approve`,{expectedTotalPaise:selected.total_paise,proofVersion:selected.proof_version});setSelected(null);await load.refresh();a.setSuccess('Proof approved. Payment and print production are simulated.');})}/></>}<Button title="Close proof" secondary onPress={()=>setSelected(null)}/></Card>}<Button title="Refresh album orders" secondary onPress={()=>void load.refresh()}/></Card>;}
