import React,{useState} from 'react';
import {Text,View} from 'react-native';
import {formatMoney} from '@kamraw/domain';
import {Button,Card,ErrorNotice,Field,styles} from './ui';
import {useSession} from '../services/session';
import {useAction,useLoad} from '../services/use-load';
export function CreatorCancellation({roleId,onCancelled}:{roleId:string;onCancelled:()=>void}){const {api}=useSession(),a=useAction(),[reason,setReason]=useState(''),[preview,setPreview]=useState<{penaltyPaise:number;strike:string;noShow:boolean}|null>(null);return <Card><Text style={styles.section}>Unable to make this shoot?</Text><Text style={styles.subtitle}>Let us know early so another creator can cover it. Review the demo penalty before confirming.</Text><Field label="Cancellation reason" value={reason} onChangeText={setReason} multiline/><ErrorNotice message={a.error}/><Button title="Review creator cancellation" secondary busy={a.busy} onPress={()=>void a.run(async()=>setPreview(await api(`/creator/roles/${roleId}/cancellation`)))}/>{preview&&<View style={{gap:12}}><Text style={styles.body}>Penalty: {formatMoney(preview.penaltyPaise)} · {preview.strike} strike</Text><Text style={styles.subtitle}>{preview.noShow?'This is within two hours of the shoot and counts as a no-show. The customer can choose a replacement or a full refund plus 20% demo credit.':'We will find a replacement. Penalties are deducted from eligible future demo payouts.'}</Text><Button title="Confirm creator cancellation" busy={a.busy} disabled={reason.trim().length<5} onPress={()=>void a.run(async()=>{await api(`/creator/roles/${roleId}/cancel`,{reason,expectedPenaltyPaise:preview.penaltyPaise});onCancelled();})}/></View>}</Card>;}
export function CustomerRecovery({sessionId,onUpdated}:{sessionId:string;onUpdated:()=>Promise<void>}){const {api}=useSession(),load=useLoad<{id:string;kind:string;status:string;credit_paise:number}[]>(`/sessions/${sessionId}/recovery`),a=useAction(),[refund,setRefund]=useState<{feePaise:number;refundPaise:number;creditPaise:number}|null>(null);const pending=load.data?.filter(f=>f.status==='pending');if(!pending?.length)return null;return <Card><Text style={styles.section}>Let’s put this right.</Text><Text style={styles.subtitle}>Your booking needs attention. Matching is underway. You can keep waiting or review a refund without a cancellation fee. Contact support to change tier or date.</Text><ErrorNotice message={load.error??a.error}/><Button title="Keep matching my creator" busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/sessions/${sessionId}/replacement`,{});await load.refresh();await onUpdated();})}/><Button title="Review full refund" secondary onPress={()=>void a.run(async()=>setRefund(await api(`/sessions/${sessionId}/cancellation`)))}/>{refund&&<View style={{gap:12}}><Text style={styles.body}>Refund {formatMoney(refund.refundPaise)} · fee {formatMoney(refund.feePaise)}</Text>{refund.creditPaise>0&&<Text style={styles.body}>Additional demo credit {formatMoney(refund.creditPaise)}</Text>}<Button title="Confirm refund and cancel" busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/sessions/${sessionId}/cancel`,{expectedFeePaise:refund.feePaise});setRefund(null);await load.refresh();await onUpdated();})}/></View>}</Card>;}
export function Credits(){const load=useLoad<{id:string;amount_paise:number;balance_paise:number;reference:string;created_at:string;expires_at:string|null}[]>('/credits');if(!load.data?.length)return null;return <Card><Text style={styles.section}>Kamraw credits</Text><Text style={styles.subtitle}>Apply available credits when reviewing a booking. Demo credits have no cash value and no expiry unless shown below.</Text>{load.data.map(c=><View key={c.id} style={{gap:8}}><Text style={styles.body}>{formatMoney(c.balance_paise)}</Text><Text style={styles.label}>{new Date(c.created_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})} · {c.expires_at?`Expires ${new Date(c.expires_at).toLocaleDateString('en-IN')}`:'No expiry in demo'}</Text></View>)}</Card>;}
export function CancellationHistory(){const load=useLoad<{id:string;code:string;strike:string;penalty_paise:number;reason:string}[]>('/creator/cancellations');return <Card><Text style={styles.section}>Cancellation record</Text><ErrorNotice message={load.error}/>{load.data?.map(c=><View key={c.id} style={{gap:8}}><Text style={styles.body}>{c.code} · {formatMoney(c.penalty_paise)}</Text><Text style={styles.subtitle}>{c.strike} strike · {c.reason}</Text></View>)}{!load.data?.length&&<Text style={styles.subtitle}>No cancellations recorded.</Text>}</Card>;}
