import React,{useState} from 'react';
import {Text} from 'react-native';
import {formatMoney} from '@kamraw/domain';
import {Button,Card,ErrorNotice,Field,styles} from './ui';
import {useSession} from '../services/session';
import {useAction,useLoad} from '../services/use-load';
interface Change {id:string;kind:string;status:string;delta_paise:number;expires_at:string;data:{input:{start:string;hours:number}};responses:{roleId:string;accepted:boolean}[]}
export function SessionChanges({sessionId,status,creator=false,onUpdated}:{sessionId:string;status:string;creator?:boolean;onUpdated?:()=>Promise<void>}){
 const {api,demo}=useSession(),load=useLoad<Change[]>(`/sessions/${sessionId}/changes`),a=useAction(),[start,setStart]=useState(''),[blocks,setBlocks]=useState('1');
 const refresh=async()=>{await load.refresh();await onUpdated?.();};
 return <Card><Text style={styles.section}>{creator?'Extension requests':'Change your shoot'}</Text><ErrorNotice message={load.error??a.error}/>{a.success&&<Text style={styles.success}>{a.success}</Text>}
 {!creator&&['confirmed','assigned','reconfirmed'].includes(status)&&<><Text style={styles.subtitle}>One free reschedule more than 72 hours before your shoot. Any price difference is shown before you confirm. Creators will be matched again.</Text><Field label="New date and time (India)" placeholder="YYYY-MM-DD HH:mm" value={start} onChangeText={setStart}/><Button title="Review reschedule" secondary busy={a.busy} onPress={()=>void a.run(async()=>{if(!/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/.test(start))throw new Error('Use YYYY-MM-DD HH:mm');const d=new Date(start.replace(' ','T')+':00+05:30');if(isNaN(d.getTime()))throw new Error('Enter a valid date');await api(`/sessions/${sessionId}/changes`,{kind:'reschedule',start:d.toISOString()});await load.refresh();})}/></>}
 {!creator&&status==='in_session'&&<><Text style={styles.subtitle}>Add time in 30-minute blocks. Every creator must accept before payment. Your booked end time changes only after confirmation.</Text><Field label="30-minute blocks (1–4)" keyboardType="number-pad" value={blocks} onChangeText={setBlocks}/><Button title="Request extra time" secondary busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/sessions/${sessionId}/changes`,{kind:'extension',blocks:Number(blocks)});await load.refresh();})}/></>}
 {load.data?.filter(c=>creator?c.kind==='extension'&&c.status==='pending':true).map(c=><Card key={c.id}><Text style={styles.label}>{c.kind} · {c.status}</Text><Text style={styles.body}>{new Date(c.data.input.start).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} · {c.data.input.hours} hours</Text><Text style={styles.body}>{c.delta_paise>=0?'Additional payment':'Refund'}: {formatMoney(Math.abs(c.delta_paise))}</Text>{c.status==='pending'&&<><Text style={styles.subtitle}>Review expires {new Date(c.expires_at).toLocaleTimeString()}. {c.kind==='extension'?`${c.responses.filter(r=>r.accepted).length} creator approval(s).`:''}</Text>{creator?<><Button title="Accept extension" busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/changes/${c.id}/respond`,{accepted:true});a.setSuccess('Accepted. Wait for customer payment before extending the shoot.');await refresh();})}/><Button title="Decline extension" secondary busy={a.busy} onPress={()=>void a.run(async()=>{await api(`/changes/${c.id}/respond`,{accepted:false});await refresh();})}/></>:<><Button title={demo?'Confirm with demo payment':'Confirm change'} busy={a.busy} disabled={!demo} onPress={()=>void a.run(async()=>{await api(`/changes/${c.id}/demo-apply`,{expectedDeltaPaise:c.delta_paise});a.setSuccess('Change confirmed. Payment or refund was simulated.');await refresh();})}/><Button title="Keep current booking" secondary onPress={()=>void a.run(async()=>{await api(`/changes/${c.id}/dismiss`,{});await load.refresh();})}/></>}</>}</Card>)}<Button title="Refresh changes" secondary onPress={()=>void refresh()}/></Card>;
}
