import React from 'react';
import {ActivityIndicator,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View,type TextInputProps,type ViewStyle} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
export const color={ink:'#242322',muted:'#72706B',paper:'#F6F3ED',white:'#FFFEFA',red:'#B83E31',line:'#E5DED3',green:'#386450',soft:'#F1DDD5'};
export const styles=StyleSheet.create({page:{flex:1,backgroundColor:color.paper},content:{padding:22,gap:20,paddingBottom:36},title:{fontSize:34,fontWeight:'700',letterSpacing:-1.2,color:color.ink},subtitle:{fontSize:15,lineHeight:23,color:color.muted},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:2,color:color.red,textTransform:'uppercase'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},card:{backgroundColor:color.white,borderWidth:1,borderColor:color.line,borderRadius:20,padding:20,gap:12},section:{fontSize:21,fontWeight:'600',color:color.ink,letterSpacing:-.5},body:{fontSize:15,lineHeight:22,color:color.ink},label:{fontSize:12,fontWeight:'600',color:color.muted},input:{borderWidth:1,borderColor:color.line,borderRadius:12,paddingHorizontal:14,paddingVertical:14,backgroundColor:color.white,color:color.ink,fontSize:16,minHeight:48},button:{backgroundColor:color.red,borderRadius:14,minHeight:52,padding:15,alignItems:'center',justifyContent:'center'},buttonText:{color:color.white,fontSize:15,fontWeight:'700'},chip:{borderWidth:1,borderColor:color.line,borderRadius:100,paddingHorizontal:16,paddingVertical:13,minHeight:44,backgroundColor:color.white},error:{padding:14,borderRadius:12,backgroundColor:'#FCE8E1',color:'#802D24',lineHeight:22},success:{padding:14,borderRadius:12,backgroundColor:'#E5EFE7',color:color.green,lineHeight:22}});
export function Page({children,scroll=true}:{children:React.ReactNode;scroll?:boolean}){return <SafeAreaView edges={['left','right']} style={styles.page}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}>{children}</ScrollView>:children}</KeyboardAvoidingView></SafeAreaView>;}
export const Card=({children,style}:{children:React.ReactNode;style?:ViewStyle})=><View style={[styles.card,style]}>{children}</View>;
export function Button({title,onPress,busy=false,secondary=false,disabled=false}:{title:string;onPress:()=>void;busy?:boolean;secondary?:boolean;disabled?:boolean}){return <Pressable role="button" accessibilityLabel={title} aria-disabled={disabled||busy} aria-busy={busy} disabled={disabled||busy} onPress={onPress} style={({pressed})=>[styles.button,secondary&&{backgroundColor:color.white,borderWidth:1,borderColor:color.line},(disabled||busy)&&{opacity:.5},pressed&&{opacity:.8}]}>{busy?<ActivityIndicator color={secondary?color.red:color.white}/>:<Text style={[styles.buttonText,secondary&&{color:color.ink}]}>{title}</Text>}</Pressable>;}
export const Field=({label,...props}:TextInputProps&{label:string})=><View style={{gap:8}}><Text style={styles.label}>{label}</Text><TextInput {...props} accessibilityLabel={label} placeholderTextColor={color.muted} style={[styles.input,props.multiline&&{minHeight:92,textAlignVertical:'top'},props.style]}/></View>;
export function Chips<T extends string>({values,value,onChange,labels}:{values:readonly T[];value:T;onChange:(v:T)=>void;labels?:Partial<Record<T,string>>}){return <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{values.map(v=><Pressable key={v} role="radio" aria-checked={v===value} accessibilityLabel={labels?.[v]??v} onPress={()=>onChange(v)} style={[styles.chip,v===value&&{backgroundColor:color.ink,borderColor:color.ink}]}><Text style={{color:v===value?color.white:color.ink,fontSize:14,textTransform:'capitalize'}}>{labels?.[v]??v.replaceAll('_',' ')}</Text></Pressable>)}</View>;}
export const ErrorNotice=({message}:{message:string|null})=>message?<Text role="alert" style={styles.error}>{message}</Text>:null;
export const Empty=({title,body}:{title:string;body:string})=><Card><Text style={styles.section}>{title}</Text><Text style={styles.subtitle}>{body}</Text></Card>;
