import request from 'supertest';
import sharp from 'sharp';
import {PDFDocument} from 'pdf-lib';
import {Client} from 'pg';
import {drainDemoOutbox} from '../src/services/demo-providers';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createApp} from '../src/app';
import {createDataSource} from '../src/db/data-source';
import {seedDemo} from '../src/db/seed';
import {PlatformRepository} from '../src/repositories/platform';
import {PrivacyService} from '../src/services/privacy';
import {RetentionService} from '../src/services/retention';
import {PrintService} from '../src/services/prints';
import {RecoveryService} from '../src/services/recovery';
import {SessionChangeService} from '../src/services/session-changes';
import {BookingService} from '../src/services/bookings';
import {DispatchService} from '../src/services/dispatch';
import {availableCredits} from '../src/services/credits';
import {ServiceReminders} from '../src/services/service-reminders';
import {SessionService} from '../src/services/sessions';
import {MediaService} from '../src/services/media';
import {OperationsService} from '../src/services/operations';
import {AccountEntity,CreatorEntity,RoleEntity,SessionEntity} from '../src/entities';
import type {Env} from '../src/config/env';
import type {BookingInput} from '@kamraw/domain';
const url=process.env.TEST_DATABASE_URL;
const suite=url?describe:describe.skip;
suite('PostgreSQL platform integration',()=>{
 const dbName=`kamraw_test_${randomUUID().replaceAll('-','')}`,isolatedUrl=new URL(url??'postgresql://localhost/postgres');isolatedUrl.pathname=dbName;const db=createDataSource(isolatedUrl.toString());let repo:PlatformRepository,booking:BookingService,dispatch:DispatchService,media:MediaService,ops:OperationsService,app:ReturnType<typeof createApp>,root:string,customer:string,creatorAccount:string,opsId:string,approver:string;
 beforeAll(async()=>{const admin=new Client({connectionString:url});await admin.connect();try{await admin.query(`CREATE DATABASE ${dbName}`);}finally{await admin.end();}await db.initialize();await db.runMigrations();await seedDemo(db);root=await mkdtemp(path.join(os.tmpdir(),'kamraw-media-'));repo=new PlatformRepository(db);booking=new BookingService(repo);dispatch=new DispatchService(repo);media=new MediaService(repo,root,true);ops=new OperationsService(repo,true);customer=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:customer'})).id;creatorAccount=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:creator'})).id;opsId=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:ops'})).id;approver=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:approver'})).id;app=createApp(db,{APP_MODE:'demo',NODE_ENV:'test',DATABASE_URL:url!,DATABASE_SSL:'false',WEB_ORIGIN:'http://localhost:5173',PUBLIC_API_URL:'http://localhost:4000',MEDIA_ROOT:root,PORT:4000,STAFF_ROLES_CLAIM:'roles'} as Env);});
 afterAll(async()=>{await db.destroy();if(root)await rm(root,{recursive:true,force:true});const admin=new Client({connectionString:url});await admin.connect();try{await admin.query(`DROP DATABASE IF EXISTS ${dbName}`);}finally{await admin.end();}});
 const startFor=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);d.setUTCHours(6,0,0,0);return d.toISOString();};
 const input=(days:number):BookingInput=>({category:'birthday',termsVersion:'demo-v1',sessions:[{start:startFor(days),mode:'scheduled',hours:2,venue:{lat:13.0827,lng:80.2707,address:'Demo venue, Chennai',type:'hall',contactName:'Host',contactPhone:'+919876543210',notes:''},roles:[{discipline:'photo',tier:'T1',count:1}],style:'candid',preferences:{femaleCreator:false},addons:[],notes:''}]});
 async function paid(days:number){const q=await booking.quote(customer,input(days));const o=await booking.checkout(customer,q.id);await booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise,currency:'INR',provider:'test'});const sessions=await db.getRepository(SessionEntity).findBy({orderId:o.id});const role=await db.getRepository(RoleEntity).findOneByOrFail({sessionId:sessions[0]!.id});return {order:o,session:sessions[0]!,role};}
 test('health is real and unauthenticated protected routes are denied',async()=>{expect((await request(app).get('/ready')).status).toBe(200);expect((await request(app).get('/api/orders')).status).toBe(401);expect((await request(app).get('/api/ops/finance').auth('demo:customer',{type:'bearer'})).status).toBe(403);expect((await request(app).get('/api/ops/privacy').auth('demo:finance',{type:'bearer'})).status).toBe(403);expect((await request(app).get('/api/ops/configurations').auth('demo:approver',{type:'bearer'})).status).toBe(200);});
 test('invalid payload and inaccessible order fail safely',async()=>{expect((await request(app).post('/api/quotes').auth('demo:customer',{type:'bearer'}).send({})).status).toBe(422);const {order}=await paid(10);expect((await request(app).get(`/api/orders/${order.id}`).auth('demo:creator',{type:'bearer'})).status).toBe(404);});
 test('checkout and verified payment are idempotent and ledger balances',async()=>{const q=await booking.quote(customer,input(11));const [a,b]=await Promise.all([booking.checkout(customer,q.id),booking.checkout(customer,q.id)]);expect(a.id).toBe(b.id);const e={id:randomUUID(),orderId:a.id,amountPaise:a.totalPaise,currency:'INR',provider:'test'};await Promise.all([booking.confirmPayment(e),booking.confirmPayment(e)]);const [r]=await db.query('SELECT count(*)::int AS count FROM payment_events WHERE order_id=$1',[a.id]);expect(r.count).toBe(1);const [sum]=await db.query('SELECT sum(e.amount_paise)::int AS total FROM ledger_entries e JOIN ledger_transactions t ON t.id=e.transaction_id WHERE t.order_id=$1',[a.id]);expect(sum.total).toBe(0);});
 test('mismatched amount cannot confirm a booking',async()=>{const q=await booking.quote(customer,input(12));const o=await booking.checkout(customer,q.id);await expect(booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:1,currency:'INR',provider:'test'})).rejects.toMatchObject({code:'PAYMENT_MISMATCH'});expect((await repo.order(o.id)).status).toBe('payment_pending');});
 test('payment statements are private and include simulated refunds',async()=>{const x=await paid(80);await booking.cancel(customer,x.session.id,0);await drainDemoOutbox(repo);const privatePath=`/api/orders/${x.order.id}`;expect((await request(app).get(`${privatePath}/statement`).auth('demo:creator',{type:'bearer'})).status).toBe(404);const detail=await request(app).get(`${privatePath}/payment-record`).auth('demo:customer',{type:'bearer'});expect(detail.status).toBe(200);expect(detail.body.data.refunds[0].status).toBe('simulated_refunded');const response=await request(app).get(`${privatePath}/statement`).auth('demo:customer',{type:'bearer'});expect(response.status).toBe(200);const pdf=await PDFDocument.load(Buffer.from(response.body.data.base64,'base64'));expect(pdf.getTitle()).toContain('demo statement');expect(pdf.getPageCount()).toBe(1);const history=await request(app).get('/api/payment-records').auth('demo:customer',{type:'bearer'});expect(history.body.data.orders.find((o:{id:string})=>o.id===x.order.id).refund_paise).toBe(x.order.totalPaise);});
 test('first acceptance wins under concurrent requests',async()=>{const x=await paid(13);await db.query("UPDATE sessions SET input=jsonb_set(input,'{mode}','\"on_demand\"') WHERE id=$1",[x.session.id]);const offers=await dispatch.dispatch(x.role.id);expect(offers.length).toBe(3);const identities=await Promise.all(offers.slice(0,2).map(async o=>(await db.getRepository(CreatorEntity).findOneByOrFail({id:o.creatorId})).accountId));const results=await Promise.allSettled(offers.slice(0,2).map((o,i)=>dispatch.accept(identities[i]!,o.id)));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await db.getRepository(RoleEntity).countBy({sessionId:x.session.id,status:'assigned'})).toBe(1);});
 test('database prevents overlapping assignments even outside dispatch',async()=>{const a=await paid(14),b=await paid(14);const c=await repo.creator(creatorAccount);await db.getRepository(RoleEntity).update(a.role.id,{creatorId:c.id,status:'assigned'});await expect(db.getRepository(RoleEntity).update(b.role.id,{creatorId:c.id,status:'assigned'})).rejects.toMatchObject({code:'23P01'});});
 test('check-in geofence, completion code, verified uploads and maker checker',async()=>{
   const x=await paid(15),offers=await dispatch.dispatch(x.role.id);const c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const svc=new SessionService(repo,true);const now=new Date(x.session.startAt);const e=(action:string,extra:object={})=>({action,clientId:randomUUID(),deviceAt:now.toISOString(),location:{lat:13.0827,lng:80.2707,accuracy:5},...extra});
   await svc.transition(c.accountId,x.role.id,e('trip'),now);await expect(svc.transition(c.accountId,x.role.id,e('check_in',{identityProof:'demo-selfie',location:{lat:12,lng:79,accuracy:5}}),now)).rejects.toMatchObject({code:'OUTSIDE_GEOFENCE'});
   const check=e('check_in',{identityProof:'demo-selfie'});await svc.transition(c.accountId,x.role.id,check,now);await expect(svc.transition(c.accountId,x.role.id,check,now)).resolves.toMatchObject({synced:true});await svc.transition(c.accountId,x.role.id,e('start'),now);await expect(svc.transition(c.accountId,x.role.id,e('complete',{completionCode:'000000'}),now)).rejects.toMatchObject({code:'INVALID_CODE'});
   const s=await db.getRepository(SessionEntity).createQueryBuilder('s').addSelect('s.completionCode').where('s.id=:id',{id:x.session.id}).getOneOrFail();await svc.transition(c.accountId,x.role.id,e('complete',{completionCode:s.completionCode}),now);
   const discarded=await media.manifest(c.accountId,{sessionId:x.session.id,files:[{filename:'discard.jpg',bytes:3,checksum:createHash('sha256').update('bad').digest('hex'),kind:'edited'}]});await media.abandon(c.accountId,discarded.id);await expect(media.chunk(c.accountId,discarded.assets[0].id,0,Buffer.from('bad'))).rejects.toMatchObject({code:'DISCARDED'});
   const bytes=await sharp({create:{width:4000,height:4000,channels:3,background:'#bd7055'}}).jpeg().toBuffer(),hash=createHash('sha256').update(bytes).digest('hex');const upload=await media.manifest(c.accountId,{sessionId:x.session.id,files:[{filename:'test.jpg',bytes:bytes.length,checksum:hash,kind:'edited'}]});const asset=upload.assets[0];await media.chunk(c.accountId,asset.id,0,bytes.subarray(0,5));expect((await media.receipt(c.accountId,upload.id)).demoVerified).toBe(false);await expect(media.chunk(c.accountId,asset.id,0,bytes)).rejects.toMatchObject({code:'OFFSET_MISMATCH'});await media.chunk(c.accountId,asset.id,5,bytes.subarray(5));const receipt=await media.receipt(c.accountId,upload.id);expect(receipt.demoVerified).toBe(true);expect(receipt.safeToFormat).toBe(false);
   await ops.reviewAsset(opsId,asset.id,{status:'approved',reason:'Test output reviewed',width:4000,height:4000});const [gallery]=await db.query('SELECT id FROM galleries WHERE order_id=$1',[x.order.id]);await ops.publish(opsId,gallery.id,{stage:'preview_ready',reason:'Preview review complete'});const previewTicket=await media.ownerTicket(customer,asset.id);const preview=await media.authorizedFile(asset.id,previewTicket.ticket,false);expect((await sharp(preview.filename).metadata()).width).toBeLessThanOrEqual(1400);const qcTicket=await media.reviewTicket(opsId,asset.id);const original=await media.authorizedFile(asset.id,qcTicket.ticket,false);expect((await sharp(original.filename).metadata()).width).toBe(4000);await expect(ops.reviewAsset(opsId,asset.id,{status:'approved',reason:'Wrong size rejected',width:100,height:100})).rejects.toMatchObject({code:'DIMENSIONS_MISMATCH'});await ops.publish(opsId,gallery.id,{stage:'final_ready',reason:'Final review complete'});const freshTicket=await media.ownerTicket(customer,asset.id);expect((await request(app).get(`/api/media/${asset.id}?ticket=${freshTicket.ticket}`)).headers['content-type']).toMatch(/image\/jpeg/);await media.receipt(c.accountId,upload.id);expect((await repo.session(x.session.id)).status).toBe('final_delivered');
   const bundle=await media.archiveTicket(customer,gallery.id);await expect(media.archiveTicket(creatorAccount,gallery.id)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(media.archive(randomUUID(),bundle.ticket)).rejects.toMatchObject({code:'INVALID_TICKET'});await expect(media.archive(gallery.id,freshTicket.ticket)).rejects.toMatchObject({code:'INVALID_TICKET'});
   const parts:Buffer[]=[];for await(const chunk of await media.archive(gallery.id,bundle.ticket))parts.push(Buffer.from(chunk));const zip=Buffer.concat(parts);expect(zip.subarray(0,2).toString()).toBe('PK');expect(zip.includes(bytes)).toBe(true);expect(zip.includes(Buffer.from(`${asset.id}-test.jpg`))).toBe(true);expect(zip.includes(Buffer.from('discard.jpg'))).toBe(false);
   await db.query("UPDATE galleries SET expires_at=now()-interval '1 minute' WHERE id=$1",[gallery.id]);await expect(media.archive(gallery.id,bundle.ticket)).rejects.toMatchObject({code:'NOT_FOUND'});await db.query("UPDATE galleries SET expires_at=now()+interval '1 year' WHERE id=$1",[gallery.id]);
   const link=await media.share(customer,gallery.id,{kind:'pin',pin:'123456',expiresAt:new Date(Date.now()+86400000).toISOString(),allowDownload:false});await expect(media.shared(link.token,'000000')).rejects.toMatchObject({code:'PIN_REQUIRED'});expect((await media.shared(link.token,'123456')).assets).toHaveLength(1);const tickets=await media.sharedTickets(link.token,'123456');const ticket=tickets.assets[0]!.ticket;await expect(media.authorizedFile(asset.id,ticket,false)).resolves.toHaveProperty('filename');await expect(media.authorizedFile(asset.id,ticket,true)).rejects.toMatchObject({code:'EXPIRED_TICKET'});await expect(media.authorizedFile(randomUUID(),ticket,false)).rejects.toMatchObject({code:'EXPIRED_TICKET'});await db.query('UPDATE shares SET revoked_at=now() WHERE id=$1',[link.id]);await expect(media.authorizedFile(asset.id,ticket,false)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(media.shared(link.token,'123456')).rejects.toMatchObject({code:'NOT_FOUND'});
   const run=await ops.generatePayout(opsId);await expect(ops.approvePayout(opsId,run.id)).rejects.toMatchObject({code:'MAKER_CHECKER'});await expect(ops.approvePayout(approver,run.id)).resolves.toMatchObject({approved:true});
 });
 test('cancellation fees cannot change silently and cancellation is idempotent',async()=>{const x=await paid(16);const preview=await booking.cancelPreview(customer,x.session.id);await expect(booking.cancel(customer,x.session.id,preview.feePaise+1)).rejects.toMatchObject({code:'FEE_CHANGED'});const a=await booking.cancel(customer,x.session.id,preview.feePaise);const b=await booking.cancel(customer,x.session.id,preview.feePaise);expect(a.id).toBe(b.id);});
 test('demo settlements are explicitly labelled and idempotent',async()=>{await drainDemoOutbox(repo);await drainDemoOutbox(repo);const [r]=await db.query("SELECT count(*)::int AS n FROM payout_runs WHERE status='simulated_paid'");expect(r.n).toBe(1);const [refunds]=await db.query("SELECT count(*)::int AS n FROM refunds WHERE status='simulated_refunded'");expect(refunds.n).toBe(2);const [ledger]=await db.query("SELECT count(*)::int AS n FROM ledger_transactions WHERE reference LIKE 'demo-payout:%'");expect(ledger.n).toBe(1);});
 test('reschedule is once-only, resets dispatch, preserves ownership and applies payment once',async()=>{
   const x=await paid(30),svc=new SessionChangeService(repo);const offers=await dispatch.dispatch(x.role.id);const c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);
   await expect(svc.request(creatorAccount,x.session.id,{kind:'reschedule',start:startFor(31)})).rejects.toMatchObject({code:'NOT_FOUND'});
   const change=await svc.request(customer,x.session.id,{kind:'reschedule',start:startFor(31)});
   await expect(svc.applyDemo(customer,change.id,change.delta_paise+1)).rejects.toMatchObject({code:'PRICE_CHANGED'});
   await Promise.all([svc.applyDemo(customer,change.id,change.delta_paise),svc.applyDemo(customer,change.id,change.delta_paise)]);
   expect((await repo.session(x.session.id)).startAt.toISOString()).toBe(startFor(31));expect((await repo.session(x.session.id)).status).toBe('confirmed');expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).status).toBe('cancelled');
   const roles=await db.getRepository(RoleEntity).findBy({sessionId:x.session.id,status:'confirmed'});expect(roles).toHaveLength(1);expect(roles[0]!.creatorId).toBeNull();await expect(repo.authorizedSession(x.session.id,c.accountId)).rejects.toMatchObject({code:'NOT_FOUND'});expect((await dispatch.dispatch(roles[0]!.id)).length).toBeGreaterThan(0);
   await expect(svc.request(customer,x.session.id,{kind:'reschedule',start:startFor(32)})).rejects.toMatchObject({code:'RESCHEDULE_USED'});
   const close=await paid(1);await expect(svc.request(customer,close.session.id,{kind:'reschedule',start:startFor(35)})).rejects.toMatchObject({code:'RESCHEDULE_WINDOW'});
 });
 test('extension needs creator consent, conflict recheck and idempotent payment before changing time',async()=>{
   const x=await paid(40),svc=new SessionChangeService(repo),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);
   await db.getRepository(SessionEntity).update(x.session.id,{status:'in_session'});await db.getRepository(RoleEntity).update(x.role.id,{status:'in_session'});const now=new Date(x.session.endAt.getTime()-20*60000);
   const change=await svc.request(customer,x.session.id,{kind:'extension',blocks:1},now);
   await expect(svc.applyDemo(customer,change.id,change.delta_paise,now)).rejects.toMatchObject({code:'AWAITING_CREATORS'});
   await expect(svc.respond(customer,change.id,true,now)).rejects.toMatchObject({code:'NOT_FOUND'});await svc.respond(c.accountId,change.id,true,now);
   const [block]=await db.query('INSERT INTO availability(creator_id,start_at,end_at,available) VALUES($1,$2,$3,false) RETURNING id',[c.id,new Date(x.session.endAt.getTime()+35*60000),new Date(x.session.endAt.getTime()+90*60000)]);
   await expect(svc.applyDemo(customer,change.id,change.delta_paise,now)).rejects.toMatchObject({code:'EXTENSION_CONFLICT'});expect((await repo.session(x.session.id)).endAt).toEqual(x.session.endAt);await db.query('DELETE FROM availability WHERE id=$1',[block.id]);
   await Promise.all([svc.applyDemo(customer,change.id,change.delta_paise,now),svc.applyDemo(customer,change.id,change.delta_paise,now)]);
   expect((await repo.session(x.session.id)).endAt.getTime()).toBe(x.session.endAt.getTime()+30*60000);expect((await repo.order(x.order.id)).totalPaise).toBe(x.order.totalPaise+change.delta_paise);const [paidOnce]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-change:${change.id}`]);expect(paidOnce.n).toBe(1);
   const declined=await svc.request(customer,x.session.id,{kind:'extension',blocks:1},now);await svc.respond(c.accountId,declined.id,false,now);await expect(svc.applyDemo(customer,declined.id,declined.delta_paise,now)).rejects.toMatchObject({code:'CHANGE_UNAVAILABLE'});
 });
 test('notifications are private and delivered once, and support replies stay with their owner',async()=>{
   await drainDemoOutbox(repo);const first=await request(app).get('/api/notifications').auth('demo:customer',{type:'bearer'});expect(first.status).toBe(200);expect(first.body.data.length).toBeGreaterThan(0);const n=first.body.data[0];await drainDemoOutbox(repo);const again=await request(app).get('/api/notifications').auth('demo:customer',{type:'bearer'});expect(again.body.data.filter((x:{id:string})=>x.id===n.id)).toHaveLength(1);
   expect((await request(app).post(`/api/notifications/${n.id}/read`).auth('demo:creator',{type:'bearer'}).send({})).status).toBe(404);expect((await request(app).post(`/api/notifications/${n.id}/read`).auth('demo:customer',{type:'bearer'}).send({})).status).toBe(200);
   const ticket=await request(app).post('/api/tickets').auth('demo:customer',{type:'bearer'}).send({category:'booking',subject:'Question about my shoot',body:'Please confirm the preparation checklist.'});const ticketId=ticket.body.data.id;
   expect((await request(app).get(`/api/tickets/${ticketId}/messages`).auth('demo:creator',{type:'bearer'})).status).toBe(404);expect((await request(app).post(`/api/ops/tickets/${ticketId}/messages`).auth('demo:ops',{type:'bearer'}).send({body:'Your preparation checklist is in the shoot brief.'})).status).toBe(200);const replies=await request(app).get(`/api/tickets/${ticketId}/messages`).auth('demo:customer',{type:'bearer'});expect(replies.body.data).toHaveLength(1);
 });
 test('creator no-show releases the role, refunds without fee, issues one credit and nets penalties from payout',async()=>{
   const x=await paid(45),svc=new RecoveryService(repo),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const now=new Date(x.session.startAt.getTime()-3600000),preview=await svc.preview(c.accountId,x.role.id,now);expect(preview.noShow).toBe(true);
   await expect(svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise+1},now)).rejects.toMatchObject({code:'PENALTY_CHANGED'});
   await Promise.all([svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise},now),svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise},now)]);
   expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBeNull();const replacements=await dispatch.dispatch(x.role.id,now);expect(replacements.length).toBeGreaterThan(0);expect(replacements.some(o=>o.creatorId===c.id)).toBe(false);
   const refund=await booking.cancelPreview(customer,x.session.id,now);expect(refund.feePaise).toBe(0);expect(refund.creditPaise).toBe(Math.round(x.session.totalPaise*.2));await booking.cancel(customer,x.session.id,0,now);await booking.cancel(customer,x.session.id,0,now);const [credits]=await db.query('SELECT count(*)::int AS n FROM customer_credits WHERE session_id=$1',[x.session.id]);expect(credits.n).toBe(1);
   const earned=await paid(46);await db.getRepository(RoleEntity).update(earned.role.id,{creatorId:c.id,status:'media_verified'});const run=await ops.generatePayout(opsId);expect(run.total_paise).toBe(earned.role.earningPaise-preview.penaltyPaise);await ops.approvePayout(approver,run.id);await drainDemoOutbox(repo);await drainDemoOutbox(repo);const [balance]=await db.query("SELECT sum(amount_paise)::int AS total FROM ledger_entries WHERE account='creator_penalty_receivable'");expect(balance.total).toBe(0);
 });
 test('manual dispatch enforces qualification and still requires creator acceptance',async()=>{
   const x=await paid(50),candidates=await dispatch.manualCandidates(x.role.id);expect(candidates.length).toBeGreaterThan(1);
   expect((await request(app).get('/api/ops/dispatch').auth('demo:customer',{type:'bearer'})).status).toBe(403);
   const first=await dispatch.manualOffer(opsId,x.role.id,{creatorId:candidates[0]!.id,reason:'Manual coverage review'});const second=await dispatch.manualOffer(opsId,x.role.id,{creatorId:candidates[1]!.id,reason:'Choose available backup'});const c1=await db.getRepository(CreatorEntity).findOneByOrFail({id:first.creatorId}),c2=await db.getRepository(CreatorEntity).findOneByOrFail({id:second.creatorId});
   await expect(dispatch.accept(c1.accountId,first.id)).rejects.toMatchObject({code:'OFFER_UNAVAILABLE'});expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBeNull();await dispatch.accept(c2.accountId,second.id);expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBe(c2.id);
 });
 test('customer cancellation shares the fee with the assigned creator and pays it only once',async()=>{
   const x=await paid(55),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const now=new Date(x.session.startAt.getTime()-8*3600000),preview=await booking.cancelPreview(customer,x.session.id,now);expect(preview.feeBps).toBe(5000);await booking.cancel(customer,x.session.id,preview.feePaise,now);
   const [compensation]=await db.query('SELECT amount_paise FROM creator_compensation WHERE role_id=$1',[x.role.id]);expect(compensation.amount_paise).toBe(Math.round(preview.feePaise*.5));const run=await ops.generatePayout(opsId);expect(run.total_paise).toBe(compensation.amount_paise);await expect(ops.generatePayout(opsId)).rejects.toMatchObject({code:'NO_EARNINGS'});
 });
 test('album approval locks the reviewed proof and settles payment and refund only once',async()=>{
   const [asset]=await db.query("SELECT a.id,a.gallery_id FROM media_assets a JOIN galleries g ON g.id=a.gallery_id WHERE a.status='verified' AND a.kind='edited' AND g.status='final_ready' LIMIT 1");const draft=await request(app).post('/api/prints').auth('demo:customer',{type:'bearer'}).send({galleryId:asset.gallery_id,configuration:{size:'8x8',paper:'matte',cover:'linen',copies:1,pages:Array.from({length:10},()=>({assetId:asset.id}))},address:{name:'Demo recipient',line:'Sample event hall, Chennai',city:'Chennai',postcode:'600001',phone:'+919000000000'}});expect(draft.status).toBe(201);const id=draft.body.data.id,svc=new PrintService(repo,true);
   await expect(svc.detail(creatorAccount,id)).rejects.toMatchObject({code:'NOT_FOUND'});const proof=await svc.prepare(opsId,id,{reason:'Demo album resolution and sequence reviewed'});await svc.prepare(opsId,id,{reason:'Revised demo proof for approval'});await expect(svc.approveDemo(customer,id,{expectedTotalPaise:proof.total_paise,proofVersion:proof.proof_version})).rejects.toMatchObject({code:'PROOF_CHANGED'});const fresh=await svc.detail(customer,id);
   await expect(svc.advance(opsId,id,{stage:'shipped',reason:'Attempt before customer approval',trackingCode:'DEMO-TRACK'})).rejects.toMatchObject({code:'PRINT_STATE'});await Promise.all([svc.approveDemo(customer,id,{expectedTotalPaise:fresh.total_paise,proofVersion:fresh.proof_version}),svc.approveDemo(customer,id,{expectedTotalPaise:fresh.total_paise,proofVersion:fresh.proof_version})]);const [charges]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-print:${id}`]);expect(charges.n).toBe(1);await expect(svc.prepare(opsId,id,{reason:'Change after approved proof'})).rejects.toMatchObject({code:'PROOF_LOCKED'});
   await svc.advance(opsId,id,{stage:'shipped',reason:'Demo fulfilment handoff',trackingCode:'DEMO-TRACK'});await svc.advance(opsId,id,{stage:'delivered',reason:'Demo delivery acknowledged'});await svc.advance(opsId,id,{stage:'reprint',reason:'Demo print defect reported'});await svc.advance(opsId,id,{stage:'refunded',reason:'Customer requested a demo refund'});await svc.advance(opsId,id,{stage:'refunded',reason:'Repeated demo refund request'});const [refunds]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-print-refund:${id}`]);expect(refunds.n).toBe(1);
 });
 test('privacy export is owner-only and demo deletion blocks sign-in without erasing audit history',async()=>{
   const exported=await request(app).post('/api/me/privacy').auth('demo:customer',{type:'bearer'}).send({kind:'export'}),id=exported.body.data.id;expect((await request(app).get(`/api/me/privacy/${id}/data`).auth('demo:creator',{type:'bearer'})).status).toBe(404);const data=await request(app).get(`/api/me/privacy/${id}/data`).auth('demo:customer',{type:'bearer'});expect(data.body.data.account.id).toBe(customer);expect(data.body.data.orders.length).toBeGreaterThan(0);
   const svc=new PrivacyService(repo,true),pending=await request(app).post('/api/me/privacy').auth('demo:customer',{type:'bearer'}).send({kind:'delete'});await expect(svc.review(opsId,pending.body.data.id,{action:'complete_demo_deletion',reason:'Review test with active customer bookings'})).rejects.toMatchObject({code:'ACTIVE_BOOKINGS'});
   const fresh=await db.getRepository(AccountEntity).save({subject:'demo:privacy-fixture',name:'Synthetic privacy test',language:'en',role:'customer',consents:{}});const [deletion]=await db.query("INSERT INTO privacy_requests(account_id,kind) VALUES($1,'delete') RETURNING id",[fresh.id]);await svc.review(opsId,deletion.id,{action:'complete_demo_deletion',reason:'User requested deletion of this synthetic test account'});expect((await request(app).get('/api/me').auth('demo:privacy-fixture',{type:'bearer'})).status).toBe(401);const [audit]=await db.query("SELECT count(*)::int AS n FROM audit WHERE action='demo_privacy_deletion' AND entity_id=$1",[deletion.id]);expect(audit.n).toBe(1);
 });
 test('expiry sends one appropriate reminder, revokes access and removes only expired media files',async()=>{
   const [asset]=await db.query("SELECT a.*,g.id AS gid FROM media_assets a JOIN galleries g ON g.id=a.gallery_id WHERE a.status='verified' AND a.kind='edited' AND g.status='final_ready' LIMIT 1"),now=new Date();await db.query('UPDATE galleries SET expires_at=$2 WHERE id=$1',[asset.gid,new Date(now.getTime()+3600000)]);const shared=await media.share(customer,asset.gid,{kind:'public',expiresAt:new Date(now.getTime()+86400000).toISOString(),allowDownload:false});const svc=new RetentionService(repo,root);await svc.tick(now);await svc.tick(now);const [reminders]=await db.query("SELECT count(*)::int AS n FROM outbox WHERE entity_id=$1 AND kind LIKE 'gallery_expiry_%'",[asset.gid]);expect(reminders.n).toBe(1);await expect(stat(path.join(root,'primary',asset.storage_key))).resolves.toBeDefined();await svc.tick(new Date(now.getTime()+2*3600000));await expect(media.shared(shared.token)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(stat(path.join(root,'primary',asset.storage_key))).rejects.toMatchObject({code:'ENOENT'});const [purged]=await db.query('SELECT status,copies FROM media_assets WHERE id=$1',[asset.id]);expect(purged).toMatchObject({status:'purged',copies:0});
 });
 test('service reminders are deduplicated, localized and expose delayed matching refunds',async()=>{
   const delayed=await paid(105),clock=new Date(),reminders=new ServiceReminders(repo);
   await db.query("UPDATE sessions SET input=jsonb_set(input,'{mode}','\"on_demand\"') WHERE id=$1",[delayed.session.id]);await db.query('UPDATE roles SET dispatch_started_at=$2 WHERE id=$1',[delayed.role.id,new Date(clock.getTime()-16*60000)]);
   await reminders.tick(clock);await reminders.tick(clock);const [count]=await db.query("SELECT count(*)::int AS n FROM service_reminders WHERE role_id=$1 AND kind IN ('assignment_overdue','assignment_choice')",[delayed.role.id]);expect(count.n).toBe(2);expect((await booking.cancelPreview(customer,delayed.session.id,clock)).platformFault).toBe(true);
   const planned=await paid(106),creator=await repo.creator(creatorAccount),promptAt=new Date(planned.session.startAt.getTime()-24*3600000);await db.getRepository(RoleEntity).update(planned.role.id,{creatorId:creator.id,status:'assigned'});await db.getRepository(SessionEntity).update(planned.session.id,{status:'assigned'});await db.query('UPDATE roles SET assigned_at=$2 WHERE id=$1',[planned.role.id,new Date(promptAt.getTime()-3600000)]);await db.getRepository(AccountEntity).update(creatorAccount,{language:'ta'});
   await reminders.tick(promptAt);await reminders.tick(new Date(promptAt.getTime()+2*3600000));await reminders.tick(new Date(promptAt.getTime()+2*3600000));const [late]=await db.query("SELECT count(*)::int AS n FROM service_reminders WHERE role_id=$1 AND kind='reconfirmation_overdue'",[planned.role.id]);expect(late.n).toBe(1);
   for(let i=0;i<20&&await drainDemoOutbox(repo);i++);const [notice]=await db.query("SELECT n.title FROM notifications n JOIN outbox o ON o.id=n.event_id WHERE n.account_id=$1 AND o.entity_id=$2 AND o.kind='reconfirmation_due'",[creatorAccount,planned.role.id]);expect(notice.title).toContain('உறுதிசெய்யவும்');await db.getRepository(AccountEntity).update(creatorAccount,{language:'en'});
 });
 test('wallet spending is atomic and full mixed refunds return credits without cashing them out',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet',name:'Wallet test',language:'en',role:'customer',consents:{}}),source=await paid(120);
   await db.query('INSERT INTO customer_credits(customer_id,session_id,reference,amount_paise) VALUES($1,$2,$3,100000)',[wallet.id,source.session.id,'wallet-test-grant']);
   const quotes=await Promise.all([booking.quote(wallet.id,input(121)),booking.quote(wallet.id,input(122))]);const orders=await Promise.all(quotes.map(q=>booking.checkout(wallet.id,q.id,new Date(),true)));expect(orders.map(o=>o.creditPaise)).toEqual([100000,100000]);await expect(booking.checkout(wallet.id,quotes[0]!.id,new Date(),false)).rejects.toMatchObject({code:'CHECKOUT_CHANGED'});
   const events=orders.map(o=>({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise-o.creditPaise,currency:'INR',provider:'test'}));const result=await Promise.allSettled(events.map(e=>booking.confirmPayment(e)));expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);const failed=result.find(r=>r.status==='rejected') as PromiseRejectedResult;expect(failed.reason.code).toBe('CREDIT_CHANGED');
   const winner=result.findIndex(r=>r.status==='fulfilled'),order=orders[winner]!,session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id});expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(0);
   const refund=await booking.cancel(wallet.id,session.id,0);expect(refund.credit_paise).toBe(100000);await booking.cancel(wallet.id,session.id,0);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(100000);
   for(let i=0;i<20&&await drainDemoOutbox(repo);i++);const [entry]=await db.query("SELECT e.amount_paise FROM ledger_entries e JOIN ledger_transactions t ON t.id=e.transaction_id WHERE t.reference=$1 AND e.account='gateway_clearing'",[`demo-refund:${refund.id}`]);expect(entry.amount_paise).toBe(-(order.totalPaise-100000));await expect(booking.confirmPayment(events[winner]!)).resolves.toMatchObject({status:'cancelled'});
   const [redemptions]=await db.query('SELECT sum(amount_paise)::int AS total FROM credit_redemptions WHERE order_id=$1',[order.id]);expect(redemptions.total).toBe(100000);
 });
 test('lower-price rescheduling returns its proportional credit and preserves payment idempotency',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet-change',name:'Wallet change test',language:'en',role:'customer',consents:{}}),source=await paid(123);await db.query('INSERT INTO customer_credits(customer_id,session_id,reference,amount_paise) VALUES($1,$2,$3,100000)',[wallet.id,source.session.id,'wallet-change-grant']);
   const q=await booking.quote(wallet.id,input(6)),order=await booking.checkout(wallet.id,q.id,new Date(),true),event={id:randomUUID(),orderId:order.id,amountPaise:order.totalPaise-order.creditPaise,currency:'INR',provider:'test'};await booking.confirmPayment(event);const session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id}),svc=new SessionChangeService(repo),change=await svc.request(wallet.id,session.id,{kind:'reschedule',start:startFor(8)});expect(change.delta_paise).toBeLessThan(0);await svc.applyDemo(wallet.id,change.id,change.delta_paise);await svc.applyDemo(wallet.id,change.id,change.delta_paise);const revised=await repo.session(session.id);expect(revised.creditPaise).toBeLessThan(100000);await expect(booking.confirmPayment(event)).resolves.toHaveProperty('id',order.id);await booking.cancel(wallet.id,session.id,0);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(100000);
 });
 test('customers can choose a credit refund and cover a new booking entirely with credits',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet-full',name:'Full credit test',language:'en',role:'customer',consents:{}}),q=await booking.quote(wallet.id,input(130)),order=await booking.checkout(wallet.id,q.id);await booking.demoPay(wallet.id,order.id);const session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id}),refund=await booking.cancel(wallet.id,session.id,0,new Date(),'credit');expect(refund.credit_paise).toBe(order.totalPaise);const next=await booking.quote(wallet.id,input(131)),checkout=await booking.checkout(wallet.id,next.id,new Date(),true);expect(checkout.creditPaise).toBe(checkout.totalPaise);await booking.demoPay(wallet.id,checkout.id);await booking.demoPay(wallet.id,checkout.id);const [payment]=await db.query('SELECT amount_paise FROM payment_events WHERE order_id=$1',[checkout.id]);expect(payment.amount_paise).toBe(0);await expect(booking.checkout(wallet.id,next.id,new Date(),true,checkout.creditPaise)).resolves.toHaveProperty('id',checkout.id);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(0);
 });
 test('database rejects modification of audit and unbalanced ledger',async()=>{await expect(db.query('UPDATE audit SET action=$1',['changed'])).rejects.toThrow('Append-only');await expect(db.transaction(async m=>{const [t]=await m.query('INSERT INTO ledger_transactions(reference) VALUES($1) RETURNING id',[randomUUID()]);await m.query('INSERT INTO ledger_entries(transaction_id,account,amount_paise) VALUES($1,$2,$3)',[t.id,'cash',100]);})).rejects.toThrow('not balanced');});
});
