import request from 'supertest';
import {AuthenticationService} from '../src/services/authentication';
import sharp from 'sharp';
import {PDFDocument} from 'pdf-lib';
import {Client} from 'pg';
import {drainDemoOutbox} from '../src/services/demo-providers';
import {createHash,randomUUID} from 'node:crypto';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createApp} from '../src/app';
import {createDataSource} from '../src/db/data-source';
import {seedDemo} from '../src/db/seed';
import {PlatformRepository} from '../src/repositories/platform';
import {PrivacyService} from '../src/services/privacy';
import {RetentionService} from '../src/services/retention';
import {PrintService} from '../src/services/prints';
import {RecoveryService} from '../src/services/recovery';
import {SessionChangeService} from '../src/services/session-changes';
import {CreatorProfileService} from '../src/services/creator-profile';
import {RatingService} from '../src/services/ratings';
import {BookingService} from '../src/services/bookings';
import {DispatchService} from '../src/services/dispatch';
import {availableCredits} from '../src/services/credits';
import {ServiceReminders} from '../src/services/service-reminders';
import {SessionTimingService} from '../src/services/session-timing';
import {SessionService} from '../src/services/sessions';
import {MediaService} from '../src/services/media';
import {OperationsService} from '../src/services/operations';
import {AccountEntity,CreatorEntity,RoleEntity,SessionEntity} from '../src/entities';
import type {Env} from '../src/config/env';
import type {BookingInput} from '@kamraw/domain';
const url=process.env.TEST_DATABASE_URL;
const suite=url?describe:describe.skip;
suite('PostgreSQL platform integration',()=>{
 const dbName=`kamraw_test_${randomUUID().replaceAll('-','')}`,isolatedUrl=new URL(url??'postgresql://localhost/postgres');isolatedUrl.pathname=dbName;const db=createDataSource(isolatedUrl.toString());let repo:PlatformRepository,booking:BookingService,dispatch:DispatchService,media:MediaService,ops:OperationsService,app:ReturnType<typeof createApp>,root:string,customer:string,creatorAccount:string,opsId:string,approver:string;
 beforeAll(async()=>{const admin=new Client({connectionString:url});await admin.connect();try{await admin.query(`CREATE DATABASE ${dbName}`);}finally{await admin.end();}await db.initialize();await db.runMigrations();await seedDemo(db);root=await mkdtemp(path.join(os.tmpdir(),'kamraw-media-'));repo=new PlatformRepository(db);booking=new BookingService(repo);dispatch=new DispatchService(repo);media=new MediaService(repo,root,true);ops=new OperationsService(repo,true);customer=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:customer'})).id;creatorAccount=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:creator'})).id;opsId=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:ops'})).id;approver=(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:approver'})).id;app=createApp(db,{APP_MODE:'demo',NODE_ENV:'test',DATABASE_URL:url!,DATABASE_SSL:'false',WEB_ORIGIN:'http://localhost:5173',PUBLIC_API_URL:'http://localhost:4000',MEDIA_ROOT:root,PORT:4000,STAFF_ROLES_CLAIM:'roles'} as Env);});
 afterAll(async()=>{await db.destroy();if(root)await rm(root,{recursive:true,force:true});const admin=new Client({connectionString:url});await admin.connect();try{await admin.query(`DROP DATABASE IF EXISTS ${dbName}`);}finally{await admin.end();}});
 const startFor=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);d.setUTCHours(6,0,0,0);return d.toISOString();};
 const input=(days:number):BookingInput=>({category:'birthday',termsVersion:'demo-v1',sessions:[{start:startFor(days),mode:'scheduled',hours:2,venue:{lat:13.0827,lng:80.2707,address:'Demo venue, Chennai',type:'hall',contactName:'Host',contactPhone:'+919876543210',notes:''},roles:[{discipline:'photo',tier:'T1',count:1}],style:'candid',preferences:{femaleCreator:false},addons:[],notes:''}]});
 async function paid(days:number){const q=await booking.quote(customer,input(days));const o=await booking.checkout(customer,q.id);await booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise,currency:'INR',provider:'test'});const sessions=await db.getRepository(SessionEntity).findBy({orderId:o.id});const role=await db.getRepository(RoleEntity).findOneByOrFail({sessionId:sessions[0]!.id});return {order:o,session:sessions[0]!,role};}
 test('Kamraw sessions expire, revoke on logout and never cross the demo/live boundary',async()=>{
  const auth=new AuthenticationService(repo,true),live=new AuthenticationService(repo,false),now=new Date(),login=await auth.demoLogin({handle:'customer'},now);
  expect(login.token).toMatch(/^kmr_/);expect((await auth.authenticate(login.token,now)).account.id).toBe(customer);expect((await db.query('SELECT token_hash FROM auth_sessions WHERE account_id=$1',[customer]))[0].token_hash).not.toBe(login.token);
  expect((await request(app).get('/api/me').auth(login.token,{type:'bearer'})).status).toBe(200);await expect(live.authenticate(login.token,now)).rejects.toMatchObject({code:'SESSION_EXPIRED'});await expect(auth.authenticate(login.token,new Date(now.getTime()+15*86400000))).rejects.toMatchObject({code:'SESSION_EXPIRED'});
  expect((await request(app).post('/api/auth/logout').auth(login.token,{type:'bearer'}).send({})).status).toBe(200);await expect(auth.authenticate(login.token,now)).rejects.toMatchObject({code:'SESSION_EXPIRED'});await expect(live.demoLogin({handle:'ops'})).rejects.toMatchObject({code:'NOT_FOUND'});await expect(live.requestCode({phone:'9000000010'})).rejects.toMatchObject({code:'SMS_PROVIDER_REQUIRED'});
 });
 test('phone codes are single use and cannot grant staff privileges or create duplicate accounts',async()=>{
  const auth=new AuthenticationService(repo,true),now=new Date(),challenge=await auth.requestCode({phone:'9000000011'},now),body={challengeId:challenge.challengeId,code:challenge.demoCode,name:'Phone QA',role:'super_admin'};
  const results=await Promise.allSettled([auth.verifyCode(body,now),auth.verifyCode(body,now)]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);const signed=results.find(r=>r.status==='fulfilled')! as PromiseFulfilledResult<Awaited<ReturnType<typeof auth.verifyCode>>>;expect(signed.value.account.role).toBe('customer');expect((await auth.authenticate(signed.value.token,now)).mfa).toBe(false);expect((await request(app).get('/api/ops/finance').auth(signed.value.token,{type:'bearer'})).status).toBe(403);
  const later=new Date(now.getTime()+60000),next=await auth.requestCode({phone:'+91 90000 00011'},later),again=await auth.verifyCode({challengeId:next.challengeId,code:next.demoCode},later);expect(again.account.id).toBe(signed.value.account.id);expect(again.account.name).toBe('Phone QA');
  await db.query('UPDATE accounts SET disabled_at=$2 WHERE id=$1',[again.account.id,later]);await expect(auth.authenticate(again.token,later)).rejects.toMatchObject({code:'SESSION_EXPIRED'});
 });
 test('wrong codes consume attempts, expiry is enforced and resending invalidates the old challenge',async()=>{
  const auth=new AuthenticationService(repo,true),now=new Date(),q=await auth.requestCode({phone:'9000000012'},now),wrong=q.demoCode==='000000'?'999999':'000000';
  for(let i=0;i<5;i++)await expect(auth.verifyCode({challengeId:q.challengeId,code:wrong},now)).rejects.toMatchObject({code:'INVALID_CODE'});
  await expect(auth.verifyCode({challengeId:q.challengeId,code:q.demoCode},now)).rejects.toMatchObject({code:'INVALID_CODE'});expect((await db.query('SELECT attempts FROM auth_challenges WHERE id=$1',[q.challengeId]))[0].attempts).toBe(5);
  const expiring=await auth.requestCode({phone:'9000000013'},now);await expect(auth.verifyCode({challengeId:expiring.challengeId,code:expiring.demoCode},new Date(now.getTime()+5*60000))).rejects.toMatchObject({code:'INVALID_CODE'});
  const old=await auth.requestCode({phone:'9000000014'},now);await expect(auth.requestCode({phone:'9000000014'},now)).rejects.toMatchObject({code:'CODE_THROTTLED'});const next=await auth.requestCode({phone:'9000000014'},new Date(now.getTime()+60000));await expect(auth.verifyCode({challengeId:old.challengeId,code:old.demoCode})).rejects.toMatchObject({code:'INVALID_CODE'});expect(next.challengeId).not.toBe(old.challengeId);
 });
 test('phone sign-in routes validate input and mark demo responses as private',async()=>{
  expect((await request(app).post('/api/auth/phone/start').send({phone:'123'})).status).toBe(422);const start=await request(app).post('/api/auth/phone/start').send({phone:'9000000015'});expect(start.status).toBe(200);expect(start.headers['cache-control']).toBe('no-store');expect(start.body.data.demo).toBe(true);
  const verified=await request(app).post('/api/auth/phone/verify').send({challengeId:start.body.data.challengeId,code:start.body.data.demoCode,name:'API phone test'});expect(verified.status).toBe(200);expect(verified.body.data.account.role).toBe('customer');const token=verified.body.data.token;
  const profile=await request(app).get('/api/me').auth(token,{type:'bearer'});expect(profile.body.data.name).toBe('API phone test');expect((await request(app).post('/api/auth/phone/verify').send({challengeId:start.body.data.challengeId,code:start.body.data.demoCode})).status).toBe(401);
 });
 test('health is real and unauthenticated protected routes are denied',async()=>{expect((await request(app).get('/ready')).status).toBe(200);expect((await request(app).get('/api/orders')).status).toBe(401);expect((await request(app).get('/api/ops/finance').auth('demo:customer',{type:'bearer'})).status).toBe(403);expect((await request(app).get('/api/ops/privacy').auth('demo:finance',{type:'bearer'})).status).toBe(403);expect((await request(app).get('/api/ops/configurations').auth('demo:approver',{type:'bearer'})).status).toBe(200);});
 test('invalid payload and inaccessible order fail safely',async()=>{expect((await request(app).post('/api/quotes').auth('demo:customer',{type:'bearer'}).send({})).status).toBe(422);const {order}=await paid(10);expect((await request(app).get(`/api/orders/${order.id}`).auth('demo:creator',{type:'bearer'})).status).toBe(404);});
 test('checkout and verified payment are idempotent and ledger balances',async()=>{const q=await booking.quote(customer,input(11));const [a,b]=await Promise.all([booking.checkout(customer,q.id),booking.checkout(customer,q.id)]);expect(a.id).toBe(b.id);const e={id:randomUUID(),orderId:a.id,amountPaise:a.totalPaise,currency:'INR',provider:'test'};await Promise.all([booking.confirmPayment(e),booking.confirmPayment(e)]);const [r]=await db.query('SELECT count(*)::int AS count FROM payment_events WHERE order_id=$1',[a.id]);expect(r.count).toBe(1);const [sum]=await db.query('SELECT sum(e.amount_paise)::int AS total FROM ledger_entries e JOIN ledger_transactions t ON t.id=e.transaction_id WHERE t.order_id=$1',[a.id]);expect(sum.total).toBe(0);});
 test('mismatched amount cannot confirm a booking',async()=>{const q=await booking.quote(customer,input(12));const o=await booking.checkout(customer,q.id);await expect(booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:1,currency:'INR',provider:'test'})).rejects.toMatchObject({code:'PAYMENT_MISMATCH'});expect((await repo.order(o.id)).status).toBe('payment_pending');});
 test('payment statements are private and include simulated refunds',async()=>{const x=await paid(80);await booking.cancel(customer,x.session.id,0);await drainDemoOutbox(repo);const privatePath=`/api/orders/${x.order.id}`;expect((await request(app).get(`${privatePath}/statement`).auth('demo:creator',{type:'bearer'})).status).toBe(404);const detail=await request(app).get(`${privatePath}/payment-record`).auth('demo:customer',{type:'bearer'});expect(detail.status).toBe(200);expect(detail.body.data.refunds[0].status).toBe('simulated_refunded');const response=await request(app).get(`${privatePath}/statement`).auth('demo:customer',{type:'bearer'});expect(response.status).toBe(200);const pdf=await PDFDocument.load(Buffer.from(response.body.data.base64,'base64'));expect(pdf.getTitle()).toContain('demo statement');expect(pdf.getPageCount()).toBe(1);const history=await request(app).get('/api/payment-records').auth('demo:customer',{type:'bearer'});expect(history.body.data.orders.find((o:{id:string})=>o.id===x.order.id).refund_paise).toBe(x.order.totalPaise);});
 test('first acceptance wins under concurrent requests',async()=>{const x=await paid(13);await db.query("UPDATE sessions SET input=jsonb_set(input,'{mode}','\"on_demand\"') WHERE id=$1",[x.session.id]);const offers=await dispatch.dispatch(x.role.id);expect(offers.length).toBe(3);const identities=await Promise.all(offers.slice(0,2).map(async o=>(await db.getRepository(CreatorEntity).findOneByOrFail({id:o.creatorId})).accountId));const results=await Promise.allSettled(offers.slice(0,2).map((o,i)=>dispatch.accept(identities[i]!,o.id)));expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect(await db.getRepository(RoleEntity).countBy({sessionId:x.session.id,status:'assigned'})).toBe(1);});
 test('database prevents overlapping assignments even outside dispatch',async()=>{const a=await paid(14),b=await paid(14);const c=await repo.creator(creatorAccount);await db.getRepository(RoleEntity).update(a.role.id,{creatorId:c.id,status:'assigned'});await expect(db.getRepository(RoleEntity).update(b.role.id,{creatorId:c.id,status:'assigned'})).rejects.toMatchObject({code:'23P01'});});
 test('check-in geofence, completion code, verified uploads and maker checker',async()=>{
   const x=await paid(15),offers=await dispatch.dispatch(x.role.id);const c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const svc=new SessionService(repo,true);const now=new Date(x.session.startAt);const e=(action:string,extra:object={})=>({action,clientId:randomUUID(),deviceAt:now.toISOString(),location:{lat:13.0827,lng:80.2707,accuracy:5},...extra});
   await svc.transition(c.accountId,x.role.id,e('trip'),now);await expect(svc.transition(c.accountId,x.role.id,e('check_in',{identityProof:'demo-selfie',location:{lat:12,lng:79,accuracy:5}}),now)).rejects.toMatchObject({code:'OUTSIDE_GEOFENCE'});
   const check=e('check_in',{identityProof:'demo-selfie'});await svc.transition(c.accountId,x.role.id,check,now);await expect(svc.transition(c.accountId,x.role.id,check,now)).resolves.toMatchObject({synced:true});await svc.transition(c.accountId,x.role.id,e('start'),now);await expect(svc.transition(c.accountId,x.role.id,e('complete',{completionCode:'000000'}),now)).rejects.toMatchObject({code:'INVALID_CODE'});
   const s=await db.getRepository(SessionEntity).createQueryBuilder('s').addSelect('s.completionCode').where('s.id=:id',{id:x.session.id}).getOneOrFail();await svc.transition(c.accountId,x.role.id,e('complete',{completionCode:s.completionCode}),now);
   const discarded=await media.manifest(c.accountId,{sessionId:x.session.id,files:[{filename:'discard.jpg',bytes:3,checksum:createHash('sha256').update('bad').digest('hex'),kind:'edited'}]});await media.abandon(c.accountId,discarded.id);await expect(media.chunk(c.accountId,discarded.assets[0].id,0,Buffer.from('bad'))).rejects.toMatchObject({code:'DISCARDED'});
   const bytes=await sharp({create:{width:4000,height:4000,channels:3,background:'#bd7055'}}).jpeg().toBuffer(),hash=createHash('sha256').update(bytes).digest('hex');const upload=await media.manifest(c.accountId,{sessionId:x.session.id,files:[{filename:'test.jpg',bytes:bytes.length,checksum:hash,kind:'edited'}]});const asset=upload.assets[0];await media.chunk(c.accountId,asset.id,0,bytes.subarray(0,5));expect((await media.receipt(c.accountId,upload.id)).demoVerified).toBe(false);await expect(media.chunk(c.accountId,asset.id,0,bytes)).rejects.toMatchObject({code:'OFFSET_MISMATCH'});await media.chunk(c.accountId,asset.id,5,bytes.subarray(5));const receipt=await media.receipt(c.accountId,upload.id);expect(receipt.demoVerified).toBe(true);expect(receipt.safeToFormat).toBe(false);
   await ops.reviewAsset(opsId,asset.id,{status:'approved',reason:'Test output reviewed',width:4000,height:4000});const [gallery]=await db.query('SELECT id FROM galleries WHERE order_id=$1',[x.order.id]);await ops.publish(opsId,gallery.id,{stage:'preview_ready',reason:'Preview review complete'});const previewTicket=await media.ownerTicket(customer,asset.id);const preview=await media.authorizedFile(asset.id,previewTicket.ticket,false);expect((await sharp(preview.filename).metadata()).width).toBeLessThanOrEqual(1400);const qcTicket=await media.reviewTicket(opsId,asset.id);const original=await media.authorizedFile(asset.id,qcTicket.ticket,false);expect((await sharp(original.filename).metadata()).width).toBe(4000);await expect(ops.reviewAsset(opsId,asset.id,{status:'approved',reason:'Wrong size rejected',width:100,height:100})).rejects.toMatchObject({code:'DIMENSIONS_MISMATCH'});await ops.publish(opsId,gallery.id,{stage:'final_ready',reason:'Final review complete'});const freshTicket=await media.ownerTicket(customer,asset.id);expect((await request(app).get(`/api/media/${asset.id}?ticket=${freshTicket.ticket}`)).headers['content-type']).toMatch(/image\/jpeg/);await media.receipt(c.accountId,upload.id);expect((await repo.session(x.session.id)).status).toBe('final_delivered');
   const bundle=await media.archiveTicket(customer,gallery.id);await expect(media.archiveTicket(creatorAccount,gallery.id)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(media.archive(randomUUID(),bundle.ticket)).rejects.toMatchObject({code:'INVALID_TICKET'});await expect(media.archive(gallery.id,freshTicket.ticket)).rejects.toMatchObject({code:'INVALID_TICKET'});
   const parts:Buffer[]=[];for await(const chunk of await media.archive(gallery.id,bundle.ticket))parts.push(Buffer.from(chunk));const zip=Buffer.concat(parts);expect(zip.subarray(0,2).toString()).toBe('PK');expect(zip.includes(bytes)).toBe(true);expect(zip.includes(Buffer.from(`${asset.id}-test.jpg`))).toBe(true);expect(zip.includes(Buffer.from('discard.jpg'))).toBe(false);
   await db.query("UPDATE galleries SET expires_at=now()-interval '1 minute' WHERE id=$1",[gallery.id]);await expect(media.archive(gallery.id,bundle.ticket)).rejects.toMatchObject({code:'NOT_FOUND'});await db.query("UPDATE galleries SET expires_at=now()+interval '1 year' WHERE id=$1",[gallery.id]);
   const link=await media.share(customer,gallery.id,{kind:'pin',pin:'123456',expiresAt:new Date(Date.now()+86400000).toISOString(),allowDownload:false});await expect(media.shared(link.token,'000000')).rejects.toMatchObject({code:'PIN_REQUIRED'});expect((await media.shared(link.token,'123456')).assets).toHaveLength(1);const tickets=await media.sharedTickets(link.token,'123456');const ticket=tickets.assets[0]!.ticket;await expect(media.authorizedFile(asset.id,ticket,false)).resolves.toHaveProperty('filename');await expect(media.authorizedFile(asset.id,ticket,true)).rejects.toMatchObject({code:'EXPIRED_TICKET'});await expect(media.authorizedFile(randomUUID(),ticket,false)).rejects.toMatchObject({code:'EXPIRED_TICKET'});await db.query('UPDATE shares SET revoked_at=now() WHERE id=$1',[link.id]);await expect(media.authorizedFile(asset.id,ticket,false)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(media.shared(link.token,'123456')).rejects.toMatchObject({code:'NOT_FOUND'});
   const run=await ops.generatePayout(opsId);await expect(ops.approvePayout(opsId,run.id)).rejects.toMatchObject({code:'MAKER_CHECKER'});await expect(ops.approvePayout(approver,run.id)).resolves.toMatchObject({approved:true});
 });
 test('cancellation fees cannot change silently and cancellation is idempotent',async()=>{const x=await paid(16);const preview=await booking.cancelPreview(customer,x.session.id);await expect(booking.cancel(customer,x.session.id,preview.feePaise+1)).rejects.toMatchObject({code:'FEE_CHANGED'});const a=await booking.cancel(customer,x.session.id,preview.feePaise);const b=await booking.cancel(customer,x.session.id,preview.feePaise);expect(a.id).toBe(b.id);});
 test('demo settlements are explicitly labelled and idempotent',async()=>{await drainDemoOutbox(repo);await drainDemoOutbox(repo);const [r]=await db.query("SELECT count(*)::int AS n FROM payout_runs WHERE status='simulated_paid'");expect(r.n).toBe(1);const [refunds]=await db.query("SELECT count(*)::int AS n FROM refunds WHERE status='simulated_refunded'");expect(refunds.n).toBe(2);const [ledger]=await db.query("SELECT count(*)::int AS n FROM ledger_transactions WHERE reference LIKE 'demo-payout:%'");expect(ledger.n).toBe(1);});
 test('reschedule is once-only, resets dispatch, preserves ownership and applies payment once',async()=>{
   const x=await paid(30),svc=new SessionChangeService(repo);const offers=await dispatch.dispatch(x.role.id);const c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);
   await expect(svc.request(creatorAccount,x.session.id,{kind:'reschedule',start:startFor(31)})).rejects.toMatchObject({code:'NOT_FOUND'});
   const change=await svc.request(customer,x.session.id,{kind:'reschedule',start:startFor(31)});
   await expect(svc.applyDemo(customer,change.id,change.delta_paise+1)).rejects.toMatchObject({code:'PRICE_CHANGED'});
   await Promise.all([svc.applyDemo(customer,change.id,change.delta_paise),svc.applyDemo(customer,change.id,change.delta_paise)]);
   expect((await repo.session(x.session.id)).startAt.toISOString()).toBe(startFor(31));expect((await repo.session(x.session.id)).status).toBe('confirmed');expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).status).toBe('cancelled');
   const roles=await db.getRepository(RoleEntity).findBy({sessionId:x.session.id,status:'confirmed'});expect(roles).toHaveLength(1);expect(roles[0]!.creatorId).toBeNull();await expect(repo.authorizedSession(x.session.id,c.accountId)).rejects.toMatchObject({code:'NOT_FOUND'});expect((await dispatch.dispatch(roles[0]!.id)).length).toBeGreaterThan(0);
   await expect(svc.request(customer,x.session.id,{kind:'reschedule',start:startFor(32)})).rejects.toMatchObject({code:'RESCHEDULE_USED'});
   const close=await paid(1);await expect(svc.request(customer,close.session.id,{kind:'reschedule',start:startFor(35)})).rejects.toMatchObject({code:'RESCHEDULE_WINDOW'});
 });
 test('extension needs creator consent, conflict recheck and idempotent payment before changing time',async()=>{
   const x=await paid(40),svc=new SessionChangeService(repo),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);
   await db.getRepository(SessionEntity).update(x.session.id,{status:'in_session'});await db.getRepository(RoleEntity).update(x.role.id,{status:'in_session'});const now=new Date(x.session.endAt.getTime()-20*60000);
   const change=await svc.request(customer,x.session.id,{kind:'extension',blocks:1},now);
   await expect(svc.applyDemo(customer,change.id,change.delta_paise,now)).rejects.toMatchObject({code:'AWAITING_CREATORS'});
   await expect(svc.respond(customer,change.id,true,now)).rejects.toMatchObject({code:'NOT_FOUND'});await svc.respond(c.accountId,change.id,true,now);
   const [block]=await db.query('INSERT INTO availability(creator_id,start_at,end_at,available) VALUES($1,$2,$3,false) RETURNING id',[c.id,new Date(x.session.endAt.getTime()+35*60000),new Date(x.session.endAt.getTime()+90*60000)]);
   await expect(svc.applyDemo(customer,change.id,change.delta_paise,now)).rejects.toMatchObject({code:'EXTENSION_CONFLICT'});expect((await repo.session(x.session.id)).endAt).toEqual(x.session.endAt);await db.query('DELETE FROM availability WHERE id=$1',[block.id]);
   await Promise.all([svc.applyDemo(customer,change.id,change.delta_paise,now),svc.applyDemo(customer,change.id,change.delta_paise,now)]);
   expect((await repo.session(x.session.id)).endAt.getTime()).toBe(x.session.endAt.getTime()+30*60000);expect((await repo.order(x.order.id)).totalPaise).toBe(x.order.totalPaise+change.delta_paise);const [paidOnce]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-change:${change.id}`]);expect(paidOnce.n).toBe(1);
   const declined=await svc.request(customer,x.session.id,{kind:'extension',blocks:1},now);await svc.respond(c.accountId,declined.id,false,now);await expect(svc.applyDemo(customer,declined.id,declined.delta_paise,now)).rejects.toMatchObject({code:'CHANGE_UNAVAILABLE'});
 });
 test('notifications are private and delivered once, and support replies stay with their owner',async()=>{
   await drainDemoOutbox(repo);const first=await request(app).get('/api/notifications').auth('demo:customer',{type:'bearer'});expect(first.status).toBe(200);expect(first.body.data.length).toBeGreaterThan(0);const n=first.body.data[0];await drainDemoOutbox(repo);const again=await request(app).get('/api/notifications').auth('demo:customer',{type:'bearer'});expect(again.body.data.filter((x:{id:string})=>x.id===n.id)).toHaveLength(1);
   expect((await request(app).post(`/api/notifications/${n.id}/read`).auth('demo:creator',{type:'bearer'}).send({})).status).toBe(404);expect((await request(app).post(`/api/notifications/${n.id}/read`).auth('demo:customer',{type:'bearer'}).send({})).status).toBe(200);
   const internal=await paid(140);await db.transaction(m=>repo.event(m,'manual_dispatch_required',internal.role.id));for(let i=0;i<10&&await drainDemoOutbox(repo);i++);const alerts=await db.query("SELECT n.account_id FROM notifications n JOIN outbox o ON o.id=n.event_id WHERE o.kind='manual_dispatch_required' AND o.entity_id=$1",[internal.role.id]);expect(alerts.some((n:{account_id:string})=>n.account_id===customer)).toBe(false);expect(alerts.some((n:{account_id:string})=>n.account_id===opsId)).toBe(true);
   const ticket=await request(app).post('/api/tickets').auth('demo:customer',{type:'bearer'}).send({category:'booking',subject:'Question about my shoot',body:'Please confirm the preparation checklist.'});const ticketId=ticket.body.data.id;
   expect((await request(app).get(`/api/tickets/${ticketId}/messages`).auth('demo:creator',{type:'bearer'})).status).toBe(404);expect((await request(app).post(`/api/ops/tickets/${ticketId}/messages`).auth('demo:ops',{type:'bearer'}).send({body:'Your preparation checklist is in the shoot brief.'})).status).toBe(200);const replies=await request(app).get(`/api/tickets/${ticketId}/messages`).auth('demo:customer',{type:'bearer'});expect(replies.body.data).toHaveLength(1);
 });
 test('creator no-show releases the role, refunds without fee, issues one credit and nets penalties from payout',async()=>{
   const x=await paid(45),svc=new RecoveryService(repo),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const now=new Date(x.session.startAt.getTime()-3600000),preview=await svc.preview(c.accountId,x.role.id,now);expect(preview.noShow).toBe(true);
   await expect(svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise+1},now)).rejects.toMatchObject({code:'PENALTY_CHANGED'});
   await Promise.all([svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise},now),svc.cancel(c.accountId,x.role.id,{reason:'Equipment failure',expectedPenaltyPaise:preview.penaltyPaise},now)]);
   expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBeNull();const replacements=await dispatch.dispatch(x.role.id,now);expect(replacements.length).toBeGreaterThan(0);expect(replacements.some(o=>o.creatorId===c.id)).toBe(false);
   const refund=await booking.cancelPreview(customer,x.session.id,now);expect(refund.feePaise).toBe(0);expect(refund.creditPaise).toBe(Math.round(x.session.totalPaise*.2));await booking.cancel(customer,x.session.id,0,now);await booking.cancel(customer,x.session.id,0,now);const [credits]=await db.query('SELECT count(*)::int AS n FROM customer_credits WHERE session_id=$1',[x.session.id]);expect(credits.n).toBe(1);
   const earned=await paid(46);await db.getRepository(RoleEntity).update(earned.role.id,{creatorId:c.id,status:'media_verified'});const run=await ops.generatePayout(opsId);expect(run.total_paise).toBe(earned.role.earningPaise-preview.penaltyPaise);await ops.approvePayout(approver,run.id);await drainDemoOutbox(repo);await drainDemoOutbox(repo);const [balance]=await db.query("SELECT sum(amount_paise)::int AS total FROM ledger_entries WHERE account='creator_penalty_receivable'");expect(balance.total).toBe(0);
 });
 test('manual dispatch enforces qualification and still requires creator acceptance',async()=>{
   const x=await paid(50),candidates=await dispatch.manualCandidates(x.role.id);expect(candidates.length).toBeGreaterThan(1);
   expect((await request(app).get('/api/ops/dispatch').auth('demo:customer',{type:'bearer'})).status).toBe(403);
   const first=await dispatch.manualOffer(opsId,x.role.id,{creatorId:candidates[0]!.id,reason:'Manual coverage review'});const second=await dispatch.manualOffer(opsId,x.role.id,{creatorId:candidates[1]!.id,reason:'Choose available backup'});const c1=await db.getRepository(CreatorEntity).findOneByOrFail({id:first.creatorId}),c2=await db.getRepository(CreatorEntity).findOneByOrFail({id:second.creatorId});
   await expect(dispatch.accept(c1.accountId,first.id)).rejects.toMatchObject({code:'OFFER_UNAVAILABLE'});expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBeNull();await dispatch.accept(c2.accountId,second.id);expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).creatorId).toBe(c2.id);
 });
 test('customer cancellation shares the fee with the assigned creator and pays it only once',async()=>{
   const x=await paid(55),offers=await dispatch.dispatch(x.role.id),c=await db.getRepository(CreatorEntity).findOneByOrFail({id:offers[0]!.creatorId});await dispatch.accept(c.accountId,offers[0]!.id);const now=new Date(x.session.startAt.getTime()-8*3600000),preview=await booking.cancelPreview(customer,x.session.id,now);expect(preview.feeBps).toBe(5000);await booking.cancel(customer,x.session.id,preview.feePaise,now);
   const [compensation]=await db.query('SELECT amount_paise FROM creator_compensation WHERE role_id=$1',[x.role.id]);expect(compensation.amount_paise).toBe(Math.round(preview.feePaise*.5));const run=await ops.generatePayout(opsId);expect(run.total_paise).toBe(compensation.amount_paise);await expect(ops.generatePayout(opsId)).rejects.toMatchObject({code:'NO_EARNINGS'});
 });
 test('album approval locks the reviewed proof and settles payment and refund only once',async()=>{
   const [asset]=await db.query("SELECT a.id,a.gallery_id FROM media_assets a JOIN galleries g ON g.id=a.gallery_id WHERE a.status='verified' AND a.kind='edited' AND g.status='final_ready' LIMIT 1");const draft=await request(app).post('/api/prints').auth('demo:customer',{type:'bearer'}).send({galleryId:asset.gallery_id,configuration:{size:'8x8',paper:'matte',cover:'linen',copies:1,pages:Array.from({length:10},()=>({assetId:asset.id}))},address:{name:'Demo recipient',line:'Sample event hall, Chennai',city:'Chennai',postcode:'600001',phone:'+919000000000'}});expect(draft.status).toBe(201);const id=draft.body.data.id,svc=new PrintService(repo,true);
   await expect(svc.detail(creatorAccount,id)).rejects.toMatchObject({code:'NOT_FOUND'});const proof=await svc.prepare(opsId,id,{reason:'Demo album resolution and sequence reviewed'});await svc.prepare(opsId,id,{reason:'Revised demo proof for approval'});await expect(svc.approveDemo(customer,id,{expectedTotalPaise:proof.total_paise,proofVersion:proof.proof_version})).rejects.toMatchObject({code:'PROOF_CHANGED'});const fresh=await svc.detail(customer,id);
   await expect(svc.advance(opsId,id,{stage:'shipped',reason:'Attempt before customer approval',trackingCode:'DEMO-TRACK'})).rejects.toMatchObject({code:'PRINT_STATE'});await Promise.all([svc.approveDemo(customer,id,{expectedTotalPaise:fresh.total_paise,proofVersion:fresh.proof_version}),svc.approveDemo(customer,id,{expectedTotalPaise:fresh.total_paise,proofVersion:fresh.proof_version})]);const [charges]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-print:${id}`]);expect(charges.n).toBe(1);await expect(svc.prepare(opsId,id,{reason:'Change after approved proof'})).rejects.toMatchObject({code:'PROOF_LOCKED'});
   await svc.advance(opsId,id,{stage:'shipped',reason:'Demo fulfilment handoff',trackingCode:'DEMO-TRACK'});await svc.advance(opsId,id,{stage:'delivered',reason:'Demo delivery acknowledged'});await svc.advance(opsId,id,{stage:'reprint',reason:'Demo print defect reported'});await svc.advance(opsId,id,{stage:'refunded',reason:'Customer requested a demo refund'});await svc.advance(opsId,id,{stage:'refunded',reason:'Repeated demo refund request'});const [refunds]=await db.query('SELECT count(*)::int AS n FROM ledger_transactions WHERE reference=$1',[`demo-print-refund:${id}`]);expect(refunds.n).toBe(1);
 });
 test('privacy export is owner-only and demo deletion blocks sign-in without erasing audit history',async()=>{
   const exported=await request(app).post('/api/me/privacy').auth('demo:customer',{type:'bearer'}).send({kind:'export'}),id=exported.body.data.id;expect((await request(app).get(`/api/me/privacy/${id}/data`).auth('demo:creator',{type:'bearer'})).status).toBe(404);const data=await request(app).get(`/api/me/privacy/${id}/data`).auth('demo:customer',{type:'bearer'});expect(data.body.data.account.id).toBe(customer);expect(data.body.data.orders.length).toBeGreaterThan(0);expect(data.body.data.payments.length).toBeGreaterThan(0);expect(data.body.data.albumOrders.length).toBeGreaterThan(0);expect(data.body.data.credits).toBeDefined();expect(data.body.data.uploadedFiles).toEqual([]);
   const svc=new PrivacyService(repo,true),pending=await request(app).post('/api/me/privacy').auth('demo:customer',{type:'bearer'}).send({kind:'delete'});await expect(svc.review(opsId,pending.body.data.id,{action:'complete_demo_deletion',reason:'Review test with active customer bookings'})).rejects.toMatchObject({code:'ACTIVE_BOOKINGS'});
   const fresh=await db.getRepository(AccountEntity).save({subject:'demo:privacy-fixture',name:'Synthetic privacy test',language:'en',role:'customer',consents:{}});const login=await new AuthenticationService(repo,true).demoLogin({handle:'privacy-fixture'});const [deletion]=await db.query("INSERT INTO privacy_requests(account_id,kind) VALUES($1,'delete') RETURNING id",[fresh.id]);await svc.review(opsId,deletion.id,{action:'complete_demo_deletion',reason:'User requested deletion of this synthetic test account'});expect((await db.query('SELECT revoked_at FROM auth_sessions WHERE account_id=$1',[fresh.id]))[0].revoked_at).not.toBeNull();await expect(new AuthenticationService(repo,true).authenticate(login.token)).rejects.toMatchObject({code:'SESSION_EXPIRED'});expect((await request(app).get('/api/me').auth('demo:privacy-fixture',{type:'bearer'})).status).toBe(401);const [audit]=await db.query("SELECT count(*)::int AS n FROM audit WHERE action='demo_privacy_deletion' AND entity_id=$1",[deletion.id]);expect(audit.n).toBe(1);
 });
 test('expiry sends one appropriate reminder, revokes access and removes only expired media files',async()=>{
   const [asset]=await db.query("SELECT a.*,g.id AS gid FROM media_assets a JOIN galleries g ON g.id=a.gallery_id WHERE a.status='verified' AND a.kind='edited' AND g.status='final_ready' LIMIT 1"),now=new Date();await db.query('UPDATE galleries SET expires_at=$2 WHERE id=$1',[asset.gid,new Date(now.getTime()+3600000)]);const shared=await media.share(customer,asset.gid,{kind:'public',expiresAt:new Date(now.getTime()+86400000).toISOString(),allowDownload:false});const svc=new RetentionService(repo,root);await svc.tick(now);await svc.tick(now);const [reminders]=await db.query("SELECT count(*)::int AS n FROM outbox WHERE entity_id=$1 AND kind LIKE 'gallery_expiry_%'",[asset.gid]);expect(reminders.n).toBe(1);await expect(stat(path.join(root,'primary',asset.storage_key))).resolves.toBeDefined();await svc.tick(new Date(now.getTime()+2*3600000));await expect(media.shared(shared.token)).rejects.toMatchObject({code:'NOT_FOUND'});await expect(stat(path.join(root,'primary',asset.storage_key))).rejects.toMatchObject({code:'ENOENT'});const [purged]=await db.query('SELECT status,copies FROM media_assets WHERE id=$1',[asset.id]);expect(purged).toMatchObject({status:'purged',copies:0});
 });
 test('service reminders are deduplicated, localized and expose delayed matching refunds',async()=>{
   const delayed=await paid(105),clock=new Date(),reminders=new ServiceReminders(repo);
   await db.query("UPDATE sessions SET input=jsonb_set(input,'{mode}','\"on_demand\"') WHERE id=$1",[delayed.session.id]);await db.query('UPDATE roles SET dispatch_started_at=$2 WHERE id=$1',[delayed.role.id,new Date(clock.getTime()-16*60000)]);
   await reminders.tick(clock);await reminders.tick(clock);const [count]=await db.query("SELECT count(*)::int AS n FROM service_reminders WHERE role_id=$1 AND kind IN ('assignment_overdue','assignment_choice')",[delayed.role.id]);expect(count.n).toBe(2);expect((await booking.cancelPreview(customer,delayed.session.id,clock)).platformFault).toBe(true);
   const planned=await paid(106),creator=await repo.creator(creatorAccount),promptAt=new Date(planned.session.startAt.getTime()-24*3600000);await db.getRepository(RoleEntity).update(planned.role.id,{creatorId:creator.id,status:'assigned'});await db.getRepository(SessionEntity).update(planned.session.id,{status:'assigned'});await db.query('UPDATE roles SET assigned_at=$2 WHERE id=$1',[planned.role.id,new Date(promptAt.getTime()-3600000)]);await db.getRepository(AccountEntity).update(creatorAccount,{language:'ta'});
   await reminders.tick(promptAt);await reminders.tick(new Date(promptAt.getTime()+2*3600000));await reminders.tick(new Date(promptAt.getTime()+2*3600000));const [late]=await db.query("SELECT count(*)::int AS n FROM service_reminders WHERE role_id=$1 AND kind='reconfirmation_overdue'",[planned.role.id]);expect(late.n).toBe(1);
   for(let i=0;i<20&&await drainDemoOutbox(repo);i++);const [notice]=await db.query("SELECT n.title FROM notifications n JOIN outbox o ON o.id=n.event_id WHERE n.account_id=$1 AND o.entity_id=$2 AND o.kind='reconfirmation_due'",[creatorAccount,planned.role.id]);expect(notice.title).toContain('உறுதிசெய்யவும்');await db.getRepository(AccountEntity).update(creatorAccount,{language:'en'});
 });
 test('wallet spending is atomic and full mixed refunds return credits without cashing them out',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet',name:'Wallet test',language:'en',role:'customer',consents:{}}),source=await paid(120);
   await db.query('INSERT INTO customer_credits(customer_id,session_id,reference,amount_paise) VALUES($1,$2,$3,100000)',[wallet.id,source.session.id,'wallet-test-grant']);
   const quotes=await Promise.all([booking.quote(wallet.id,input(121)),booking.quote(wallet.id,input(122))]);const orders=await Promise.all(quotes.map(q=>booking.checkout(wallet.id,q.id,new Date(),true)));expect(orders.map(o=>o.creditPaise)).toEqual([100000,100000]);await expect(booking.checkout(wallet.id,quotes[0]!.id,new Date(),false)).rejects.toMatchObject({code:'CHECKOUT_CHANGED'});
   const events=orders.map(o=>({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise-o.creditPaise,currency:'INR',provider:'test'}));const result=await Promise.allSettled(events.map(e=>booking.confirmPayment(e)));expect(result.filter(r=>r.status==='fulfilled')).toHaveLength(1);const failed=result.find(r=>r.status==='rejected') as PromiseRejectedResult;expect(failed.reason.code).toBe('CREDIT_CHANGED');
   const winner=result.findIndex(r=>r.status==='fulfilled'),order=orders[winner]!,session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id});expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(0);
   const refund=await booking.cancel(wallet.id,session.id,0);expect(refund.credit_paise).toBe(100000);await booking.cancel(wallet.id,session.id,0);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(100000);
   for(let i=0;i<20&&await drainDemoOutbox(repo);i++);const [entry]=await db.query("SELECT e.amount_paise FROM ledger_entries e JOIN ledger_transactions t ON t.id=e.transaction_id WHERE t.reference=$1 AND e.account='gateway_clearing'",[`demo-refund:${refund.id}`]);expect(entry.amount_paise).toBe(-(order.totalPaise-100000));await expect(booking.confirmPayment(events[winner]!)).resolves.toMatchObject({status:'cancelled'});
   const [redemptions]=await db.query('SELECT sum(amount_paise)::int AS total FROM credit_redemptions WHERE order_id=$1',[order.id]);expect(redemptions.total).toBe(100000);
 });
 test('lower-price rescheduling returns its proportional credit and preserves payment idempotency',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet-change',name:'Wallet change test',language:'en',role:'customer',consents:{}}),source=await paid(123);await db.query('INSERT INTO customer_credits(customer_id,session_id,reference,amount_paise) VALUES($1,$2,$3,100000)',[wallet.id,source.session.id,'wallet-change-grant']);
   const q=await booking.quote(wallet.id,input(6)),order=await booking.checkout(wallet.id,q.id,new Date(),true),event={id:randomUUID(),orderId:order.id,amountPaise:order.totalPaise-order.creditPaise,currency:'INR',provider:'test'};await booking.confirmPayment(event);const session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id}),svc=new SessionChangeService(repo),change=await svc.request(wallet.id,session.id,{kind:'reschedule',start:startFor(8)});expect(change.delta_paise).toBeLessThan(0);await svc.applyDemo(wallet.id,change.id,change.delta_paise);await svc.applyDemo(wallet.id,change.id,change.delta_paise);const revised=await repo.session(session.id);expect(revised.creditPaise).toBeLessThan(100000);await expect(booking.confirmPayment(event)).resolves.toHaveProperty('id',order.id);await booking.cancel(wallet.id,session.id,0);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(100000);
 });
 test('customers can choose a credit refund and cover a new booking entirely with credits',async()=>{
   const wallet=await db.getRepository(AccountEntity).save({subject:'demo:wallet-full',name:'Full credit test',language:'en',role:'customer',consents:{}}),q=await booking.quote(wallet.id,input(130)),order=await booking.checkout(wallet.id,q.id);await booking.demoPay(wallet.id,order.id);const session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id}),refund=await booking.cancel(wallet.id,session.id,0,new Date(),'credit');expect(refund.credit_paise).toBe(order.totalPaise);const next=await booking.quote(wallet.id,input(131)),checkout=await booking.checkout(wallet.id,next.id,new Date(),true);expect(checkout.creditPaise).toBe(checkout.totalPaise);await booking.demoPay(wallet.id,checkout.id);await booking.demoPay(wallet.id,checkout.id);const [payment]=await db.query('SELECT amount_paise FROM payment_events WHERE order_id=$1',[checkout.id]);expect(payment.amount_paise).toBe(0);await expect(booking.checkout(wallet.id,next.id,new Date(),true,checkout.creditPaise)).resolves.toHaveProperty('id',checkout.id);expect((await availableCredits(db.manager,wallet.id)).reduce((n,c)=>n+c.balance_paise,0)).toBe(0);
 });
 test('deploy-time demo seeding preserves profile and consent changes',async()=>{const before=await repo.account(customer);await db.getRepository(AccountEntity).update(customer,{name:'Saved customer name',language:'ta',consents:{marketing:false,portfolio:true,guardian:false}});await seedDemo(db);const after=await repo.account(customer);expect(after.name).toBe('Saved customer name');expect(after.language).toBe('ta');expect(after.consents.portfolio).toBe(true);await db.getRepository(AccountEntity).update(customer,{name:before.name,language:before.language,consents:before.consents});});
 test('database rejects modification of audit and unbalanced ledger',async()=>{await expect(db.query('UPDATE audit SET action=$1',['changed'])).rejects.toThrow('Append-only');await expect(db.transaction(async m=>{const [t]=await m.query('INSERT INTO ledger_transactions(reference) VALUES($1) RETURNING id',[randomUUID()]);await m.query('INSERT INTO ledger_entries(transaction_id,account,amount_paise) VALUES($1,$2,$3)',[t.id,'cash',100]);})).rejects.toThrow('not balanced');});
 test('assigned creator cards redact private fields and validate profile photos',async()=>{
   const x=await paid(160),creator=await repo.creator(creatorAccount),profiles=new CreatorProfileService(repo,true),before=await profiles.self(creatorAccount);
   await db.getRepository(RoleEntity).update(x.role.id,{creatorId:creator.id,status:'assigned'});
   await db.getRepository(CreatorEntity).update(creator.id,{profile:{...creator.profile,bio:'Portrait photographer',gear:[{type:'camera',model:'Test camera',serial:'PRIVATE-SERIAL',ownership:'owned'}],portfolioUrls:['https://example.com/portfolio','javascript:alert(1)'],emergencyContact:'+919876543210'}});
   const own=await request(app).get('/api/creator/performance').auth('demo:creator',{type:'bearer'});expect(own.status).toBe(200);expect(own.body.data.profile.rating).toBe(before.profile.rating);
   expect((await request(app).get(`/api/sessions/${x.session.id}/creators`).auth('demo:creator3',{type:'bearer'})).status).toBe(404);
   const cards=await request(app).get(`/api/sessions/${x.session.id}/creators`).auth('demo:customer',{type:'bearer'});expect(cards.status).toBe(200);expect(cards.body.data[0].verificationCode).toBe(own.body.data.profile.verificationCode);expect(cards.body.data[0].portfolioUrls).toEqual(['https://example.com/portfolio']);expect(cards.body.data[0].gear).toEqual([{type:'camera',model:'Test camera'}]);expect(JSON.stringify(cards.body.data)).not.toMatch(/PRIVATE-SERIAL|emergencyContact|checks|accountId/);
   const photo=await sharp({create:{width:800,height:600,channels:3,background:'#a95846'}}).png().toBuffer();
   const saved=await request(app).put('/api/creator/photo').auth('demo:creator',{type:'bearer'}).set('Content-Type','application/octet-stream').send(photo);expect(saved.status).toBe(200);
   const after=await profiles.self(creatorAccount),jpeg=Buffer.from(after.profile.photo!.split(',')[1]!,'base64');expect(await sharp(jpeg).metadata()).toMatchObject({format:'jpeg',width:512,height:512});expect(after.profile.verificationCode).toBe(before.profile.verificationCode);
   await expect(profiles.photo(creatorAccount,Buffer.from('broken'))).rejects.toMatchObject({code:'PHOTO_FORMAT'});await expect(profiles.photo(creatorAccount,Buffer.alloc(4*1024**2+1))).rejects.toMatchObject({code:'PHOTO_SIZE'});await expect(profiles.photo(creatorAccount,Buffer.from('<svg width="10" height="10"></svg>'))).rejects.toMatchObject({code:'PHOTO_FORMAT'});
   await expect(new CreatorProfileService(repo,false).photo(creatorAccount,photo)).rejects.toMatchObject({code:'PHOTO_REVIEW_REQUIRED'});await db.query('UPDATE creators SET profile=$2 WHERE id=$1',[creator.id,JSON.stringify(creator.profile)]);
 });
 test('crew feedback is per creator, mutual, private and idempotent',async()=>{
   const body=input(161);body.sessions[0]!.roles[0]!.count=2;const quote=await booking.quote(customer,body),order=await booking.checkout(customer,quote.id);await booking.confirmPayment({id:randomUUID(),orderId:order.id,amountPaise:order.totalPaise,currency:'INR',provider:'test'});
   const session=await db.getRepository(SessionEntity).findOneByOrFail({orderId:order.id}),roles=await db.getRepository(RoleEntity).findBy({sessionId:session.id}),c1=await repo.creator(creatorAccount),c2=await db.getRepository(CreatorEntity).findOneByOrFail({accountId:(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:creator2'})).id});
   await db.getRepository(RoleEntity).update(roles[0]!.id,{creatorId:c1.id,status:'session_completed'});await db.getRepository(RoleEntity).update(roles[1]!.id,{creatorId:c2.id,status:'session_completed'});await db.getRepository(SessionEntity).update(session.id,{status:'session_completed',completedAt:new Date()});
   const url=`/api/sessions/${session.id}/ratings`,review={kind:'creator',creatorId:c1.id,stars:3,tags:['friendly','punctual','friendly'],comment:'Helpful crew'};
   const results=await Promise.all([request(app).post(url).auth('demo:customer',{type:'bearer'}).send(review),request(app).post(url).auth('demo:customer',{type:'bearer'}).send(review)]);expect(results.map(r=>r.status)).toEqual([201,201]);expect(results[0]!.body.data.id).toBe(results[1]!.body.data.id);expect(results[0]!.body.data.tags).toEqual(['friendly','punctual']);
   expect((await request(app).post(url).auth('demo:customer',{type:'bearer'}).send({...review,stars:4})).status).toBe(409);expect((await request(app).post(url).auth('demo:customer',{type:'bearer'}).send({...review,creatorId:c2.id,stars:4})).status).toBe(201);
   expect((await request(app).post(url).auth('demo:customer',{type:'bearer'}).send({kind:'creator',stars:5})).body.error.code).toBe('CREATOR_REQUIRED');expect((await request(app).post(url).auth('demo:customer',{type:'bearer'}).send({...review,creatorId:randomUUID()})).status).toBe(404);
   expect((await request(app).post(url).auth('demo:creator',{type:'bearer'}).send({kind:'customer',stars:5,tags:['venue_ready'],comment:'Host had the venue ready'})).status).toBe(201);
   expect((await request(app).post(url).auth('demo:creator2',{type:'bearer'}).send({kind:'customer',stars:4})).status).toBe(201);
   expect((await request(app).post(url).auth('demo:creator',{type:'bearer'}).send({kind:'delivery',stars:5})).status).toBe(403);expect((await request(app).post(url).auth('demo:customer',{type:'bearer'}).send({kind:'customer',stars:5})).status).toBe(403);expect((await request(app).post(url).auth('demo:creator3',{type:'bearer'}).send({kind:'customer',stars:5})).status).toBe(404);
   const own=await request(app).get(url).auth('demo:customer',{type:'bearer'});expect(own.body.data.ratings).toHaveLength(2);expect(own.body.data.windows.session.open).toBe(true);expect(own.body.data.windows.delivery.open).toBe(false);
   const profiles=new CreatorProfileService(repo,true),performance=await profiles.self(creatorAccount);expect(performance.profile.rating).toBe(3);expect(performance.statistics.review).toBe('suspension_review');expect((await repo.creator(creatorAccount)).status).toBe(c1.status);
   for(let i=0;i<20&&await drainDemoOutbox(repo);i++);const alerts=await db.query("SELECT n.account_id,o.payload FROM notifications n JOIN outbox o ON o.id=n.event_id WHERE o.kind='creator_quality_review' AND o.entity_id=$1",[c1.id]);expect(alerts.some((n:{account_id:string})=>n.account_id===opsId)).toBe(true);expect(alerts.some((n:{account_id:string})=>n.account_id===customer||n.account_id===creatorAccount)).toBe(false);expect(alerts[0].payload.review).toBe('suspension_review');
 });
 test('delivery feedback uses its own seven-day window after final delivery',async()=>{
   const x=await paid(162),svc=new RatingService(repo),now=new Date();await db.getRepository(SessionEntity).update(x.session.id,{completedAt:new Date(now.getTime()-20*86400000),status:'final_delivered'});
   await expect(svc.rate(customer,x.session.id,{kind:'delivery',stars:5},now)).rejects.toMatchObject({code:'RATING_WINDOW'});
   await db.query('UPDATE galleries SET final_delivered_at=$2 WHERE order_id=$1',[x.order.id,new Date(now.getTime()-86400000)]);await expect(svc.rate(customer,x.session.id,{kind:'creator',stars:5,creatorId:(await repo.creator(creatorAccount)).id},now)).rejects.toMatchObject({code:'RATING_WINDOW'});await expect(svc.rate(customer,x.session.id,{kind:'delivery',stars:5,tags:['delivery_quality']},now)).resolves.toMatchObject({kind:'delivery'});
   expect((await svc.list(customer,x.session.id,now)).windows).toMatchObject({session:{open:false},delivery:{open:true}});expect((await svc.list(customer,x.session.id,new Date(now.getTime()+7*86400000))).windows.delivery.open).toBe(false);
   await expect(svc.rate(customer,x.session.id,{kind:'delivery',stars:5},new Date(now.getTime()+7*86400000))).rejects.toMatchObject({code:'RATING_WINDOW'});
 });

 test('creator performance considers only the latest twenty recipient-specific reviews',async()=>{
   const x=await paid(163),c=await db.getRepository(CreatorEntity).findOneByOrFail({accountId:(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:creator3'})).id}),now=new Date();
   for(let i=0;i<21;i++){
     const start=new Date(now.getTime()-(30-i)*86400000),end=new Date(start.getTime()+2*3600000);
     const [session]=await db.query("INSERT INTO sessions(order_id,start_at,end_at,zone_id,status,input,total_paise,completion_code,completed_at) VALUES($1,$2,$3,'chennai-pilot','closed',$4,1,'123456',$3) RETURNING id",[x.order.id,start,end,JSON.stringify(x.session.input)]);
     await db.query("INSERT INTO ratings(session_id,rater_id,kind,creator_id,stars,comment,created_at) VALUES($1,$2,'creator',$3,$4,'Rolling-window test',$5)",[session.id,customer,c.id,i===0?1:5,new Date(now.getTime()-(21-i)*60000)]);
   }
   const result=await new CreatorProfileService(repo,true).self(c.accountId);expect(result.profile.rating).toBe(5);expect(result.profile.ratingCount).toBe(20);expect(result.statistics.review).toBe('within_standard');
 });

 async function running(days:number,lateMinutes=0){
   const x=await paid(days),c=await repo.creator(creatorAccount),svc=new SessionService(repo,true),clock=new Date(x.session.startAt.getTime()+lateMinutes*60000);
   await db.getRepository(RoleEntity).update(x.role.id,{creatorId:c.id,status:'assigned'});await db.getRepository(SessionEntity).update(x.session.id,{status:'assigned'});
   const post=(action:string,at=clock,extra:object={})=>svc.transition(c.accountId,x.role.id,{action,clientId:randomUUID(),deviceAt:at.toISOString(),location:{...x.session.input.venue,accuracy:5},identityProof:'demo-selfie',...extra},at);
   await post('trip',x.session.startAt);await post('check_in');await post('start');return {...x,c,clock,post};
 }
 test('late arrival credits once, retains full duration and respects the venue choice and paid extensions',async()=>{
   const x=await running(166,15),timing=new SessionTimingService(repo),arrival=await repo.session(x.session.id),expectedCredit=Math.round(x.session.totalPaise/10);
   expect(arrival.endAt.getTime()).toBe(x.session.endAt.getTime()+15*60000);const detail=await timing.detail(customer,x.session.id,x.clock);expect(detail.lateCreditPaise).toBe(expectedCredit);expect(detail.roles[0]).toMatchObject({late:true,overrun_conflict:false});expect((await timing.detail(creatorAccount,x.session.id)).customer).toBe(false);await expect(timing.detail((await repo.account(opsId)).id,x.session.id)).rejects.toMatchObject({code:'NOT_FOUND'});
   const [credit]=await db.query('SELECT count(*)::int AS n FROM customer_credits WHERE reference=$1',[`late-arrival:${x.session.id}`]);expect(credit.n).toBe(1);const [ledger]=await db.query('SELECT sum(amount_paise)::int AS total FROM ledger_entries WHERE transaction_id=(SELECT id FROM ledger_transactions WHERE reference=$1)',[`late-credit:${x.session.id}`]);expect(ledger.total).toBe(0);
   await timing.venue(customer,x.session.id,{allowOverrun:false});expect((await repo.session(x.session.id)).endAt.toISOString()).toBe(x.session.endAt.toISOString());await expect(new SessionChangeService(repo).request(customer,x.session.id,{kind:'extension',blocks:1},x.clock)).rejects.toMatchObject({code:'VENUE_LIMIT'});
   await timing.venue(customer,x.session.id,{allowOverrun:true});const changes=new SessionChangeService(repo),change=await changes.request(customer,x.session.id,{kind:'extension',blocks:1},x.clock);await changes.respond(creatorAccount,change.id,true,x.clock);await changes.applyDemo(customer,change.id,change.delta_paise,x.clock);expect((await repo.session(x.session.id)).endAt.getTime()).toBe(x.session.endAt.getTime()+45*60000);expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).serviceEndAt?.getTime()).toBe(x.session.endAt.getTime()+45*60000);
 });
 test('customer-unavailable completion needs full time and checkout evidence, then closes exactly once after an hour',async()=>{
   const x=await running(167),timing=new SessionTimingService(repo),end=new Date(x.session.endAt),body={clientId:randomUUID(),location:{...x.session.input.venue,accuracy:5}};
   await expect(timing.request(creatorAccount,x.role.id,body,x.clock)).rejects.toMatchObject({code:'FULL_DURATION_REQUIRED'});await expect(timing.request(creatorAccount,x.role.id,{...body,location:{lat:12,lng:79,accuracy:5}},end)).rejects.toMatchObject({code:'OUTSIDE_GEOFENCE'});
   const q=await timing.request(creatorAccount,x.role.id,body,end);expect((await timing.request(creatorAccount,x.role.id,body,end)).id).toBe(q.id);expect((await timing.request(creatorAccount,x.role.id,{...body,clientId:randomUUID()},end)).id).toBe(q.id);
   await timing.closeDue(new Date(end.getTime()+59*60000));expect((await repo.session(x.session.id)).status).toBe('in_session');await timing.closeDue(new Date(end.getTime()+60*60000));await timing.closeDue(new Date(end.getTime()+61*60000));expect((await repo.session(x.session.id)).status).toBe('session_completed');const [saved]=await db.query('SELECT status,location FROM completion_requests WHERE id=$1',[q.id]);expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).actualCompletedAt?.toISOString()).toBe(end.toISOString());expect(saved.status).toBe('auto_completed');expect(saved.location.accuracy).toBe(5);const [events]=await db.query("SELECT count(*)::int AS n FROM outbox WHERE kind='session_complete' AND entity_id=$1",[x.session.id]);expect(events.n).toBe(1);
 });
 test('a customer dispute stops automatic completion and operations can reopen or resolve it',async()=>{
   const x=await running(168),timing=new SessionTimingService(repo),end=new Date(x.session.endAt),q=await timing.request(creatorAccount,x.role.id,{clientId:randomUUID(),location:{...x.session.input.venue,accuracy:5}},end);
   expect((await request(app).get('/api/ops/completion-requests').auth('demo:customer',{type:'bearer'})).status).toBe(403);expect((await request(app).post(`/api/completion-requests/${q.id}/decision`).auth('demo:creator2',{type:'bearer'}).send({action:'confirm'})).status).toBe(404);
   await timing.decide(customer,q.id,{action:'dispute',reason:'The shoot is not yet complete'},end);await timing.closeDue(new Date(end.getTime()+2*3600000));expect((await repo.session(x.session.id)).status).toBe('in_session');expect((await timing.queue()).find((r:{id:string})=>r.id===q.id).status).toBe('disputed');
   await timing.decide(opsId,q.id,{action:'continue',reason:'Customer and creator agreed to continue'},end,true);const next=await timing.request(creatorAccount,x.role.id,{clientId:randomUUID(),location:{...x.session.input.venue,accuracy:5}},new Date(end.getTime()+2*3600000));expect(next.id).not.toBe(q.id);
   await timing.decide(customer,next.id,{action:'confirm'},new Date(end.getTime()+2*3600000));expect((await repo.session(x.session.id)).status).toBe('session_completed');await timing.closeDue(new Date(end.getTime()+4*3600000));expect((await db.query('SELECT status FROM completion_requests WHERE id=$1',[next.id]))[0].status).toBe('confirmed');
 });
 test('a crew session completes even when the first creator has already uploaded',async()=>{
   const body=input(169);body.sessions[0]!.roles[0]!.count=2;const q=await booking.quote(customer,body),o=await booking.checkout(customer,q.id);await booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise,currency:'INR',provider:'test'});
   const s=await db.getRepository(SessionEntity).createQueryBuilder('s').addSelect('s.completionCode').where('s.orderId=:id',{id:o.id}).getOneOrFail(),roles=await db.getRepository(RoleEntity).findBy({sessionId:s.id}),accounts=[creatorAccount,(await db.getRepository(AccountEntity).findOneByOrFail({subject:'demo:creator2'})).id],svc=new SessionService(repo,true);let clock=s.startAt;
   const event=(action:string)=>({clientId:randomUUID(),action,deviceAt:clock.toISOString(),location:{...s.input.venue,accuracy:5},identityProof:'demo-selfie',completionCode:s.completionCode});
   for(const [i,account] of accounts.entries()){const c=await repo.creator(account);await db.getRepository(RoleEntity).update(roles[i]!.id,{creatorId:c.id,status:'assigned'});clock=s.startAt;await svc.transition(account,roles[i]!.id,event('trip'),clock);clock=new Date(s.startAt.getTime()+(20-i*5)*60000);const arrived=event('check_in');await svc.transition(account,roles[i]!.id,arrived,clock);await svc.transition(account,roles[i]!.id,arrived,clock);await svc.transition(account,roles[i]!.id,event('start'),clock);}
   expect((await db.query('SELECT amount_paise FROM customer_credits WHERE reference=$1',[`late-arrival:${s.id}`]))).toEqual([{amount_paise:Math.round(s.totalPaise/10)}]);
   clock=new Date(s.endAt.getTime()+20*60000);await svc.transition(accounts[0]!,roles[0]!.id,event('complete'),clock);const bytes=await sharp({create:{width:100,height:100,channels:3,background:'#a07755'}}).jpeg().toBuffer(),card=await media.manifest(accounts[0]!,{sessionId:s.id,files:[{filename:'crew-test.jpg',bytes:bytes.length,checksum:createHash('sha256').update(bytes).digest('hex'),kind:'edited'}]});await media.chunk(accounts[0]!,card.assets[0].id,0,bytes);await media.receipt(accounts[0]!,card.id);expect((await repo.session(s.id)).status).toBe('in_session');
   await new SessionTimingService(repo).venue(customer,s.id,{allowOverrun:false});expect((await repo.session(s.id)).endAt.getTime()).toBe(s.endAt.getTime()+20*60000);
   await svc.transition(accounts[1]!,roles[1]!.id,event('complete'),clock);expect((await repo.session(s.id)).status).toBe('session_completed');expect((await repo.session(s.id)).completedAt).not.toBeNull();
 });
 test('late overlaps are visible to operations and the next shoot can be reassigned without penalties',async()=>{
   const x=await paid(170),body=input(170);body.sessions[0]!.start=new Date(x.session.startAt.getTime()+4*3600000).toISOString();const q=await booking.quote(customer,body),o=await booking.checkout(customer,q.id);await booking.confirmPayment({id:randomUUID(),orderId:o.id,amountPaise:o.totalPaise,currency:'INR',provider:'test'});const next=await db.getRepository(SessionEntity).findOneByOrFail({orderId:o.id}),nextRole=await db.getRepository(RoleEntity).findOneByOrFail({sessionId:next.id}),c=await repo.creator(creatorAccount),svc=new SessionService(repo,true),timing=new SessionTimingService(repo),late=new Date(x.session.startAt.getTime()+15*60000);
   for(const r of [x.role,nextRole])await db.getRepository(RoleEntity).update(r.id,{creatorId:c.id,status:'assigned'});const event=(action:string,at:Date)=>({clientId:randomUUID(),action,deviceAt:at.toISOString(),location:{...x.session.input.venue,accuracy:5},identityProof:'demo-selfie'});await svc.transition(c.accountId,x.role.id,event('trip',x.session.startAt),x.session.startAt);await svc.transition(c.accountId,x.role.id,event('check_in',late),late);
   expect((await timing.detail(customer,x.session.id)).roles[0]?.overrun_conflict).toBe(true);const queue=await timing.conflicts();expect(queue.find((r:{id:string})=>r.id===x.role.id).next_jobs[0].id).toBe(nextRole.id);
   await timing.resolveConflict(opsId,x.role.id,{nextRoleId:nextRole.id,reason:'Protect both bookings after the delayed arrival'},late);expect((await repo.session(next.id)).status).toBe('confirmed');expect((await db.getRepository(RoleEntity).findOneByOrFail({id:nextRole.id})).creatorId).toBeNull();expect((await db.getRepository(RoleEntity).findOneByOrFail({id:x.role.id})).overrunConflict).toBe(false);expect((await booking.cancelPreview(customer,next.id,late)).platformFault).toBe(true);expect((await db.query('SELECT id FROM creator_cancellations WHERE role_id=$1',[nextRole.id]))).toHaveLength(0);
 });
 test('arrival boundaries reject no-shows and out-of-order device events',async()=>{
   const x=await paid(171),c=await repo.creator(creatorAccount),svc=new SessionService(repo,true);await db.getRepository(RoleEntity).update(x.role.id,{creatorId:c.id,status:'assigned'});
   const event=(action:string,at:Date)=>({clientId:randomUUID(),action,deviceAt:at.toISOString(),location:{...x.session.input.venue,accuracy:5},identityProof:'demo-selfie'});await svc.transition(c.accountId,x.role.id,event('trip',x.session.startAt),x.session.startAt);const earlier=new Date(x.session.startAt.getTime()-60000);await expect(svc.transition(c.accountId,x.role.id,event('check_in',earlier),x.session.startAt)).rejects.toMatchObject({code:'EVENT_ORDER'});
   const late=new Date(x.session.startAt.getTime()+30*60000);await expect(svc.transition(c.accountId,x.role.id,event('check_in',late),late)).rejects.toMatchObject({code:'NO_SHOW_WINDOW'});expect((await db.query('SELECT id FROM customer_credits WHERE reference=$1',[`late-arrival:${x.session.id}`]))).toHaveLength(0);
 });

});
